// Generated by scripts/.cache/calc-audit/status-eot/build/track-a-gen-status-table.ts from pinned Showdown c23d2e94
// (data/moves.ts with the mods applied: gen 9 for Scarlet/Violet, data/mods/champions, data/mods/gen8, data/mods/gen7).
// Data only, no engine imports: every Status move of the four games' catalogs (271), with the build's kind
// (status-eot SPEC §2.2, ADDENDUM §2.2) and the dex fields the 2v2 status-move pipeline (doubles-status.ts) reads.
// tests/source/doubles-status-moves.test.ts checks every field against the pinned dex per game.
import type { BattleGame } from "./types";

/**
 * M: modelled exactly. N: no effect on this turn's HP or order. C: modelled under a condition, otherwise guarded. L: not
 * modelled in this build (not estimated before a later living action; with none only the end of turn). S: switches a
 * Pokémon out. P: presence guard. X: today's handling (doubles-status.ts statusMove's early branches, presence guards).
 */
export type StatusKind = "M" | "N" | "C" | "L" | "S" | "P" | "X";
export type StatusFlags = Partial<Record<"protect" | "reflectable" | "powder" | "sound" | "bypasssub" | "heal" | "wind" | "gravity", true>>;
export type StatusStages = Partial<Record<"atk" | "def" | "spa" | "spd" | "spe" | "accuracy" | "evasion", number>>;
export type StatusEntry = {
  kind: StatusKind;
  /** The dex target type. */
  target: string;
  priority: number;
  type: string;
  flags: StatusFlags;
  /** ignoreImmunity false: type immunity applies (Thunder Wave vs Ground). */
  ignoreImmunity?: false;
  /** moveData.boosts (on each target). */
  boosts?: StatusStages;
  /** moveData.self.boosts (on the user). */
  selfBoosts?: StatusStages;
  /** moveData.self.volatileStatus (Roost). */
  selfVolatile?: string;
  status?: "slp" | "par" | "brn" | "psn" | "tox" | "frz";
  volatile?: string;
  side?: string;
  slot?: string;
  heal?: [number, number];
  selfdestruct?: string;
  /** The move's own onHit or condition the pipeline runs (doubles-status.ts onHit, volatile, sideOrField). */
  handler?: string;
  /** The move's own Try or TryHit failure the pipeline checks (doubles-status.ts moveTry, hitOne). */
  fails?: string;
  /** Each catalog game that has the move, with the fields that differ there (null: absent there). */
  games: Partial<Record<BattleGame, Partial<Record<keyof Omit<StatusEntry, "kind" | "games" | "handler" | "fails">, unknown>>>>;
};

export const STATUS_MOVE_TABLE: Readonly<Record<string, StatusEntry>> = {
  acidarmor: {kind:"M",target:"self",priority:0,type:"Poison",flags:{},boosts:{def:2},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  acupressure: {kind:"L",target:"adjacentAllyOrSelf",priority:0,type:"Normal",flags:{},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  afteryou: {kind:"M",target:"normal",priority:0,type:"Normal",flags:{bypasssub:true},handler:"afterYou",fails:"queued",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  agility: {kind:"M",target:"self",priority:0,type:"Psychic",flags:{},boosts:{spe:2},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  allyswitch: {kind:"M",target:"self",priority:2,type:"Psychic",flags:{},handler:"allySwitch",fails:"allySwitch",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  amnesia: {kind:"M",target:"self",priority:0,type:"Psychic",flags:{},boosts:{spd:2},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  aquaring: {kind:"M",target:"self",priority:0,type:"Water",flags:{},volatile:"aquaring",handler:"aquaRing",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  aromatherapy: {kind:"L",target:"allyTeam",priority:0,type:"Grass",flags:{},games:{sword_shield:{},ultra_sun_ultra_moon:{}}},
  aromaticmist: {kind:"M",target:"adjacentAlly",priority:0,type:"Fairy",flags:{bypasssub:true},boosts:{spd:1},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  assist: {kind:"X",target:"self",priority:0,type:"Normal",flags:{},games:{ultra_sun_ultra_moon:{}}},
  attract: {kind:"L",target:"normal",priority:0,type:"Normal",flags:{protect:true,reflectable:true,bypasssub:true},volatile:"attract",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  auroraveil: {kind:"X",target:"allySide",priority:0,type:"Ice",flags:{},side:"auroraveil",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  autotomize: {kind:"L",target:"self",priority:0,type:"Steel",flags:{},boosts:{spe:2},games:{sword_shield:{},ultra_sun_ultra_moon:{}}},
  babydolleyes: {kind:"M",target:"normal",priority:1,type:"Fairy",flags:{protect:true,reflectable:true},boosts:{atk:-1},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  banefulbunker: {kind:"X",target:"self",priority:4,type:"Poison",flags:{},volatile:"banefulbunker",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  barrier: {kind:"M",target:"self",priority:0,type:"Psychic",flags:{},boosts:{def:2},games:{ultra_sun_ultra_moon:{}}},
  batonpass: {kind:"S",target:"self",priority:0,type:"Normal",flags:{},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  bellydrum: {kind:"M",target:"self",priority:0,type:"Normal",flags:{},handler:"bellyDrum",fails:"bellyDrum",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  bestow: {kind:"L",target:"normal",priority:0,type:"Normal",flags:{bypasssub:true},games:{ultra_sun_ultra_moon:{}}},
  block: {kind:"N",target:"normal",priority:0,type:"Normal",flags:{reflectable:true},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  bulkup: {kind:"M",target:"self",priority:0,type:"Fighting",flags:{},boosts:{atk:1,def:1},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  burningbulwark: {kind:"X",target:"self",priority:4,type:"Fire",flags:{},volatile:"burningbulwark",games:{scarlet_violet:{}}},
  calmmind: {kind:"M",target:"self",priority:0,type:"Psychic",flags:{},boosts:{spa:1,spd:1},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  camouflage: {kind:"L",target:"self",priority:0,type:"Normal",flags:{},games:{ultra_sun_ultra_moon:{}}},
  captivate: {kind:"L",target:"allAdjacentFoes",priority:0,type:"Normal",flags:{protect:true,reflectable:true},boosts:{spa:-2},games:{ultra_sun_ultra_moon:{}}},
  celebrate: {kind:"N",target:"self",priority:0,type:"Normal",flags:{},games:{scarlet_violet:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  charge: {kind:"M",target:"self",priority:0,type:"Electric",flags:{},boosts:{spd:1},volatile:"charge",handler:"charge",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  charm: {kind:"M",target:"normal",priority:0,type:"Fairy",flags:{protect:true,reflectable:true},boosts:{atk:-2},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  chillyreception: {kind:"S",target:"all",priority:0,type:"Ice",flags:{},games:{scarlet_violet:{},champions:{}}},
  clangoroussoul: {kind:"M",target:"self",priority:0,type:"Dragon",flags:{sound:true},boosts:{atk:1,def:1,spa:1,spd:1,spe:1},handler:"clangorousSoul",fails:"clangorousSoul",games:{scarlet_violet:{},champions:{},sword_shield:{}}},
  coaching: {kind:"M",target:"adjacentAlly",priority:0,type:"Fighting",flags:{bypasssub:true},boosts:{atk:1,def:1},games:{scarlet_violet:{},champions:{},sword_shield:{}}},
  coil: {kind:"M",target:"self",priority:0,type:"Poison",flags:{},boosts:{atk:1,def:1,accuracy:1},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  confide: {kind:"M",target:"normal",priority:0,type:"Normal",flags:{reflectable:true,sound:true,bypasssub:true},boosts:{spa:-1},games:{scarlet_violet:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  confuseray: {kind:"M",target:"normal",priority:0,type:"Ghost",flags:{protect:true,reflectable:true},volatile:"confusion",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  conversion: {kind:"L",target:"self",priority:0,type:"Normal",flags:{},games:{scarlet_violet:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  conversion2: {kind:"L",target:"normal",priority:0,type:"Normal",flags:{bypasssub:true},games:{scarlet_violet:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  copycat: {kind:"X",target:"self",priority:0,type:"Normal",flags:{},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  corrosivegas: {kind:"L",target:"allAdjacent",priority:0,type:"Poison",flags:{protect:true,reflectable:true},games:{champions:{},sword_shield:{}}},
  cosmicpower: {kind:"M",target:"self",priority:0,type:"Psychic",flags:{},boosts:{def:1,spd:1},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  cottonguard: {kind:"M",target:"self",priority:0,type:"Grass",flags:{},boosts:{def:3},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  cottonspore: {kind:"M",target:"allAdjacentFoes",priority:0,type:"Grass",flags:{protect:true,reflectable:true,powder:true},boosts:{spe:-2},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  courtchange: {kind:"L",target:"all",priority:0,type:"Normal",flags:{},games:{scarlet_violet:{},champions:{},sword_shield:{}}},
  craftyshield: {kind:"L",target:"allySide",priority:3,type:"Fairy",flags:{},side:"craftyshield",games:{sword_shield:{},ultra_sun_ultra_moon:{}}},
  curse: {kind:"M",target:"normal",priority:0,type:"Ghost",flags:{bypasssub:true},volatile:"curse",handler:"curse",fails:"cursed",games:{scarlet_violet:{},champions:{},sword_shield:{target:"randomNormal"},ultra_sun_ultra_moon:{}}},
  darkvoid: {kind:"M",target:"allAdjacentFoes",priority:0,type:"Dark",flags:{protect:true,reflectable:true},status:"slp",handler:"darkVoid",fails:"darkrai",games:{scarlet_violet:{},ultra_sun_ultra_moon:{}}},
  decorate: {kind:"M",target:"normal",priority:0,type:"Fairy",flags:{},boosts:{atk:2,spa:2},games:{scarlet_violet:{},champions:{},sword_shield:{}}},
  defendorder: {kind:"M",target:"self",priority:0,type:"Bug",flags:{},boosts:{def:1,spd:1},games:{scarlet_violet:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  defensecurl: {kind:"M",target:"self",priority:0,type:"Normal",flags:{},boosts:{def:1},volatile:"defensecurl",games:{scarlet_violet:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  defog: {kind:"L",target:"normal",priority:0,type:"Flying",flags:{protect:true,reflectable:true,bypasssub:true},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  destinybond: {kind:"M",target:"self",priority:0,type:"Ghost",flags:{bypasssub:true},volatile:"destinybond",handler:"destinyBond",fails:"destinyBond",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  detect: {kind:"X",target:"self",priority:4,type:"Fighting",flags:{},volatile:"protect",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  disable: {kind:"C",target:"normal",priority:0,type:"Normal",flags:{protect:true,reflectable:true,bypasssub:true},volatile:"disable",handler:"disable",fails:"lastMove",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  doodle: {kind:"L",target:"adjacentFoe",priority:0,type:"Normal",flags:{},games:{scarlet_violet:{}}},
  doubleteam: {kind:"M",target:"self",priority:0,type:"Normal",flags:{},boosts:{evasion:1},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  dragoncheer: {kind:"M",target:"adjacentAlly",priority:0,type:"Dragon",flags:{bypasssub:true},volatile:"dragoncheer",handler:"dragonCheer",fails:"critVolatile",games:{scarlet_violet:{},champions:{flags:{sound:true,bypasssub:true}}}},
  dragondance: {kind:"M",target:"self",priority:0,type:"Dragon",flags:{},boosts:{atk:1,spe:1},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  eerieimpulse: {kind:"M",target:"normal",priority:0,type:"Electric",flags:{protect:true,reflectable:true},boosts:{spa:-2},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  electricterrain: {kind:"X",target:"all",priority:0,type:"Electric",flags:{},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  electrify: {kind:"L",target:"normal",priority:0,type:"Electric",flags:{protect:true},volatile:"electrify",games:{champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  embargo: {kind:"L",target:"normal",priority:0,type:"Dark",flags:{protect:true,reflectable:true},volatile:"embargo",games:{ultra_sun_ultra_moon:{}}},
  encore: {kind:"C",target:"normal",priority:0,type:"Normal",flags:{protect:true,reflectable:true,bypasssub:true},volatile:"encore",handler:"encore",fails:"lastMove",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  endure: {kind:"M",target:"self",priority:4,type:"Normal",flags:{},volatile:"endure",handler:"endure",fails:"stall",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  entrainment: {kind:"L",target:"normal",priority:0,type:"Normal",flags:{protect:true,reflectable:true},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  extremeevoboost: {kind:"X",target:"self",priority:0,type:"Normal",flags:{},boosts:{atk:2,def:2,spa:2,spd:2,spe:2},games:{ultra_sun_ultra_moon:{}}},
  fairylock: {kind:"N",target:"all",priority:0,type:"Fairy",flags:{bypasssub:true},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  faketears: {kind:"M",target:"normal",priority:0,type:"Dark",flags:{protect:true,reflectable:true},boosts:{spd:-2},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  featherdance: {kind:"M",target:"normal",priority:0,type:"Flying",flags:{protect:true,reflectable:true},boosts:{atk:-2},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  filletaway: {kind:"M",target:"self",priority:0,type:"Normal",flags:{},boosts:{atk:2,spa:2,spe:2},handler:"filletAway",fails:"halfHP",games:{scarlet_violet:{}}},
  flash: {kind:"M",target:"normal",priority:0,type:"Normal",flags:{protect:true,reflectable:true},boosts:{accuracy:-1},games:{ultra_sun_ultra_moon:{}}},
  flatter: {kind:"M",target:"normal",priority:0,type:"Dark",flags:{protect:true,reflectable:true},boosts:{spa:1},volatile:"confusion",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  floralhealing: {kind:"M",target:"normal",priority:0,type:"Fairy",flags:{protect:true,reflectable:true,heal:true},handler:"floralHealing",games:{scarlet_violet:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  flowershield: {kind:"L",target:"all",priority:0,type:"Fairy",flags:{},games:{sword_shield:{},ultra_sun_ultra_moon:{}}},
  focusenergy: {kind:"M",target:"self",priority:0,type:"Normal",flags:{},volatile:"focusenergy",handler:"focusEnergy",fails:"critVolatile",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  followme: {kind:"X",target:"self",priority:2,type:"Normal",flags:{},volatile:"followme",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  foresight: {kind:"L",target:"normal",priority:0,type:"Normal",flags:{protect:true,reflectable:true,bypasssub:true},volatile:"foresight",games:{ultra_sun_ultra_moon:{}}},
  forestscurse: {kind:"L",target:"normal",priority:0,type:"Grass",flags:{protect:true,reflectable:true},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  gastroacid: {kind:"L",target:"normal",priority:0,type:"Poison",flags:{protect:true,reflectable:true},volatile:"gastroacid",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  gearup: {kind:"L",target:"allySide",priority:0,type:"Steel",flags:{bypasssub:true},games:{sword_shield:{},ultra_sun_ultra_moon:{}}},
  geomancy: {kind:"L",target:"self",priority:0,type:"Fairy",flags:{},boosts:{spa:2,spd:2,spe:2},games:{sword_shield:{},ultra_sun_ultra_moon:{}}},
  glare: {kind:"M",target:"normal",priority:0,type:"Normal",flags:{protect:true,reflectable:true},status:"par",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  grasswhistle: {kind:"M",target:"normal",priority:0,type:"Grass",flags:{protect:true,reflectable:true,sound:true,bypasssub:true},status:"slp",games:{ultra_sun_ultra_moon:{}}},
  grassyterrain: {kind:"X",target:"all",priority:0,type:"Grass",flags:{},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  gravity: {kind:"X",target:"all",priority:0,type:"Psychic",flags:{},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  growl: {kind:"M",target:"allAdjacentFoes",priority:0,type:"Normal",flags:{protect:true,reflectable:true,sound:true,bypasssub:true},boosts:{atk:-1},games:{scarlet_violet:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  growth: {kind:"M",target:"self",priority:0,type:"Normal",flags:{},boosts:{atk:1,spa:1},handler:"growth",games:{scarlet_violet:{},champions:{type:"Grass"},sword_shield:{},ultra_sun_ultra_moon:{}}},
  grudge: {kind:"N",target:"self",priority:0,type:"Ghost",flags:{bypasssub:true},volatile:"grudge",games:{sword_shield:{},ultra_sun_ultra_moon:{}}},
  guardsplit: {kind:"L",target:"normal",priority:0,type:"Psychic",flags:{protect:true},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  guardswap: {kind:"L",target:"normal",priority:0,type:"Psychic",flags:{protect:true,bypasssub:true},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  hail: {kind:"X",target:"all",priority:0,type:"Ice",flags:{},games:{sword_shield:{},ultra_sun_ultra_moon:{}}},
  happyhour: {kind:"N",target:"allySide",priority:0,type:"Normal",flags:{},games:{scarlet_violet:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  harden: {kind:"M",target:"self",priority:0,type:"Normal",flags:{},boosts:{def:1},games:{scarlet_violet:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  haze: {kind:"M",target:"all",priority:0,type:"Ice",flags:{bypasssub:true},handler:"haze",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  healbell: {kind:"L",target:"allyTeam",priority:0,type:"Normal",flags:{sound:true,bypasssub:true},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  healblock: {kind:"L",target:"allAdjacentFoes",priority:0,type:"Psychic",flags:{protect:true,reflectable:true},volatile:"healblock",games:{ultra_sun_ultra_moon:{}}},
  healingwish: {kind:"M",target:"self",priority:0,type:"Psychic",flags:{heal:true},slot:"healingwish",selfdestruct:"ifHit",handler:"healingWish",fails:"canSwitch",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  healorder: {kind:"M",target:"self",priority:0,type:"Bug",flags:{heal:true},heal:[1,2],games:{ultra_sun_ultra_moon:{}}},
  healpulse: {kind:"M",target:"any",priority:0,type:"Psychic",flags:{protect:true,reflectable:true,heal:true},handler:"healPulse",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  heartswap: {kind:"L",target:"normal",priority:0,type:"Psychic",flags:{protect:true,bypasssub:true},games:{scarlet_violet:{},ultra_sun_ultra_moon:{}}},
  helpinghand: {kind:"X",target:"adjacentAlly",priority:5,type:"Normal",flags:{bypasssub:true},volatile:"helpinghand",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  holdhands: {kind:"N",target:"adjacentAlly",priority:0,type:"Normal",flags:{bypasssub:true},games:{sword_shield:{},ultra_sun_ultra_moon:{}}},
  honeclaws: {kind:"M",target:"self",priority:0,type:"Dark",flags:{},boosts:{atk:1,accuracy:1},games:{scarlet_violet:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  howl: {kind:"M",target:"allies",priority:0,type:"Normal",flags:{sound:true},boosts:{atk:1},games:{scarlet_violet:{},champions:{flags:{sound:true,bypasssub:true}},sword_shield:{},ultra_sun_ultra_moon:{target:"self",flags:{}}}},
  hypnosis: {kind:"M",target:"normal",priority:0,type:"Psychic",flags:{protect:true,reflectable:true},status:"slp",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  imprison: {kind:"C",target:"self",priority:0,type:"Psychic",flags:{bypasssub:true},volatile:"imprison",handler:"imprison",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  ingrain: {kind:"C",target:"self",priority:0,type:"Grass",flags:{},volatile:"ingrain",handler:"ingrain",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  instruct: {kind:"X",target:"normal",priority:0,type:"Psychic",flags:{protect:true,bypasssub:true},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  iondeluge: {kind:"L",target:"all",priority:1,type:"Electric",flags:{},games:{ultra_sun_ultra_moon:{}}},
  irondefense: {kind:"M",target:"self",priority:0,type:"Steel",flags:{},boosts:{def:2},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  junglehealing: {kind:"M",target:"allies",priority:0,type:"Grass",flags:{bypasssub:true,heal:true},handler:"jungleHealing",games:{scarlet_violet:{},sword_shield:{}}},
  kinesis: {kind:"M",target:"normal",priority:0,type:"Psychic",flags:{protect:true,reflectable:true},boosts:{accuracy:-1},games:{sword_shield:{},ultra_sun_ultra_moon:{}}},
  kingsshield: {kind:"X",target:"self",priority:4,type:"Steel",flags:{},volatile:"kingsshield",games:{champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  laserfocus: {kind:"N",target:"self",priority:0,type:"Normal",flags:{},volatile:"laserfocus",games:{sword_shield:{},ultra_sun_ultra_moon:{}}},
  leechseed: {kind:"M",target:"normal",priority:0,type:"Grass",flags:{protect:true,reflectable:true},volatile:"leechseed",handler:"leechSeed",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  leer: {kind:"M",target:"allAdjacentFoes",priority:0,type:"Normal",flags:{protect:true,reflectable:true},boosts:{def:-1},games:{scarlet_violet:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  lifedew: {kind:"M",target:"allies",priority:0,type:"Water",flags:{bypasssub:true,heal:true},heal:[1,4],games:{scarlet_violet:{},champions:{},sword_shield:{}}},
  lightscreen: {kind:"X",target:"allySide",priority:0,type:"Psychic",flags:{},side:"lightscreen",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  lockon: {kind:"N",target:"normal",priority:0,type:"Normal",flags:{protect:true},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  lovelykiss: {kind:"M",target:"normal",priority:0,type:"Normal",flags:{protect:true,reflectable:true},status:"slp",games:{sword_shield:{},ultra_sun_ultra_moon:{}}},
  luckychant: {kind:"L",target:"allySide",priority:0,type:"Normal",flags:{},side:"luckychant",games:{ultra_sun_ultra_moon:{}}},
  lunarblessing: {kind:"M",target:"allies",priority:0,type:"Psychic",flags:{heal:true},handler:"jungleHealing",games:{scarlet_violet:{}}},
  lunardance: {kind:"M",target:"self",priority:0,type:"Psychic",flags:{heal:true},slot:"lunardance",selfdestruct:"ifHit",handler:"healingWish",fails:"canSwitch",games:{scarlet_violet:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  magiccoat: {kind:"L",target:"self",priority:4,type:"Psychic",flags:{},volatile:"magiccoat",games:{sword_shield:{},ultra_sun_ultra_moon:{}}},
  magicpowder: {kind:"L",target:"normal",priority:0,type:"Psychic",flags:{protect:true,reflectable:true,powder:true},games:{scarlet_violet:{},champions:{},sword_shield:{}}},
  magicroom: {kind:"L",target:"all",priority:0,type:"Psychic",flags:{},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  magneticflux: {kind:"L",target:"allySide",priority:0,type:"Electric",flags:{bypasssub:true},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  magnetrise: {kind:"C",target:"self",priority:0,type:"Electric",flags:{gravity:true},volatile:"magnetrise",handler:"magnetRise",fails:"magnetRise",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  matblock: {kind:"L",target:"allySide",priority:0,type:"Fighting",flags:{},side:"matblock",games:{sword_shield:{},ultra_sun_ultra_moon:{}}},
  maxguard: {kind:"X",target:"self",priority:4,type:"Normal",flags:{},volatile:"maxguard",games:{sword_shield:{}}},
  meanlook: {kind:"N",target:"normal",priority:0,type:"Normal",flags:{reflectable:true},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  meditate: {kind:"M",target:"self",priority:0,type:"Psychic",flags:{},boosts:{atk:1},games:{ultra_sun_ultra_moon:{}}},
  mefirst: {kind:"X",target:"adjacentFoe",priority:0,type:"Normal",flags:{protect:true,bypasssub:true},games:{ultra_sun_ultra_moon:{}}},
  memento: {kind:"M",target:"normal",priority:0,type:"Dark",flags:{protect:true},boosts:{atk:-2,spa:-2},selfdestruct:"ifHit",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  metalsound: {kind:"M",target:"normal",priority:0,type:"Steel",flags:{protect:true,reflectable:true,sound:true,bypasssub:true},boosts:{spd:-2},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  metronome: {kind:"X",target:"self",priority:0,type:"Normal",flags:{},games:{scarlet_violet:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  milkdrink: {kind:"M",target:"self",priority:0,type:"Normal",flags:{heal:true},heal:[1,2],games:{scarlet_violet:{},champions:{target:"adjacentAllyOrSelf"},sword_shield:{},ultra_sun_ultra_moon:{}}},
  mimic: {kind:"N",target:"normal",priority:0,type:"Normal",flags:{protect:true,bypasssub:true},games:{scarlet_violet:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  mindreader: {kind:"N",target:"normal",priority:0,type:"Normal",flags:{protect:true},games:{sword_shield:{},ultra_sun_ultra_moon:{}}},
  minimize: {kind:"L",target:"self",priority:0,type:"Normal",flags:{},boosts:{evasion:2},volatile:"minimize",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  miracleeye: {kind:"L",target:"normal",priority:0,type:"Psychic",flags:{protect:true,reflectable:true,bypasssub:true},volatile:"miracleeye",games:{ultra_sun_ultra_moon:{}}},
  mirrormove: {kind:"X",target:"normal",priority:0,type:"Flying",flags:{},games:{ultra_sun_ultra_moon:{}}},
  mist: {kind:"L",target:"allySide",priority:0,type:"Ice",flags:{},side:"mist",games:{scarlet_violet:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  mistyterrain: {kind:"X",target:"all",priority:0,type:"Fairy",flags:{},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  moonlight: {kind:"M",target:"self",priority:0,type:"Fairy",flags:{heal:true},handler:"weatherHeal",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  morningsun: {kind:"M",target:"self",priority:0,type:"Normal",flags:{heal:true},handler:"weatherHeal",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  mudsport: {kind:"L",target:"all",priority:0,type:"Ground",flags:{},games:{ultra_sun_ultra_moon:{}}},
  nastyplot: {kind:"M",target:"self",priority:0,type:"Dark",flags:{},boosts:{spa:2},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  naturepower: {kind:"X",target:"normal",priority:0,type:"Normal",flags:{},games:{sword_shield:{},ultra_sun_ultra_moon:{}}},
  nightmare: {kind:"L",target:"normal",priority:0,type:"Ghost",flags:{protect:true},volatile:"nightmare",games:{ultra_sun_ultra_moon:{}}},
  nobleroar: {kind:"M",target:"normal",priority:0,type:"Normal",flags:{protect:true,reflectable:true,sound:true,bypasssub:true},boosts:{atk:-1,spa:-1},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  noretreat: {kind:"L",target:"self",priority:0,type:"Fighting",flags:{},boosts:{atk:1,def:1,spa:1,spd:1,spe:1},volatile:"noretreat",games:{scarlet_violet:{},champions:{},sword_shield:{}}},
  obstruct: {kind:"X",target:"self",priority:4,type:"Dark",flags:{},volatile:"obstruct",games:{sword_shield:{}}},
  octolock: {kind:"L",target:"normal",priority:0,type:"Fighting",flags:{protect:true},volatile:"octolock",games:{champions:{},sword_shield:{}}},
  odorsleuth: {kind:"L",target:"normal",priority:0,type:"Normal",flags:{protect:true,reflectable:true,bypasssub:true},volatile:"foresight",games:{ultra_sun_ultra_moon:{}}},
  painsplit: {kind:"M",target:"normal",priority:0,type:"Normal",flags:{protect:true},handler:"painSplit",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  partingshot: {kind:"S",target:"normal",priority:0,type:"Dark",flags:{protect:true,reflectable:true,sound:true,bypasssub:true},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  perishsong: {kind:"M",target:"all",priority:0,type:"Normal",flags:{sound:true,bypasssub:true},handler:"perishSong",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  playnice: {kind:"M",target:"normal",priority:0,type:"Normal",flags:{reflectable:true,bypasssub:true},boosts:{atk:-1},games:{scarlet_violet:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  poisongas: {kind:"M",target:"allAdjacentFoes",priority:0,type:"Poison",flags:{protect:true,reflectable:true},status:"psn",games:{scarlet_violet:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  poisonpowder: {kind:"M",target:"normal",priority:0,type:"Poison",flags:{protect:true,reflectable:true,powder:true},status:"psn",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  powder: {kind:"L",target:"normal",priority:1,type:"Bug",flags:{protect:true,reflectable:true,powder:true,bypasssub:true},volatile:"powder",games:{ultra_sun_ultra_moon:{}}},
  powershift: {kind:"L",target:"self",priority:0,type:"Normal",flags:{},volatile:"powershift",games:{champions:{}}},
  powersplit: {kind:"L",target:"normal",priority:0,type:"Psychic",flags:{protect:true},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  powerswap: {kind:"L",target:"normal",priority:0,type:"Psychic",flags:{protect:true,bypasssub:true},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  powertrick: {kind:"L",target:"self",priority:0,type:"Psychic",flags:{},volatile:"powertrick",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  protect: {kind:"X",target:"self",priority:4,type:"Normal",flags:{},volatile:"protect",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  psychicterrain: {kind:"X",target:"all",priority:0,type:"Psychic",flags:{},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  psychoshift: {kind:"L",target:"normal",priority:0,type:"Psychic",flags:{protect:true},games:{sword_shield:{},ultra_sun_ultra_moon:{}}},
  psychup: {kind:"L",target:"normal",priority:0,type:"Normal",flags:{bypasssub:true},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  purify: {kind:"L",target:"normal",priority:0,type:"Poison",flags:{protect:true,reflectable:true,heal:true},games:{sword_shield:{},ultra_sun_ultra_moon:{}}},
  quash: {kind:"M",target:"normal",priority:0,type:"Dark",flags:{protect:true},handler:"quash",fails:"queued",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  quickguard: {kind:"X",target:"allySide",priority:3,type:"Fighting",flags:{},side:"quickguard",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  quiverdance: {kind:"M",target:"self",priority:0,type:"Bug",flags:{},boosts:{spa:1,spd:1,spe:1},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  ragepowder: {kind:"X",target:"self",priority:2,type:"Bug",flags:{powder:true},volatile:"ragepowder",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  raindance: {kind:"X",target:"all",priority:0,type:"Water",flags:{},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  recover: {kind:"M",target:"self",priority:0,type:"Normal",flags:{heal:true},heal:[1,2],games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  recycle: {kind:"L",target:"self",priority:0,type:"Normal",flags:{},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  reflect: {kind:"X",target:"allySide",priority:0,type:"Psychic",flags:{},side:"reflect",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  reflecttype: {kind:"L",target:"normal",priority:0,type:"Normal",flags:{protect:true,bypasssub:true},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  refresh: {kind:"M",target:"self",priority:0,type:"Normal",flags:{},handler:"refresh",games:{ultra_sun_ultra_moon:{}}},
  rest: {kind:"M",target:"self",priority:0,type:"Psychic",flags:{heal:true},handler:"rest",fails:"rest",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  revivalblessing: {kind:"P",target:"self",priority:0,type:"Normal",flags:{heal:true},slot:"revivalblessing",games:{scarlet_violet:{},champions:{}}},
  roar: {kind:"S",target:"normal",priority:-6,type:"Normal",flags:{reflectable:true,sound:true,bypasssub:true},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  rockpolish: {kind:"M",target:"self",priority:0,type:"Rock",flags:{},boosts:{spe:2},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  roleplay: {kind:"L",target:"normal",priority:0,type:"Psychic",flags:{bypasssub:true},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  roost: {kind:"C",target:"self",priority:0,type:"Flying",flags:{heal:true},selfVolatile:"roost",heal:[1,2],handler:"roost",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  rototiller: {kind:"L",target:"all",priority:0,type:"Ground",flags:{},games:{ultra_sun_ultra_moon:{}}},
  safeguard: {kind:"M",target:"allySide",priority:0,type:"Normal",flags:{},side:"safeguard",handler:"safeguard",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  sandattack: {kind:"M",target:"normal",priority:0,type:"Ground",flags:{protect:true,reflectable:true},boosts:{accuracy:-1},games:{scarlet_violet:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  sandstorm: {kind:"X",target:"all",priority:0,type:"Rock",flags:{wind:true},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  scaryface: {kind:"M",target:"normal",priority:0,type:"Normal",flags:{protect:true,reflectable:true},boosts:{spe:-2},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  screech: {kind:"M",target:"normal",priority:0,type:"Normal",flags:{protect:true,reflectable:true,sound:true,bypasssub:true},boosts:{def:-2},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  sharpen: {kind:"M",target:"self",priority:0,type:"Normal",flags:{},boosts:{atk:1},games:{ultra_sun_ultra_moon:{}}},
  shedtail: {kind:"S",target:"self",priority:0,type:"Normal",flags:{},volatile:"substitute",games:{scarlet_violet:{},champions:{}}},
  shellsmash: {kind:"M",target:"self",priority:0,type:"Normal",flags:{},boosts:{def:-1,spd:-1,atk:2,spa:2,spe:2},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  shelter: {kind:"M",target:"self",priority:0,type:"Steel",flags:{},boosts:{def:2},games:{scarlet_violet:{},champions:{}}},
  shiftgear: {kind:"M",target:"self",priority:0,type:"Steel",flags:{},boosts:{spe:2,atk:1},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  shoreup: {kind:"M",target:"self",priority:0,type:"Ground",flags:{heal:true},handler:"shoreUp",games:{scarlet_violet:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  silktrap: {kind:"X",target:"self",priority:4,type:"Bug",flags:{},volatile:"silktrap",games:{scarlet_violet:{}}},
  simplebeam: {kind:"L",target:"normal",priority:0,type:"Normal",flags:{protect:true,reflectable:true},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  sing: {kind:"M",target:"normal",priority:0,type:"Normal",flags:{protect:true,reflectable:true,sound:true,bypasssub:true},status:"slp",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  sketch: {kind:"N",target:"normal",priority:0,type:"Normal",flags:{bypasssub:true},games:{scarlet_violet:{},ultra_sun_ultra_moon:{}}},
  skillswap: {kind:"L",target:"normal",priority:0,type:"Psychic",flags:{protect:true,bypasssub:true},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  slackoff: {kind:"M",target:"self",priority:0,type:"Normal",flags:{heal:true},heal:[1,2],games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  sleeppowder: {kind:"M",target:"normal",priority:0,type:"Grass",flags:{protect:true,reflectable:true,powder:true},status:"slp",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  sleeptalk: {kind:"X",target:"self",priority:0,type:"Normal",flags:{},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  smokescreen: {kind:"M",target:"normal",priority:0,type:"Normal",flags:{protect:true,reflectable:true},boosts:{accuracy:-1},games:{scarlet_violet:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  snatch: {kind:"L",target:"self",priority:4,type:"Dark",flags:{bypasssub:true},volatile:"snatch",games:{ultra_sun_ultra_moon:{}}},
  snowscape: {kind:"X",target:"all",priority:0,type:"Ice",flags:{},games:{scarlet_violet:{},champions:{}}},
  soak: {kind:"L",target:"normal",priority:0,type:"Water",flags:{protect:true,reflectable:true},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  softboiled: {kind:"M",target:"self",priority:0,type:"Normal",flags:{heal:true},heal:[1,2],games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  speedswap: {kind:"L",target:"normal",priority:0,type:"Psychic",flags:{protect:true,bypasssub:true},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  spicyextract: {kind:"M",target:"normal",priority:0,type:"Grass",flags:{protect:true,reflectable:true},boosts:{atk:2,def:-2},games:{scarlet_violet:{},champions:{}}},
  spiderweb: {kind:"N",target:"normal",priority:0,type:"Bug",flags:{protect:true,reflectable:true},games:{ultra_sun_ultra_moon:{}}},
  spikes: {kind:"N",target:"foeSide",priority:0,type:"Ground",flags:{reflectable:true},side:"spikes",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  spikyshield: {kind:"X",target:"self",priority:4,type:"Grass",flags:{},volatile:"spikyshield",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  spite: {kind:"N",target:"normal",priority:0,type:"Ghost",flags:{protect:true,reflectable:true,bypasssub:true},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  splash: {kind:"N",target:"self",priority:0,type:"Normal",flags:{gravity:true},games:{scarlet_violet:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  spore: {kind:"M",target:"normal",priority:0,type:"Grass",flags:{protect:true,reflectable:true,powder:true},status:"slp",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  spotlight: {kind:"X",target:"normal",priority:3,type:"Normal",flags:{protect:true,reflectable:true},volatile:"spotlight",games:{ultra_sun_ultra_moon:{}}},
  stealthrock: {kind:"N",target:"foeSide",priority:0,type:"Rock",flags:{reflectable:true},side:"stealthrock",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  stickyweb: {kind:"N",target:"foeSide",priority:0,type:"Bug",flags:{reflectable:true},side:"stickyweb",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  stockpile: {kind:"L",target:"self",priority:0,type:"Normal",flags:{},volatile:"stockpile",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  strengthsap: {kind:"M",target:"normal",priority:0,type:"Grass",flags:{protect:true,reflectable:true,heal:true},handler:"strengthSap",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  stringshot: {kind:"M",target:"allAdjacentFoes",priority:0,type:"Bug",flags:{protect:true,reflectable:true},boosts:{spe:-2},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  stuffcheeks: {kind:"L",target:"self",priority:0,type:"Normal",flags:{},games:{scarlet_violet:{},champions:{},sword_shield:{}}},
  stunspore: {kind:"M",target:"normal",priority:0,type:"Grass",flags:{protect:true,reflectable:true,powder:true},status:"par",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  substitute: {kind:"M",target:"self",priority:0,type:"Normal",flags:{},volatile:"substitute",handler:"substitute",fails:"substitute",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  sunnyday: {kind:"X",target:"all",priority:0,type:"Fire",flags:{},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  supersonic: {kind:"M",target:"normal",priority:0,type:"Normal",flags:{protect:true,reflectable:true,sound:true,bypasssub:true},volatile:"confusion",games:{scarlet_violet:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  swagger: {kind:"M",target:"normal",priority:0,type:"Normal",flags:{protect:true,reflectable:true},boosts:{atk:2},volatile:"confusion",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  swallow: {kind:"L",target:"self",priority:0,type:"Normal",flags:{heal:true},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  sweetkiss: {kind:"M",target:"normal",priority:0,type:"Fairy",flags:{protect:true,reflectable:true},volatile:"confusion",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  sweetscent: {kind:"M",target:"allAdjacentFoes",priority:0,type:"Normal",flags:{protect:true,reflectable:true},boosts:{evasion:-2},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  switcheroo: {kind:"M",target:"normal",priority:0,type:"Dark",flags:{protect:true},handler:"swapItems",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  swordsdance: {kind:"M",target:"self",priority:0,type:"Normal",flags:{},boosts:{atk:2},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  synthesis: {kind:"M",target:"self",priority:0,type:"Grass",flags:{heal:true},handler:"weatherHeal",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  tailglow: {kind:"M",target:"self",priority:0,type:"Bug",flags:{},boosts:{spa:3},games:{scarlet_violet:{},ultra_sun_ultra_moon:{}}},
  tailwhip: {kind:"M",target:"allAdjacentFoes",priority:0,type:"Normal",flags:{protect:true,reflectable:true},boosts:{def:-1},games:{scarlet_violet:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  tailwind: {kind:"X",target:"allySide",priority:0,type:"Flying",flags:{wind:true},side:"tailwind",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  takeheart: {kind:"M",target:"self",priority:0,type:"Psychic",flags:{},handler:"takeHeart",games:{scarlet_violet:{}}},
  tarshot: {kind:"L",target:"normal",priority:0,type:"Rock",flags:{protect:true,reflectable:true},boosts:{spe:-1},volatile:"tarshot",games:{scarlet_violet:{},sword_shield:{}}},
  taunt: {kind:"M",target:"normal",priority:0,type:"Dark",flags:{protect:true,reflectable:true,bypasssub:true},volatile:"taunt",handler:"taunt",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  tearfullook: {kind:"M",target:"normal",priority:0,type:"Normal",flags:{reflectable:true},boosts:{atk:-1,spa:-1},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  teatime: {kind:"L",target:"all",priority:0,type:"Normal",flags:{bypasssub:true},games:{scarlet_violet:{},champions:{},sword_shield:{}}},
  teeterdance: {kind:"M",target:"allAdjacent",priority:0,type:"Normal",flags:{protect:true},volatile:"confusion",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  telekinesis: {kind:"L",target:"normal",priority:0,type:"Psychic",flags:{protect:true,reflectable:true,gravity:true},volatile:"telekinesis",games:{ultra_sun_ultra_moon:{}}},
  teleport: {kind:"S",target:"self",priority:-6,type:"Psychic",flags:{},games:{scarlet_violet:{},sword_shield:{},ultra_sun_ultra_moon:{priority:0}}},
  thunderwave: {kind:"M",target:"normal",priority:0,type:"Electric",flags:{protect:true,reflectable:true},ignoreImmunity:false,status:"par",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  tickle: {kind:"M",target:"normal",priority:0,type:"Normal",flags:{protect:true,reflectable:true},boosts:{atk:-1,def:-1},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  tidyup: {kind:"L",target:"self",priority:0,type:"Normal",flags:{},games:{scarlet_violet:{},champions:{}}},
  topsyturvy: {kind:"L",target:"normal",priority:0,type:"Dark",flags:{protect:true,reflectable:true},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  torment: {kind:"N",target:"normal",priority:0,type:"Dark",flags:{protect:true,reflectable:true,bypasssub:true},volatile:"torment",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  toxic: {kind:"M",target:"normal",priority:0,type:"Poison",flags:{protect:true,reflectable:true},status:"tox",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  toxicspikes: {kind:"N",target:"foeSide",priority:0,type:"Poison",flags:{reflectable:true},side:"toxicspikes",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  toxicthread: {kind:"M",target:"normal",priority:0,type:"Poison",flags:{protect:true,reflectable:true},boosts:{spe:-1},status:"psn",games:{scarlet_violet:{},champions:{boosts:{spe:-2}},ultra_sun_ultra_moon:{}}},
  transform: {kind:"L",target:"normal",priority:0,type:"Normal",flags:{},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  trick: {kind:"M",target:"normal",priority:0,type:"Psychic",flags:{protect:true},handler:"swapItems",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  trickortreat: {kind:"L",target:"normal",priority:0,type:"Ghost",flags:{protect:true,reflectable:true},games:{champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  trickroom: {kind:"X",target:"all",priority:-7,type:"Psychic",flags:{},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  venomdrench: {kind:"M",target:"allAdjacentFoes",priority:0,type:"Poison",flags:{protect:true,reflectable:true},handler:"venomDrench",games:{sword_shield:{},ultra_sun_ultra_moon:{}}},
  victorydance: {kind:"M",target:"self",priority:0,type:"Fighting",flags:{},boosts:{atk:1,def:1,spe:1},games:{scarlet_violet:{}}},
  watersport: {kind:"L",target:"all",priority:0,type:"Water",flags:{},games:{ultra_sun_ultra_moon:{}}},
  whirlwind: {kind:"S",target:"normal",priority:-6,type:"Normal",flags:{reflectable:true,bypasssub:true,wind:true},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  wideguard: {kind:"X",target:"allySide",priority:3,type:"Rock",flags:{},side:"wideguard",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  willowisp: {kind:"M",target:"normal",priority:0,type:"Fire",flags:{protect:true,reflectable:true},status:"brn",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  wish: {kind:"M",target:"self",priority:0,type:"Normal",flags:{heal:true},slot:"Wish",handler:"wish",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  withdraw: {kind:"M",target:"self",priority:0,type:"Water",flags:{},boosts:{def:1},games:{scarlet_violet:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  wonderroom: {kind:"L",target:"all",priority:0,type:"Psychic",flags:{},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  workup: {kind:"M",target:"self",priority:0,type:"Normal",flags:{},boosts:{atk:1,spa:1},games:{scarlet_violet:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  worryseed: {kind:"L",target:"normal",priority:0,type:"Grass",flags:{protect:true,reflectable:true},games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
  yawn: {kind:"M",target:"normal",priority:0,type:"Normal",flags:{protect:true,reflectable:true},volatile:"yawn",handler:"yawn",fails:"yawn",games:{scarlet_violet:{},champions:{},sword_shield:{},ultra_sun_ultra_moon:{}}},
} as Record<string, StatusEntry>;

/** The move's entry as `game` sees it (its overrides applied), or undefined when the move is not a catalog Status move there. */
export function statusEntry(id: string, game: BattleGame): StatusEntry | undefined {
  const entry = STATUS_MOVE_TABLE[id];
  const own = entry?.games[game];
  if (!entry || !own) return undefined;
  const merged = { ...entry, ...own } as Record<string, unknown>;
  for (const [key, value] of Object.entries(own)) if (value === null) delete merged[key];
  return merged as StatusEntry;
}

/** Moves with flags.failencore (Encore fails when it is the last move), in any of the four games. */
export const FAILENCORE_MOVES: ReadonlySet<string> = new Set(["assist","copycat","dynamaxcannon","encore","mefirst","metronome","mimic","mirrormove","naturepower","sketch","sleeptalk","struggle","transform"]);
/** Moves with flags.defrost: a frozen user thaws as it uses one (data/conditions.ts frz onBeforeMove; Burn Up only for a Fire type). */
export const DEFROST_MOVES: ReadonlySet<string> = new Set(["burnup","flamewheel","flareblitz","fusionflare","hydrosteam","matchagotcha","pyroball","sacredfire","scald","scorchingsands","steameruption"]);
/** Champions: moves with flags.cantusetwice, which Disable does not stop there (data/mods/champions/moves.ts disable). */
export const CANTUSETWICE_MOVES: ReadonlySet<string> = new Set(["bloodmoon","gigatonhammer"]);
/** Moves with thawsTarget: a hit thaws a frozen target (data/conditions.ts frz onAfterMoveSecondary). */
export const THAWING_MOVES: ReadonlySet<string> = new Set(["hydrosteam","matchagotcha","scald","scorchingsands","steameruption"]);

/** Status moves with flags.heal in `game` (Triage: +3 priority, calculate.ts turnPriority). */
export function healFlag(id: string, game: BattleGame): boolean {
  return !!statusEntry(id, game)?.flags.heal;
}

