// Seeds public.pokemon, the Pool Builder v2 dataset (docs/release-architecture.md
// section 13.4), from data/pokemon/pokemon.json, the file that
// scripts/build-pokemon-data.mjs writes (npm run data:pokemon). The rows whose
// slug or display name moved to another id since the last run are parked
// first (see rowsToPark), then every row is upserted on id in batches of 500,
// then the rows whose id is not in the file are deleted, and the counts are
// printed. This script is the table's only writer; the client only reads it.
// Exits 1 on any error.
// Run with: npm run seed:pokemon   (needs .env.scripts, see .env.example)
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { chunk, createAdminClient, fetchAllRows } from "./lib/supabase-admin.mjs";

const DATA_FILE = resolve("data", "pokemon", "pokemon.json");
const TABLE = "pokemon";
const UPSERT_BATCH = 500;
const DELETE_BATCH = 500;

const FORM_KINDS = ["default", "mega", "regional", "gender", "other"] as const;
const STATS = ["hp", "attack", "defense", "special_attack", "special_defense", "speed"] as const;
const TAGS = ["legendary", "sub_legendary", "restricted", "mythical", "paradox", "ultra_beast"] as const;

type FormKind = (typeof FORM_KINDS)[number];
type Stat = (typeof STATS)[number];

// The writable columns of public.pokemon. `bst` is generated by the table and
// `updated_at` is set to this run's timestamp, so neither is taken from the
// file even when the build script writes them.
export type SeedRow = Record<Stat, number> & {
  id: number;
  species_id: number;
  slug: string;
  display_name: string;
  species_name: string;
  form_kind: FormKind;
  form_label: string | null;
  type1: string;
  type2: string | null;
  generation: number;
  tags: string[];
  games: string[];
  dex_numbers: Record<string, number>;
  sprite_url: string | null;
  updated_at: string;
};

// What the script reads back from the table before writing: enough to find
// the rows that are stale and the rows that would collide with the file.
export type ExistingRow = { id: number; slug: string; display_name: string };

const COLUMNS = new Set<string>([
  "id",
  "species_id",
  "slug",
  "display_name",
  "species_name",
  "form_kind",
  "form_label",
  "type1",
  "type2",
  ...STATS,
  "generation",
  "tags",
  "games",
  "dex_numbers",
  "sprite_url",
]);
const IGNORED_KEYS = new Set(["bst", "updated_at"]);

// Parked rows get this as their slug and display name (unique per id, and
// never a real value: PokéAPI slugs are lower-case words and hyphens, and the
// display names are prose). The file may not use the marker.
const PARK_MARKER = "~";

class RowError extends Error {
  constructor(file: string, index: number, label: string, message: string) {
    super(`${file} row ${index}${label ? ` (${label})` : ""}: ${message}`);
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isInteger(value: unknown): value is number {
  return typeof value === "number" && Number.isInteger(value);
}

function isText(value: unknown): value is string {
  return typeof value === "string" && value.trim().length > 0;
}

function isStringArray(value: unknown): value is string[] {
  return Array.isArray(value) && value.every((item) => typeof item === "string" && item.length > 0);
}

// Entry numbers start at 0 in some Pokédexes (Victini is #000 in Unova's).
function isDexNumbers(value: unknown): value is Record<string, number> {
  return isRecord(value) && Object.values(value).every((n) => isInteger(n) && n >= 0);
}

// Validates one row of the file against the table's constraints so a bad
// build fails here, with the row named, instead of half way through an
// upsert with PostgREST's message.
function toSeedRow(file: string, raw: unknown, index: number, updatedAt: string): SeedRow {
  if (!isRecord(raw)) {
    throw new RowError(file, index, "", "not an object");
  }
  const label = typeof raw.slug === "string" ? raw.slug : "";
  // The explicit annotation is what lets TypeScript treat a call as a
  // `never` exit and narrow the guarded fields below.
  const fail: (message: string) => never = (message) => {
    throw new RowError(file, index, label, message);
  };
  for (const key of Object.keys(raw)) {
    if (!COLUMNS.has(key) && !IGNORED_KEYS.has(key)) {
      fail(`unknown column "${key}" (public.pokemon has no such column; rebuild the data or extend the migration)`);
    }
  }
  if (!isInteger(raw.id) || raw.id < 1) fail("id must be a positive integer");
  if (!isInteger(raw.species_id) || raw.species_id < 1) fail("species_id must be a positive integer");
  if (!isText(raw.slug)) fail("slug must be a non-empty string");
  if (raw.slug.startsWith(PARK_MARKER)) fail(`slug must not start with "${PARK_MARKER}" (reserved for the seed's parked rows)`);
  if (!isText(raw.display_name)) fail("display_name must be a non-empty string");
  if (raw.display_name.startsWith(PARK_MARKER)) fail(`display_name must not start with "${PARK_MARKER}" (reserved for the seed's parked rows)`);
  if (!isText(raw.species_name)) fail("species_name must be a non-empty string");
  if (typeof raw.form_kind !== "string" || !(FORM_KINDS as readonly string[]).includes(raw.form_kind)) {
    fail(`form_kind must be one of ${FORM_KINDS.join(", ")}`);
  }
  if (raw.form_label !== null && raw.form_label !== undefined && !isText(raw.form_label)) fail("form_label must be a string or null");
  if (!isText(raw.type1)) fail("type1 must be a non-empty string");
  if (raw.type2 !== null && raw.type2 !== undefined && !isText(raw.type2)) fail("type2 must be a string or null");
  for (const stat of STATS) {
    const value = raw[stat];
    if (!isInteger(value) || value < 1 || value > 32767) fail(`${stat} must be an integer between 1 and 32767`);
  }
  if (!isInteger(raw.generation) || raw.generation < 1 || raw.generation > 9) fail("generation must be an integer between 1 and 9");
  if (!isStringArray(raw.tags)) fail("tags must be an array of strings");
  for (const tag of raw.tags) {
    if (!(TAGS as readonly string[]).includes(tag)) fail(`unknown tag "${tag}" (expected one of ${TAGS.join(", ")})`);
  }
  if (!isStringArray(raw.games)) fail("games must be an array of strings");
  if (!isDexNumbers(raw.dex_numbers)) fail("dex_numbers must be an object of non-negative integers");
  if (raw.sprite_url !== null && raw.sprite_url !== undefined && !isText(raw.sprite_url)) fail("sprite_url must be a string or null");

  const stats = Object.fromEntries(STATS.map((stat) => [stat, raw[stat] as number])) as Record<Stat, number>;
  return {
    ...stats,
    id: raw.id as number,
    species_id: raw.species_id as number,
    slug: raw.slug as string,
    display_name: raw.display_name as string,
    species_name: raw.species_name as string,
    form_kind: raw.form_kind as FormKind,
    form_label: (raw.form_label as string | undefined) ?? null,
    type1: raw.type1 as string,
    type2: (raw.type2 as string | undefined) ?? null,
    generation: raw.generation as number,
    tags: raw.tags as string[],
    games: raw.games as string[],
    dex_numbers: raw.dex_numbers as Record<string, number>,
    sprite_url: (raw.sprite_url as string | undefined) ?? null,
    updated_at: updatedAt,
  };
}

// A duplicate id would make the upsert non-deterministic and a duplicate slug
// or display name would fail the table's unique constraints half way through.
function assertUnique(file: string, rows: SeedRow[], key: "id" | "slug" | "display_name"): void {
  const seen = new Map<string | number, number>();
  rows.forEach((row, index) => {
    const value = row[key];
    const first = seen.get(value);
    if (first !== undefined) {
      throw new Error(`${file}: duplicate ${key} ${JSON.stringify(value)} at rows ${first} and ${index}`);
    }
    seen.set(value, index);
  });
}

export function readSeedRows(file = DATA_FILE, updatedAt = new Date().toISOString()): SeedRow[] {
  if (!existsSync(file)) {
    throw new Error(`${file} does not exist. Run npm run data:pokemon first (scripts/build-pokemon-data.mjs).`);
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(readFileSync(file, "utf8"));
  } catch (error) {
    throw new Error(`${file} is not valid JSON: ${error instanceof Error ? error.message : String(error)}`);
  }
  if (!Array.isArray(parsed) || parsed.length === 0) {
    throw new Error(`${file} must be a non-empty array of dataset rows.`);
  }
  const rows = parsed.map((raw, index) => toSeedRow(file, raw, index, updatedAt));
  assertUnique(file, rows, "id");
  assertUnique(file, rows, "slug");
  assertUnique(file, rows, "display_name");
  return rows;
}

// The slug and display name a parked row carries until the upsert overwrites
// it (or the stale delete removes it).
export function parkedValue(id: number): string {
  return `${PARK_MARKER}${id}`;
}

// The ids of the rows in the table whose slug or display name the file gives
// to a different id: a display-name fix in overrides.json that moves a name
// between two rows, a swap, a row that gained a real PokéAPI id, or a stale
// row whose name a new row takes over. slug and display_name are unique and
// checked row by row, so upserting the file over such a row fails with 23505
// whichever order the batches run in. Parking those rows (slug and display
// name set to parkedValue) before the upsert frees the values; the upsert
// then overwrites the parked rows that are in the file and the stale delete
// removes the rest. Sorted by id.
export function rowsToPark(existing: readonly ExistingRow[], rows: ReadonlyArray<Pick<SeedRow, "id" | "slug" | "display_name">>): number[] {
  const idBySlug = new Map(rows.map((row) => [row.slug, row.id]));
  const idByName = new Map(rows.map((row) => [row.display_name, row.id]));
  const claimedByAnother = (owner: number | undefined, id: number) => owner !== undefined && owner !== id;
  return existing
    .filter((row) => claimedByAnother(idBySlug.get(row.slug), row.id) || claimedByAnother(idByName.get(row.display_name), row.id))
    .map((row) => row.id)
    .sort((a, b) => a - b);
}

async function main(): Promise<void> {
  const rows = readSeedRows();
  console.log(`Read ${rows.length} rows from ${DATA_FILE}.`);

  // Loads .env.scripts and exits 1 with the "Missing SUPABASE_URL and
  // SUPABASE_SERVICE_ROLE_KEY" message when either is absent, like the other
  // seed scripts; the service-role key never lives in .env.local.
  const supabase = createAdminClient();

  const existing = await fetchAllRows<ExistingRow>((from, to) =>
    supabase.from(TABLE).select("id, slug, display_name").order("id", { ascending: true }).range(from, to),
  );
  const keep = new Set(rows.map((row) => row.id));
  const stale = existing.map((row) => row.id).filter((id) => !keep.has(id));

  // A run that stops between here and the end of the upsert leaves the parked
  // rows with their marker names; the next run overwrites or deletes them.
  const park = rowsToPark(existing, rows);
  if (park.length > 0) {
    console.log(`Parking ${park.length} row(s) whose slug or display name moved to another id...`);
    for (const id of park) {
      const { error } = await supabase.from(TABLE).update({ slug: parkedValue(id), display_name: parkedValue(id) }).eq("id", id);
      if (error) {
        throw new Error(`${TABLE} could not park row ${id}: ${error.message}`);
      }
    }
  }

  console.log(`Upserting ${rows.length} rows into ${TABLE} in batches of ${UPSERT_BATCH}...`);
  let upserted = 0;
  for (const batch of chunk(rows, UPSERT_BATCH)) {
    const { error } = await supabase.from(TABLE).upsert(batch, { onConflict: "id" });
    if (error) {
      throw new Error(`${TABLE} upsert failed after ${upserted} rows: ${error.message}`);
    }
    upserted += batch.length;
    console.log(`  ${upserted}/${rows.length}`);
  }

  for (const batch of chunk(stale, DELETE_BATCH)) {
    const { error } = await supabase.from(TABLE).delete().in("id", batch);
    if (error) {
      throw new Error(`${TABLE} delete of stale rows failed: ${error.message}`);
    }
  }

  const { count, error: countError } = await supabase.from(TABLE).select("id", { count: "exact", head: true });
  if (countError) {
    throw new Error(`${TABLE} count failed: ${countError.message}`);
  }
  console.log(
    `Seeded ${TABLE}: ${park.length} rows parked, ${upserted} rows upserted, ${stale.length} stale rows deleted, ${count ?? "?"} rows in the table.`,
  );
  if (count !== rows.length) {
    throw new Error(`${TABLE} holds ${count ?? "an unknown number of"} rows after seeding but the file has ${rows.length}.`);
  }
}

// Runs only as a script (npm run seed:pokemon); the tests import the helpers.
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  });
}
