import { describe, expect, it } from "vitest";
import { calculateDoublesMoves, calculateDoublesOutcomes, calculateDoublesTurn } from "@/app/lib/battle/doubles-turn";
import type { DoublesPokemonInput, DoublesSlotId, DoublesTurnInput } from "@/app/lib/battle/doubles-types";
import { loadBattleRuntime } from "@/app/lib/battle/load-runtime";
import { createBuild, createConditions, createSide, defaultAbilityActive } from "@/app/lib/battle/model";
import type { BattleRuntime } from "@/app/lib/battle/runtime";
import type { BattleBuild, BattleConditions, BattleGame, MoveContext } from "@/app/lib/battle/types";

/**
 * Neutralizing Gas in the 2v2 turn (ngas-pp N1): from the turn's start it suppresses every other ability it can (pinned Showdown
 * c23d2e94 data/abilities.ts neutralizinggas, sim/pokemon.ts:858-877 ignoringAbility: cantsuppress abilities, another holder's
 * gas and an Ability Shield outside Magic Room keep theirs), and the events that would end it or change what it suppresses are
 * not estimated. Cases NG01-NG32 of scripts/.cache/calc-audit/ngas-pp/fix/cases-ng.ts and VF22.
 * The whole turn against pinned Showdown c23d2e94 (SPEC §8.2). Each case's values are the exact oracle of
 * scripts/.cache/calc-audit/2v2/verify/sim-dfs.ts: one real doubles turn per case with every damage roll, speed tie, Quick Claw,
 * Quick Draw, full paralysis, random target and hit count enumerated with its weight, every move hitting, no critical hit unless
 * certain or the field's, added effects below 100% failing, and HP read before the end of the turn. low and high are the most
 * likely HP when every roll is the lowest (ties to the higher HP) or the highest (ties to the lower HP), every other branch kept.
 * Damage min and max are the action's getDamage values into that slot (all its hits), uncapped. Level 50, 31 IVs, Serious nature
 * and 0 EVs / Stat Points unless set; Champions sets give Stat Points. Generated by ngas-pp/fix/gen-ngas-test.ts from verify/results.
 */
type Stat = "hp" | "atk" | "def" | "spa" | "spd" | "spe";
type Mon = {
  species: string; appSpecies?: string; ability: string; item?: string; nature?: string; evs?: Partial<Record<Stat, number>>;
  ivs?: Partial<Record<Stat, number>>; level?: number; hp?: number; status?: BattleBuild["status"];
  boosts?: Partial<Record<Exclude<Stat, "hp">, number>>; teraType?: string; choice?: "mega" | "terastallize" | "dynamax" | "zmove";
  charged?: boolean; appBuild?: Record<string, unknown>; absent?: boolean; gender?: string;
  move: string | null; target?: DoublesSlotId; context?: MoveContext;
};
type Side = { tailwind?: boolean; reflect?: boolean; lightScreen?: boolean; auroraVeil?: boolean };
type Field = Partial<Pick<BattleConditions, "weather" | "terrain" | "trickRoom" | "gravity" | "wonderRoom" | "magicRoom" | "critical">> & { own?: Side; opponent?: Side };
type HP = { start: number; maximum: number; low: number; high: number; min: number; max: number; average: number; koChance: number; faintsBeforeMoving?: number };
type Hit = { slot: DoublesSlotId; reached: number; koChance: number; min?: number; max?: number; kind?: "blocked" | "no-damage" | "calculated" };
type Step = { moveId: string; moves: number; order: [number, number][]; hits: Hit[] };
type Case = {
  id: string; game: "sv" | "swsh" | "usum" | "champions"; title: string; checks: string; field?: Field; exact: boolean;
  slots: Record<DoublesSlotId, Mon>; hp: Record<DoublesSlotId, HP | null>; steps: Partial<Record<DoublesSlotId, Step>>;
};

const GAMES: Record<Case["game"], BattleGame> = { sv: "scarlet_violet", swsh: "sword_shield", usum: "ultra_sun_ultra_moon", champions: "champions" };
const SLOTS: DoublesSlotId[] = ["own-left", "own-right", "opponent-left", "opponent-right"];
const id = (text: string) => text.toLowerCase().replace(/[^a-z0-9]+/g, "");
const ZERO = { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 };

/** The app build for an oracle set: Showdown names as ids, EVs (native) or Stat Points (Champions), the start state. */
function build(m: Mon, runtime: BattleRuntime): BattleBuild {
  const base = createBuild(m.appSpecies ?? id(m.species), runtime);
  const abilityId = id(m.ability);
  const shared = {
    nature: m.nature ?? "Serious", abilityId, abilityActive: defaultAbilityActive(abilityId), itemId: id(m.item ?? ""),
    boosts: { atk: 0, def: 0, spa: 0, spd: 0, spe: 0, ...m.boosts }, currentHP: m.hp ?? null, status: m.status ?? "",
  };
  const configuration = { ...base.configuration, ...(m.teraType ? { teraType: m.teraType } : {}) };
  const mechanic = m.choice === "terastallize" ? { mechanic: "tera" as const } : m.choice === "dynamax" ? { mechanic: "dynamax" as const } : {};
  const trained = base.game === "champions"
    ? { ...base, ...shared, points: { ...ZERO, ...m.evs } }
    : { ...base, ...shared, native: { level: m.level ?? 50, evs: { ...ZERO, ...m.evs }, ivs: { hp: 31, atk: 31, def: 31, spa: 31, spd: 31, spe: 31, ...m.ivs } } };
  return { ...trained, ...(Object.keys(configuration).length ? { configuration } : {}), ...mechanic, ...m.appBuild } as BattleBuild;
}
function side(s: Side | undefined) {
  return { ...createSide(), tailwind: !!s?.tailwind, reflect: !!s?.reflect, lightScreen: !!s?.lightScreen, auroraVeil: !!s?.auroraVeil };
}
async function input(c: Case): Promise<DoublesTurnInput> {
  const runtime = await loadBattleRuntime(GAMES[c.game]);
  const f = c.field ?? {};
  const field: BattleConditions = {
    ...createConditions(), gameType: "Doubles", weather: f.weather ?? "", terrain: f.terrain ?? "", critical: !!f.critical,
    trickRoom: !!f.trickRoom, gravity: !!f.gravity, wonderRoom: !!f.wonderRoom, magicRoom: !!f.magicRoom,
    attackerSide: side(f.own), defenderSide: side(f.opponent),
  };
  const pokemon = Object.fromEntries(SLOTS.map((slot) => {
    const m = c.slots[slot];
    if (m.absent) return [slot, null];
    const moveId = m.move === null ? null : id(m.move);
    const context: MoveContext = { ...(m.choice === "zmove" ? { useZ: true } : {}), ...m.context };
    const entry: DoublesPokemonInput = {
      build: build(m, runtime), contexts: moveId && Object.keys(context).length ? { [moveId]: context } : {}, charged: !!m.charged,
      action: { moveId, target: m.target ?? null },
    };
    return [slot, entry];
  })) as Record<DoublesSlotId, DoublesPokemonInput | null>;
  return { runtime, field, pokemon };
}

/** The oracle's cases (ngas-pp/fix/cases-ng.ts, VF22) with their expected values (2v2/verify/results/<id>.json). */
const CASES: Case[] = [
  {id:"VF22",game:"sv",title:"Critical hit field on: Neutralizing Gas Weezing's Sludge Bomb into an intact Mimikyu: the face still acts, not critical (SV)",checks:"gas + crit",field:{critical:true},exact:true,slots:{"own-left":{species:"Weezing-Galar",ability:"Neutralizing Gas",move:"Sludge Bomb",target:"opponent-left"},"own-right":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-left":{species:"Mimikyu",ability:"Disguise",move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}},hp:{"own-left":{start:140,maximum:140,low:140,high:140,min:140,max:140,average:140,koChance:0},"own-right":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-left":{start:130,maximum:130,low:114,high:114,min:114,max:114,average:114,koChance:0},"opponent-right":{start:235,maximum:235,low:235,high:235,min:235,max:235,average:235,koChance:0}},steps:{"own-left":{moveId:"sludgebomb",moves:1,order:[[1,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,min:43,max:52}]}}},
  {id:"NG01",game:"sv",title:"Gas Weezing idle: Charizard's Flamethrower into a Thick Fat Snorlax (full damage), Snorlax's Body Slam into Weezing (SV)",checks:"Thick Fat suppressed",exact:true,slots:{"own-left":{species:"Weezing-Galar",ability:"Neutralizing Gas",move:null},"own-right":{species:"Charizard",ability:"Blaze",move:"Flamethrower",target:"opponent-right"},"opponent-left":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:"Body Slam",target:"own-left"}},hp:{"own-left":{start:140,maximum:140,low:95,high:86,min:86,max:95,average:91,koChance:0},"own-right":{start:153,maximum:153,low:153,high:153,min:153,max:153,average:153,koChance:0},"opponent-left":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-right":{start:235,maximum:235,low:184,high:174,min:174,max:184,average:179.0625,koChance:0}},steps:{"own-right":{moveId:"flamethrower",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:51,max:61}]},"opponent-right":{moveId:"bodyslam",moves:1,order:[[2,1]],hits:[{slot:"own-left",reached:1,koChance:0,min:45,max:54}]}}},
  {id:"NG02",game:"sv",title:"Gas on the foe's side: Garchomp's Dragon Claw into a full-HP Multiscale Dragonite is not halved (SV)",checks:"Multiscale suppressed",exact:true,slots:{"own-left":{species:"Garchomp",ability:"Rough Skin",move:"Dragon Claw",target:"opponent-right"},"own-right":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-left":{species:"Weezing-Galar",ability:"Neutralizing Gas",move:null},"opponent-right":{species:"Dragonite",ability:"Multiscale",move:null}},hp:{"own-left":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"own-right":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-left":{start:140,maximum:140,low:140,high:140,min:140,max:140,average:140,koChance:0},"opponent-right":{start:166,maximum:166,low:50,high:26,min:26,max:50,average:37.5,koChance:0}},steps:{"own-left":{moveId:"dragonclaw",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:116,max:140}]}}},
  {id:"NG03",game:"sv",title:"Ability Shield keeps Snorlax's Thick Fat under the gas: Flamethrower is halved (SV)",checks:"Ability Shield keeps it",exact:true,slots:{"own-left":{species:"Weezing-Galar",ability:"Neutralizing Gas",move:null},"own-right":{species:"Charizard",ability:"Blaze",move:"Flamethrower",target:"opponent-right"},"opponent-left":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},item:"Ability Shield",move:null}},hp:{"own-left":{start:140,maximum:140,low:140,high:140,min:140,max:140,average:140,koChance:0},"own-right":{start:153,maximum:153,low:153,high:153,min:153,max:153,average:153,koChance:0},"opponent-left":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-right":{start:235,maximum:235,low:210,high:204,min:204,max:210,average:206.8125,koChance:0}},steps:{"own-right":{moveId:"flamethrower",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:25,max:31}]}}},
  {id:"NG04",game:"sv",title:"Magic Room: Snorlax's Ability Shield does not work, so its Thick Fat is suppressed (SV)",checks:"Magic Room off the Shield",field:{magicRoom:true},exact:true,slots:{"own-left":{species:"Weezing-Galar",ability:"Neutralizing Gas",move:null},"own-right":{species:"Charizard",ability:"Blaze",move:"Flamethrower",target:"opponent-right"},"opponent-left":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},item:"Ability Shield",move:null}},hp:{"own-left":{start:140,maximum:140,low:140,high:140,min:140,max:140,average:140,koChance:0},"own-right":{start:153,maximum:153,low:153,high:153,min:153,max:153,average:153,koChance:0},"opponent-left":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-right":{start:235,maximum:235,low:184,high:174,min:174,max:184,average:179.0625,koChance:0}},steps:{"own-right":{moveId:"flamethrower",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:51,max:61}]}}},
  {id:"NG05",game:"sv",title:"Earthquake hits a Levitate Hydreigon under the gas, and the gas holder across (SV)",checks:"Levitate suppressed; spread",exact:true,slots:{"own-left":{species:"Garchomp",ability:"Rough Skin",move:"Earthquake"},"own-right":{species:"Talonflame",ability:"Flame Body",move:null},"opponent-left":{species:"Weezing-Galar",ability:"Neutralizing Gas",move:null},"opponent-right":{species:"Hydreigon",ability:"Levitate",move:null}},hp:{"own-left":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"own-right":{start:153,maximum:153,low:153,high:153,min:153,max:153,average:153,koChance:0},"opponent-left":{start:140,maximum:140,low:48,high:30,min:30,max:48,average:39.25,koChance:0},"opponent-right":{start:167,maximum:167,low:109,high:98,min:98,max:109,average:104.0625,koChance:0}},steps:{"own-left":{moveId:"earthquake",moves:1,order:[[1,1]],hits:[{slot:"own-right",reached:1,koChance:0,kind:"no-damage"},{slot:"opponent-right",reached:1,koChance:0,min:58,max:69},{slot:"opponent-left",reached:1,koChance:0,min:92,max:110}]}}},
  {id:"NG06",game:"sv",title:"Unnerve suppressed: Tyranitar's Body Slam takes Snorlax under half and it eats its Sitrus Berry before Charizard's hit (SV)",checks:"Unnerve suppressed, Sitrus eaten",exact:true,slots:{"own-left":{species:"Tyranitar",ability:"Unnerve",move:"Body Slam",target:"opponent-right"},"own-right":{species:"Charizard",ability:"Blaze",move:"Flamethrower",target:"opponent-right"},"opponent-left":{species:"Weezing-Galar",ability:"Neutralizing Gas",move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},item:"Sitrus Berry",hp:200,move:null}},hp:{"own-left":{start:175,maximum:175,low:175,high:175,min:175,max:175,average:175,koChance:0},"own-right":{start:153,maximum:153,low:153,high:153,min:153,max:153,average:153,koChance:0},"opponent-left":{start:140,maximum:140,low:140,high:140,min:140,max:140,average:140,koChance:0},"opponent-right":{start:200,maximum:235,low:149,high:128,min:128,max:149,average:138.6875,koChance:0}},steps:{"own-left":{moveId:"bodyslam",moves:1,order:[[2,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:58,max:69}]},"own-right":{moveId:"flamethrower",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:51,max:61}]}}},
  {id:"NG07",game:"sv",title:"Friend Guard suppressed: Charizard's Flamethrower into Venusaur next to a Friend Guard Clefairy (SV)",checks:"partner Friend Guard suppressed",exact:true,slots:{"own-left":{species:"Weezing-Galar",ability:"Neutralizing Gas",move:null},"own-right":{species:"Charizard",ability:"Blaze",move:"Flamethrower",target:"opponent-left"},"opponent-left":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-right":{species:"Clefairy",ability:"Friend Guard",move:null}},hp:{"own-left":{start:140,maximum:140,low:140,high:140,min:140,max:140,average:140,koChance:0},"own-right":{start:153,maximum:153,low:153,high:153,min:153,max:153,average:153,koChance:0},"opponent-left":{start:155,maximum:155,low:45,high:23,min:23,max:45,average:34.75,koChance:0},"opponent-right":{start:145,maximum:145,low:145,high:145,min:145,max:145,average:145,koChance:0}},steps:{"own-right":{moveId:"flamethrower",moves:1,order:[[1,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,min:110,max:132}]}}},
  {id:"NG08",game:"sv",title:"Friend Guard kept by an Ability Shield: the gas holder's own Sludge Bomb into Venusaur is cut to 75% (SV)",checks:"shielded partner ability vs the holder",exact:true,slots:{"own-left":{species:"Weezing-Galar",ability:"Neutralizing Gas",move:"Sludge Bomb",target:"opponent-left"},"own-right":{species:"Charizard",ability:"Blaze",move:null},"opponent-left":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-right":{species:"Clefairy",ability:"Friend Guard",item:"Ability Shield",move:null}},hp:{"own-left":{start:140,maximum:140,low:140,high:140,min:140,max:140,average:140,koChance:0},"own-right":{start:153,maximum:153,low:153,high:153,min:153,max:153,average:153,koChance:0},"opponent-left":{start:155,maximum:155,low:121,high:115,min:115,max:121,average:118.3125,koChance:0},"opponent-right":{start:145,maximum:145,low:145,high:145,min:145,max:145,average:145,koChance:0}},steps:{"own-left":{moveId:"sludgebomb",moves:1,order:[[1,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,min:34,max:40}]}}},
  {id:"NG09",game:"sv",title:"Gale Wings suppressed: Talonflame's Brave Bird at full HP has no priority, Garchomp moves first (SV)",checks:"priority from an ability suppressed; Jolly Garchomp (169) before Talonflame (146)",exact:true,slots:{"own-left":{species:"Talonflame",ability:"Gale Wings",move:"Brave Bird",target:"opponent-right"},"own-right":{species:"Weezing-Galar",ability:"Neutralizing Gas",move:null},"opponent-left":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{spe:252},move:"Dragon Claw",target:"own-right"},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}},hp:{"own-left":{start:153,maximum:153,low:126,high:121,min:121,max:126,average:123.8125,koChance:0},"own-right":{start:140,maximum:140,low:140,high:140,min:140,max:140,average:140,koChance:0},"opponent-left":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"opponent-right":{start:235,maximum:235,low:154,high:139,min:139,max:154,average:147.0625,koChance:0}},steps:{"own-left":{moveId:"bravebird",moves:1,order:[[2,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:81,max:96}]},"opponent-left":{moveId:"dragonclaw",moves:1,order:[[1,1]],hits:[{slot:"own-right",reached:1,koChance:0,kind:"no-damage"}]}}},
  {id:"NG10",game:"sv",title:"Two gas holders: Garchomp's Dragon Claw into Dragonite (Multiscale suppressed), Weezing's Sludge Bomb into Weezing-Galar (SV)",checks:"two holders",exact:true,slots:{"own-left":{species:"Weezing",ability:"Neutralizing Gas",move:"Sludge Bomb",target:"opponent-left"},"own-right":{species:"Garchomp",ability:"Rough Skin",move:"Dragon Claw",target:"opponent-right"},"opponent-left":{species:"Weezing-Galar",ability:"Neutralizing Gas",move:null},"opponent-right":{species:"Dragonite",ability:"Multiscale",move:null}},hp:{"own-left":{start:140,maximum:140,low:140,high:140,min:140,max:140,average:140,koChance:0},"own-right":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"opponent-left":{start:140,maximum:140,low:80,high:68,min:68,max:80,average:74.25,koChance:0},"opponent-right":{start:166,maximum:166,low:50,high:26,min:26,max:50,average:37.5,koChance:0}},steps:{"own-left":{moveId:"sludgebomb",moves:1,order:[[2,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,min:60,max:72}]},"own-right":{moveId:"dragonclaw",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:116,max:140}]}}},
  {id:"NG11",game:"sv",title:"Gas-proof Disguise: Sludge Bomb into an intact Mimikyu still breaks the disguise (SV)",checks:"cantsuppress",exact:true,slots:{"own-left":{species:"Weezing-Galar",ability:"Neutralizing Gas",move:"Sludge Bomb",target:"opponent-left"},"own-right":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-left":{species:"Mimikyu",ability:"Disguise",move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}},hp:{"own-left":{start:140,maximum:140,low:140,high:140,min:140,max:140,average:140,koChance:0},"own-right":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-left":{start:130,maximum:130,low:114,high:114,min:114,max:114,average:114,koChance:0},"opponent-right":{start:235,maximum:235,low:235,high:235,min:235,max:235,average:235,koChance:0}},steps:{"own-left":{moveId:"sludgebomb",moves:1,order:[[1,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,min:43,max:52}]}}},
  {id:"NG12",game:"swsh",title:"Mimicry suppressed on Electric Terrain: Raichu's Thunderbolt into Ground/Steel Stunfisk has no effect (SwSh)",checks:"Mimicry types",field:{terrain:"Electric"},exact:true,slots:{"own-left":{species:"Raichu",ability:"Static",move:"Thunderbolt",target:"opponent-left"},"own-right":{species:"Weezing",ability:"Neutralizing Gas",move:null},"opponent-left":{species:"Stunfisk-Galar",ability:"Mimicry",move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}},hp:{"own-left":{start:135,maximum:135,low:135,high:135,min:135,max:135,average:135,koChance:0},"own-right":{start:140,maximum:140,low:140,high:140,min:140,max:140,average:140,koChance:0},"opponent-left":{start:184,maximum:184,low:184,high:184,min:184,max:184,average:184,koChance:0},"opponent-right":{start:235,maximum:235,low:235,high:235,min:235,max:235,average:235,koChance:0}},steps:{"own-left":{moveId:"thunderbolt",moves:1,order:[[1,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,kind:"no-damage"}]}}},
  {id:"NG13",game:"swsh",title:"Dynamax under the gas: Max Flare into a Thick Fat Snorlax (SwSh)",checks:"Max Move with gas",exact:true,slots:{"own-left":{species:"Charizard",ability:"Blaze",choice:"dynamax",move:"Flamethrower",target:"opponent-right"},"own-right":{species:"Weezing",ability:"Neutralizing Gas",move:null},"opponent-left":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}},hp:{"own-left":{start:306,maximum:306,low:306,high:306,min:306,max:306,average:306,koChance:0},"own-right":{start:140,maximum:140,low:140,high:140,min:140,max:140,average:140,koChance:0},"opponent-left":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-right":{start:235,maximum:235,low:162,high:148,min:148,max:162,average:155.5,koChance:0}},steps:{"own-left":{moveId:"flamethrower",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:73,max:87}]}}},
  {id:"NG14",game:"sv",title:"Terastallized Ogerpon-Wellspring: Embody Aspect is suppressed (no +1 Sp. Def) for Charizard's Flamethrower (SV)",checks:"Tera form ability suppressed",exact:true,slots:{"own-left":{species:"Weezing-Galar",ability:"Neutralizing Gas",move:null},"own-right":{species:"Charizard",ability:"Blaze",move:"Flamethrower",target:"opponent-left"},"opponent-left":{species:"Ogerpon-Wellspring",ability:"Water Absorb",item:"Wellspring Mask",teraType:"Water",choice:"terastallize",move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}},hp:{"own-left":{start:140,maximum:140,low:140,high:140,min:140,max:140,average:140,koChance:0},"own-right":{start:153,maximum:153,low:153,high:153,min:153,max:153,average:153,koChance:0},"opponent-left":{start:155,maximum:155,low:126,high:121,min:121,max:126,average:123.75,koChance:0},"opponent-right":{start:235,maximum:235,low:235,high:235,min:235,max:235,average:235,koChance:0}},steps:{"own-right":{moveId:"flamethrower",moves:1,order:[[1,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,min:29,max:34}]}}},
  {id:"NG15",game:"sv",title:"Terapagos-Terastal at full HP: Tera Shell is suppressed, Garchomp's Dragon Claw is neutral (SV)",checks:"Tera Shift form, Tera Shell suppressed",exact:true,slots:{"own-left":{species:"Weezing-Galar",ability:"Neutralizing Gas",move:null},"own-right":{species:"Garchomp",ability:"Rough Skin",move:"Dragon Claw",target:"opponent-left"},"opponent-left":{species:"Terapagos",ability:"Tera Shift",move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}},hp:{"own-left":{start:140,maximum:140,low:140,high:140,min:140,max:140,average:140,koChance:0},"own-right":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"opponent-left":{start:170,maximum:170,low:118,high:107,min:107,max:118,average:112.6875,koChance:0},"opponent-right":{start:235,maximum:235,low:235,high:235,min:235,max:235,average:235,koChance:0}},steps:{"own-right":{moveId:"dragonclaw",moves:1,order:[[1,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,min:52,max:63}]}}},
  {id:"NG16",game:"sv",title:"The gas holder survives two hits: Garchomp and Charizard into Weezing-Galar (SV)",checks:"holder hit, gas stays",exact:true,slots:{"own-left":{species:"Garchomp",ability:"Rough Skin",move:"Dragon Claw",target:"opponent-left"},"own-right":{species:"Charizard",ability:"Blaze",move:"Air Slash",target:"opponent-left"},"opponent-left":{species:"Weezing-Galar",ability:"Neutralizing Gas",move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}},hp:{"own-left":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"own-right":{start:153,maximum:153,low:153,high:153,min:153,max:153,average:153,koChance:0},"opponent-left":{start:140,maximum:140,low:79,high:67,min:67,max:79,average:72.75,koChance:0},"opponent-right":{start:235,maximum:235,low:235,high:235,min:235,max:235,average:235,koChance:0}},steps:{"own-left":{moveId:"dragonclaw",moves:1,order:[[1,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,kind:"no-damage"}]},"own-right":{moveId:"airslash",moves:1,order:[[2,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,min:61,max:73}]}}},
  {id:"NG23",game:"sv",title:"Cloud Nine suppressed: Blastoise's Hydro Pump into Snorlax is boosted by the rain (SV)",checks:"weather negator suppressed",field:{weather:"Rain"},exact:true,slots:{"own-left":{species:"Weezing-Galar",ability:"Neutralizing Gas",move:null},"own-right":{species:"Blastoise",ability:"Torrent",move:"Hydro Pump",target:"opponent-right"},"opponent-left":{species:"Golduck",ability:"Cloud Nine",move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}},hp:{"own-left":{start:140,maximum:140,low:140,high:140,min:140,max:140,average:140,koChance:0},"own-right":{start:154,maximum:154,low:154,high:154,min:154,max:154,average:154,koChance:0},"opponent-left":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-right":{start:235,maximum:235,low:159,high:144,min:144,max:159,average:151.375,koChance:0}},steps:{"own-right":{moveId:"hydropump",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:76,max:91}]}}},
  {id:"NG24",game:"sv",title:"Lightning Rod suppressed: Magnezone's Thunderbolt hits Snorlax, not its partner Raichu (SV)",checks:"redirection suppressed",exact:true,slots:{"own-left":{species:"Magnezone",ability:"Magnet Pull",move:"Thunderbolt",target:"opponent-right"},"own-right":{species:"Weezing-Galar",ability:"Neutralizing Gas",move:null},"opponent-left":{species:"Raichu",ability:"Lightning Rod",move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}},hp:{"own-left":{start:145,maximum:145,low:145,high:145,min:145,max:145,average:145,koChance:0},"own-right":{start:140,maximum:140,low:140,high:140,min:140,max:140,average:140,koChance:0},"opponent-left":{start:135,maximum:135,low:135,high:135,min:135,max:135,average:135,koChance:0},"opponent-right":{start:235,maximum:235,low:177,high:165,min:165,max:177,average:170.75,koChance:0}},steps:{"own-left":{moveId:"thunderbolt",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:58,max:70}]}}},
  {id:"NG28",game:"sv",title:"Water Absorb suppressed: Blastoise's Hydro Pump damages Politoed (SV)",checks:"absorbing ability suppressed",exact:true,slots:{"own-left":{species:"Weezing-Galar",ability:"Neutralizing Gas",move:null},"own-right":{species:"Blastoise",ability:"Torrent",move:"Hydro Pump",target:"opponent-left"},"opponent-left":{species:"Politoed",ability:"Water Absorb",move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}},hp:{"own-left":{start:140,maximum:140,low:140,high:140,min:140,max:140,average:140,koChance:0},"own-right":{start:154,maximum:154,low:154,high:154,min:154,max:154,average:154,koChance:0},"opponent-left":{start:165,maximum:165,low:138,high:132,min:132,max:138,average:135.1875,koChance:0},"opponent-right":{start:235,maximum:235,low:235,high:235,min:235,max:235,average:235,koChance:0}},steps:{"own-right":{moveId:"hydropump",moves:1,order:[[1,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,min:27,max:33}]}}},
  {id:"NG25",game:"sv",title:"Quark Drive with Booster Energy suppressed: Iron Hands's Thunder Punch into Snorlax (SV)",checks:"paradox boost suppressed, Booster Energy kept",exact:true,slots:{"own-left":{species:"Iron Hands",ability:"Quark Drive",item:"Booster Energy",move:"Thunder Punch",target:"opponent-right"},"own-right":{species:"Weezing-Galar",ability:"Neutralizing Gas",move:null},"opponent-left":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}},hp:{"own-left":{start:229,maximum:229,low:229,high:229,min:229,max:229,average:229,koChance:0},"own-right":{start:140,maximum:140,low:140,high:140,min:140,max:140,average:140,koChance:0},"opponent-left":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-right":{start:235,maximum:235,low:154,high:139,min:139,max:154,average:147.0625,koChance:0}},steps:{"own-left":{moveId:"thunderpunch",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:81,max:96}]}}},
  {id:"NG26",game:"sv",title:"Imposter suppressed: Ditto stays Ditto and takes Charizard's Flamethrower (SV)",checks:"no transformation",exact:true,slots:{"own-left":{species:"Weezing-Galar",ability:"Neutralizing Gas",move:null},"own-right":{species:"Charizard",ability:"Blaze",move:"Flamethrower",target:"opponent-left"},"opponent-left":{species:"Ditto",ability:"Imposter",move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}},hp:{"own-left":{start:140,maximum:140,low:140,high:140,min:140,max:140,average:140,koChance:0},"own-right":{start:153,maximum:153,low:153,high:153,min:153,max:153,average:153,koChance:0},"opponent-left":{start:123,maximum:123,low:26,high:8,min:8,max:26,average:17.125,koChance:0},"opponent-right":{start:235,maximum:235,low:235,high:235,min:235,max:235,average:235,koChance:0}},steps:{"own-right":{moveId:"flamethrower",moves:1,order:[[1,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,min:97,max:115}]}}},
  {id:"NG27",game:"sv",title:"Sturdy suppressed: Charizard's Specs Overheat knocks out a full-HP Magnezone (SV)",checks:"OHKO through Sturdy",exact:true,slots:{"own-left":{species:"Weezing-Galar",ability:"Neutralizing Gas",move:null},"own-right":{species:"Charizard",ability:"Blaze",item:"Choice Specs",nature:"Modest",evs:{spa:252},move:"Overheat",target:"opponent-left"},"opponent-left":{species:"Magnezone",ability:"Sturdy",move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}},hp:{"own-left":{start:140,maximum:140,low:140,high:140,min:140,max:140,average:140,koChance:0},"own-right":{start:153,maximum:153,low:153,high:153,min:153,max:153,average:153,koChance:0},"opponent-left":{start:145,maximum:145,low:0,high:0,min:0,max:0,average:0,koChance:1},"opponent-right":{start:235,maximum:235,low:235,high:235,min:235,max:235,average:235,koChance:0}},steps:{"own-right":{moveId:"overheat",moves:1,order:[[1,1]],hits:[{slot:"opponent-left",reached:1,koChance:1,min:354,max:416}]}}},
  {id:"NG29",game:"sv",title:"Gluttony suppressed: Snorlax at 117 HP (half) keeps its Figy Berry; Flamethrower takes it to a quarter on some rolls (SV)",checks:"berry line at a quarter, not half",exact:true,slots:{"own-left":{species:"Weezing-Galar",ability:"Neutralizing Gas",move:null},"own-right":{species:"Charizard",ability:"Blaze",move:"Flamethrower",target:"opponent-right"},"opponent-left":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-right":{species:"Snorlax",ability:"Gluttony",evs:{spe:4},item:"Figy Berry",hp:117,move:null}},hp:{"own-left":{start:140,maximum:140,low:140,high:140,min:140,max:140,average:140,koChance:0},"own-right":{start:153,maximum:153,low:153,high:153,min:153,max:153,average:153,koChance:0},"opponent-left":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-right":{start:117,maximum:235,low:66,high:134,min:59,max:135,average:75.6875,koChance:0}},steps:{"own-right":{moveId:"flamethrower",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:51,max:61}]}}},
  {id:"NG30",game:"swsh",title:"Serene Grace suppressed: Blissey's Rock Smash does not lower Snorlax's Defense before Conkeldurr's Hammer Arm (SwSh; the serene-grace unit test's turn)",checks:"doubled chance suppressed: the 50% drop does not happen",exact:true,slots:{"own-left":{species:"Blissey",ability:"Serene Grace",move:"Rock Smash",target:"opponent-left"},"own-right":{species:"Conkeldurr",ability:"Guts",move:"Hammer Arm",target:"opponent-left"},"opponent-left":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null},"opponent-right":{species:"Weezing-Galar",ability:"Neutralizing Gas",move:null}},hp:{"own-left":{start:330,maximum:330,low:330,high:330,min:330,max:330,average:330,koChance:0},"own-right":{start:180,maximum:180,low:180,high:180,min:180,max:180,average:180,koChance:0},"opponent-left":{start:235,maximum:235,low:11,high:0,min:0,max:11,average:1.32421875,koChance:0.73828125},"opponent-right":{start:140,maximum:140,low:140,high:140,min:140,max:140,average:140,koChance:0}},steps:{"own-left":{moveId:"rocksmash",moves:1,order:[[1,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,min:12,max:16}]},"own-right":{moveId:"hammerarm",moves:1,order:[[2,1]],hits:[{slot:"opponent-left",reached:1,koChance:0.73828125,min:212,max:252}]}}},
  {id:"NG31",game:"swsh",title:"Core Enforcer into the gas holder (Weezing, 80) before it moves: no suppression, the gas stays (SwSh)",checks:"willMove: no gastroacid",exact:true,slots:{"own-left":{species:"Zygarde",ability:"Aura Break",move:"Core Enforcer"},"own-right":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-left":{species:"Weezing",ability:"Neutralizing Gas",move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}},hp:{"own-left":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"own-right":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-left":{start:140,maximum:140,low:92,high:83,min:83,max:92,average:88.1875,koChance:0},"opponent-right":{start:235,maximum:235,low:202,high:195,min:195,max:202,average:198.5,koChance:0}},steps:{"own-left":{moveId:"coreenforcer",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:33,max:40},{slot:"opponent-left",reached:1,koChance:0,min:48,max:57}]}}},
];

/** The cases a gas event leaves not estimated (ngas-pp/fix/cases-ng.ts), with their reasons. */
const GUARDED: (Pick<Case, "id" | "game" | "title" | "field" | "slots"> & { reason: string })[] = [
  {id:"NG17",game:"sv",title:"The gas holder is knocked out by the first hit, with a later move (SV)",reason:"Neutralizing Gas ending is not modelled in 2v2.",slots:{"own-left":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Earthquake"},"own-right":{species:"Talonflame",ability:"Flame Body",move:null},"opponent-left":{species:"Weezing-Galar",ability:"Neutralizing Gas",hp:20,move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:"Body Slam",target:"own-left"}}},
  {id:"NG18",game:"sv",title:"The gas holder is knocked out by the last move of the turn (SV)",reason:"Neutralizing Gas ending is not modelled in 2v2.",slots:{"own-left":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:"Body Slam",target:"opponent-left"},"own-right":{species:"Charizard",ability:"Blaze",move:"Flamethrower",target:"opponent-right"},"opponent-left":{species:"Weezing-Galar",ability:"Neutralizing Gas",hp:10,move:null},"opponent-right":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null}}},
  {id:"NG19",game:"sv",title:"Eject Button on the gas holder hit by the last move (SV)",reason:"Neutralizing Gas ending is not modelled in 2v2.",slots:{"own-left":{species:"Charizard",ability:"Blaze",move:"Flamethrower",target:"opponent-left"},"own-right":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-left":{species:"Weezing-Galar",ability:"Neutralizing Gas",item:"Eject Button",move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}}},
  {id:"NG20",game:"sv",title:"Knock Off removes Snorlax's Ability Shield under the gas (SV)",reason:"An Ability Shield change under Neutralizing Gas is not modelled in 2v2.",slots:{"own-left":{species:"Weezing-Galar",ability:"Neutralizing Gas",move:null},"own-right":{species:"Tyranitar",ability:"Unnerve",move:"Knock Off",target:"opponent-right"},"opponent-left":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},item:"Ability Shield",move:"Body Slam",target:"own-left"}}},
  {id:"NG21",game:"sv",title:"Lingering Aroma kept by an Ability Shield under the gas (SV)",reason:"Lingering Aroma with Neutralizing Gas is not modelled in 2v2.",slots:{"own-left":{species:"Weezing-Galar",ability:"Neutralizing Gas",move:null},"own-right":{species:"Garchomp",ability:"Rough Skin",move:"Dragon Claw",target:"opponent-right"},"opponent-left":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-right":{species:"Oinkologne",ability:"Lingering Aroma",item:"Ability Shield",move:null}}},
  {id:"NG32",game:"swsh",title:"Core Enforcer into a Choice Scarf gas holder that has moved: its gas ends (SwSh)",reason:"Neutralizing Gas ending is not modelled in 2v2.",slots:{"own-left":{species:"Zygarde",ability:"Aura Break",move:"Core Enforcer"},"own-right":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-left":{species:"Weezing",ability:"Neutralizing Gas",item:"Choice Scarf",move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}}},
  {id:"NG22",game:"sv",title:"Explosion from the gas holder (SV)",reason:"Neutralizing Gas ending is not modelled in 2v2.",slots:{"own-left":{species:"Weezing-Galar",ability:"Neutralizing Gas",move:"Explosion"},"own-right":{species:"Charizard",ability:"Blaze",move:null},"opponent-left":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}}},
];

describe("the 2v2 turn under Neutralizing Gas against pinned Showdown", () => {
  for (const c of CASES) {
    it(`${c.id}: ${c.title}`, async () => {
      const result = calculateDoublesTurn(await input(c));
      expect(result.status, c.checks).toBe("ready");
      if (result.status !== "ready") return;
      // Exhaustive cases are exact to 1e-9; a sampled one (exact: false) to 0.015 in its chances and 0.5 HP in its average.
      const digits = c.exact ? 9 : 1;
      for (const slot of SLOTS) {
        const want = c.hp[slot], got = result.hp[slot];
        if (!want) { expect(got, slot).toBeNull(); continue; }
        expect(got, slot).not.toBeNull();
        expect({ start: got!.start, maximum: got!.maximum, low: got!.low, high: got!.high }, `${c.id} ${slot}`).toEqual({ start: want.start, maximum: want.maximum, low: want.low, high: want.high });
        if (c.exact) expect({ min: got!.min, max: got!.max }, `${c.id} ${slot}`).toEqual({ min: want.min, max: want.max });
        else expect(got!.min <= want.min && got!.max >= want.max, `${c.id} ${slot} range`).toBe(true);
        expect(got!.average, `${c.id} ${slot} average`).toBeCloseTo(want.average, c.exact ? 9 : 0);
        expect(Math.abs(got!.koChance - want.koChance), `${c.id} ${slot} KO chance`).toBeLessThanOrEqual(c.exact ? 1e-9 : 0.015);
        expect(got!.faintsBeforeMoving ?? 0, `${c.id} ${slot} faints before moving`).toBeCloseTo(want.faintsBeforeMoving ?? 0, digits);
      }
      expect(result.steps.map((step) => step.slot).sort()).toEqual(Object.keys(c.steps).sort());
      for (const step of result.steps) {
        const want = c.steps[step.slot as DoublesSlotId]!;
        expect(step.moveId).toBe(want.moveId);
        expect(step.moves, `${c.id} ${step.slot} moves`).toBeCloseTo(want.moves, digits);
        const order = new Map(step.order.map((entry) => [entry.position, entry.chance]));
        for (const [position, chance] of want.order) expect(order.get(position) ?? 0, `${c.id} ${step.slot} order ${position}`).toBeCloseTo(chance, digits);
        expect([...order.keys()].every((position) => want.order.some(([p]) => p === position))).toBe(true);
        if (!want.hits.length) continue;
        for (const hit of want.hits) {
          const got = step.hits.find((h) => h.slot === hit.slot);
          expect(got, `${c.id} ${step.slot} → ${hit.slot}`).toBeDefined();
          expect(got!.reached, `${c.id} ${step.slot} → ${hit.slot} reached`).toBeCloseTo(hit.reached, digits);
          expect(got!.koChance, `${c.id} ${step.slot} → ${hit.slot} KO chance`).toBeCloseTo(hit.koChance, digits);
          if (hit.kind) expect(got!.kind === hit.kind || (hit.kind === "blocked" && got!.kind === "no-damage"), `${c.id} ${step.slot} → ${hit.slot} ${got!.kind}`).toBe(true);
          if (hit.min !== undefined) expect({ kind: got!.kind, min: got!.min, max: got!.max }, `${c.id} ${step.slot} → ${hit.slot}`).toEqual({ kind: "calculated", min: hit.min, max: hit.max });
        }
      }
    });
  }
});

const asCase = (g: (typeof GUARDED)[number]): Case => ({ ...g, checks: "", exact: true, hp: {} as Case["hp"], steps: {} });
const byId = (caseId: string) => CASES.find((c) => c.id === caseId)!;

describe("Neutralizing Gas in the 2v2 turn: facts, start rows, the moves pane and the outcomes", () => {
  it("states the abilities the gas suppresses, as a turn fact and in each start row", async () => {
    // NG01 (Showdown): Flamethrower 51-61 into Snorlax with Thick Fat suppressed, Body Slam 45-54 into Weezing-Galar.
    const result = calculateDoublesTurn(await input(byId("NG01")));
    expect(result.status).toBe("ready");
    if (result.status !== "ready") return;
    expect(result.facts).toContain("Neutralizing Gas suppresses the abilities of Charizard, Venusaur and Snorlax.");
    const flamethrower = result.startRows.find((row) => row.slot === "own-right")!;
    expect(flamethrower).toMatchObject({ target: "opponent-right", row: { moveId: "flamethrower", min: 51, max: 61 } });
    expect(flamethrower.row.assumptions).toEqual(expect.arrayContaining([
      "Charizard's Blaze is suppressed by Neutralizing Gas.", "Snorlax's Thick Fat is suppressed by Neutralizing Gas.",
    ]));
    expect(result.startRows.find((row) => row.slot === "opponent-right")).toMatchObject({ target: "own-left", row: { moveId: "bodyslam", min: 45, max: 54 } });
  });

  it("leaves an Ability Shield holder its ability outside Magic Room", async () => {
    // NG03 and NG04 (Showdown): Thick Fat halves Flamethrower (25-31) with the Shield; under Magic Room the Shield fails (51-61).
    const shielded = calculateDoublesTurn(await input(byId("NG03")));
    const room = calculateDoublesTurn(await input(byId("NG04")));
    if (shielded.status !== "ready" || room.status !== "ready") throw new Error(`${shielded.status} ${room.status}`);
    expect(shielded.facts).toContain("Neutralizing Gas suppresses the abilities of Charizard and Venusaur.");
    expect(shielded.startRows[0].row).toMatchObject({ moveId: "flamethrower", min: 25, max: 31 });
    expect(room.facts).toContain("Neutralizing Gas suppresses the abilities of Charizard, Venusaur and Snorlax.");
    expect(room.startRows[0].row).toMatchObject({ moveId: "flamethrower", min: 51, max: 61 });
  });

  it("lists each move's damage at the start of a turn whose gas ends, with the gas on", async () => {
    for (const g of GUARDED) {
      const result = calculateDoublesTurn(await input(asCase(g)));
      expect(result.status, g.id).toBe("not-estimated");
      if (result.status !== "not-estimated") continue;
      expect(result.reason, g.id).toBe(g.reason);
      for (const slot of SLOTS) if (g.slots[slot].move) expect(result.startRows.some((row) => row.slot === slot), `${g.id} start row for ${slot}`).toBe(true);
    }
    // NG18: Snorlax's Body Slam into Weezing-Galar 45-54 (NG01's Showdown hit) and Charizard's Flamethrower into Venusaur
    // 110-132 (NG07's), as each stands at the start of the turn.
    const ng18 = calculateDoublesTurn(await input(asCase(GUARDED.find((g) => g.id === "NG18")!)));
    if (ng18.status !== "not-estimated") throw new Error(ng18.status);
    expect(ng18.start).not.toBeNull();
    expect(ng18.startRows.map((row) => [row.slot, row.target, row.row.min, row.row.max])).toEqual([
      ["own-left", "opponent-left", 45, 54], ["own-right", "opponent-right", 110, 132],
    ]);
  });

  it("calculates the moves pane with the gas on", async () => {
    const pane = calculateDoublesMoves(await input(byId("NG01")), "own-right", "opponent-right");
    const row = pane.results.find((entry) => entry.moveId === "flamethrower")!;
    expect(row).toMatchObject({ kind: "calculated", min: 51, max: 61 });
    expect(row.assumptions).toContain("Snorlax's Thick Fat is suppressed by Neutralizing Gas.");
    expect(row.usesToKO).toMatchObject({ kind: "uses" });
  });

  it("gives the outcomes back the abilities the gas suppressed", async () => {
    const result = calculateDoublesOutcomes(await input(byId("NG01")));
    expect(result.status).toBe("ready");
    if (result.status !== "ready") return;
    let average = 0;
    for (const outcome of result.outcomes) {
      expect(outcome.mons["own-left"]!.build.abilityId).toBe("neutralizinggas");
      expect(outcome.mons["own-right"]!.build.abilityId).toBe("blaze");
      expect(outcome.mons["opponent-right"]!.build.abilityId).toBe("thickfat");
      for (const { hp, chance } of outcome.mons["opponent-right"]!.hp) average += hp * chance * outcome.chance;
    }
    // NG01 (Showdown): Snorlax's average HP after the turn.
    expect(average).toBeCloseTo(179.0625, 9);
  });

  it("is not estimated for a move that can end the gas or change what it suppresses, even as the last action", async () => {
    const swalot: Mon = { species: "Swalot", ability: "Liquid Ooze", move: "Gastro Acid", target: "opponent-left" };
    const klefki: Mon = { species: "Klefki", ability: "Prankster", move: "Magic Room" };
    const turn = (own: Mon, foe: Mon): Case => asCase({ id: "-", game: "sv", title: "", reason: "", slots: {
      "own-left": own, "own-right": { species: "Charizard", ability: "Blaze", move: null }, "opponent-left": foe, "opponent-right": { species: "Garchomp", ability: "Rough Skin", move: null },
    } });
    const gas: Mon = { species: "Weezing-Galar", ability: "Neutralizing Gas", move: null };
    const levitate: Mon = { species: "Weezing-Galar", ability: "Levitate", move: null };
    expect(calculateDoublesTurn(await input(turn(swalot, gas)))).toMatchObject({ status: "not-estimated", reason: "Gastro Acid with Neutralizing Gas is not modelled in 2v2." });
    expect(calculateDoublesTurn(await input(turn(klefki, gas)))).toMatchObject({ status: "not-estimated", reason: "Magic Room with Neutralizing Gas is not modelled in 2v2." });
    // Without the gas, a status move nothing follows changes no HP (doubles-turn-guards.test.ts): Swalot (75) moves last.
    expect(calculateDoublesTurn(await input(turn({ ...swalot, ability: "Sticky Hold" }, levitate))).status).toBe("ready");
  });

  it("still names Commander with Dondozo on its side under the gas", async () => {
    const c = asCase({ id: "-", game: "sv", title: "", reason: "", slots: {
      "own-left": { species: "Tatsugiri", ability: "Commander", move: null }, "own-right": { species: "Dondozo", ability: "Unaware", move: null },
      "opponent-left": { species: "Weezing-Galar", ability: "Neutralizing Gas", move: null }, "opponent-right": { species: "Garchomp", ability: "Rough Skin", move: "Dragon Claw", target: "own-right" },
    } });
    expect(calculateDoublesTurn(await input(c))).toMatchObject({ status: "not-estimated", reason: "Commander is not modelled in 2v2." });
  });
});
