import { describe, expect, it } from "vitest";
import { calculateDoublesMoves, calculateDoublesTurn } from "@/app/lib/battle/doubles-turn";
import { doublesTargetRule } from "@/app/lib/battle/doubles-targets";
import type { DoublesPokemonInput, DoublesSlotId, DoublesTurnInput } from "@/app/lib/battle/doubles-types";
import { loadBattleRuntime } from "@/app/lib/battle/load-runtime";
import { createBuild, createConditions, createSide, defaultAbilityActive } from "@/app/lib/battle/model";
import type { BattleRuntime } from "@/app/lib/battle/runtime";
import type { BattleBuild, BattleConditions, BattleGame, MoveContext } from "@/app/lib/battle/types";

/**
 * The engine fixes of 2v2 round 1 against pinned Showdown c23d2e94: each "ready" case's values are the exact oracle of
 * scripts/.cache/calc-audit/2v2/verify/sim-dfs.ts (every damage roll, speed tie and random event enumerated, every move hitting,
 * no critical hit, added effects below 100% failing, HP read before the end of the turn), and each guarded case's reason is the
 * fact the turn is not estimated for. Level 50, 31 IVs, Serious nature and 0 EVs / Stat Points unless set. Generated by
 * scripts/.cache/calc-audit/2v2/fix-engine/gen-fixes.ts from fix-engine/cases3.ts and review-engine/cases.ts.
 */
type Stat = "hp" | "atk" | "def" | "spa" | "spd" | "spe";
type Mon = {
  species: string; appSpecies?: string; ability: string; item?: string; nature?: string; evs?: Partial<Record<Stat, number>>;
  ivs?: Partial<Record<Stat, number>>; level?: number; hp?: number; status?: BattleBuild["status"];
  boosts?: Partial<Record<Exclude<Stat, "hp">, number>>; teraType?: string; choice?: "mega" | "terastallize" | "dynamax" | "zmove";
  charged?: boolean; appBuild?: Record<string, unknown>; absent?: boolean; gender?: string;
  move: string | null; target?: DoublesSlotId; context?: MoveContext;
};
type Side = { tailwind?: boolean; reflect?: boolean; lightScreen?: boolean; auroraVeil?: boolean };
type Field = Partial<Pick<BattleConditions, "weather" | "terrain" | "trickRoom" | "gravity" | "wonderRoom" | "magicRoom" | "critical">> & { own?: Side; opponent?: Side };
type HP = { start: number; maximum: number; low: number; high: number; min: number; max: number; average: number; koChance: number; faintsBeforeMoving?: number };
type Hit = { slot: DoublesSlotId; reached: number; koChance: number; min?: number; max?: number; kind?: "blocked" | "no-damage" };
type Step = { moveId: string; moves: number; order: [number, number][]; hits: Hit[] };
type Setup = { id: string; game: "sv" | "swsh" | "usum" | "champions"; title: string; field?: Field; slots: Record<DoublesSlotId, Mon> };
type Ready = Setup & { hp: Record<DoublesSlotId, HP | null>; steps: Partial<Record<DoublesSlotId, Step>> };
type Guarded = Setup & { reason: string };

const GAMES: Record<Setup["game"], BattleGame> = { sv: "scarlet_violet", swsh: "sword_shield", usum: "ultra_sun_ultra_moon", champions: "champions" };
const SLOTS: DoublesSlotId[] = ["own-left", "own-right", "opponent-left", "opponent-right"];
const id = (text: string) => text.toLowerCase().replace(/[^a-z0-9]+/g, "");
const ZERO = { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 };

function build(m: Mon, runtime: BattleRuntime): BattleBuild {
  const base = createBuild(m.appSpecies ?? id(m.species), runtime);
  const abilityId = id(m.ability);
  const shared = {
    nature: m.nature ?? "Serious", abilityId, abilityActive: defaultAbilityActive(abilityId), itemId: id(m.item ?? ""),
    boosts: { atk: 0, def: 0, spa: 0, spd: 0, spe: 0, ...m.boosts }, currentHP: m.hp ?? null, status: m.status ?? "",
  };
  const configuration = { ...base.configuration, ...(m.teraType ? { teraType: m.teraType } : {}) };
  const mechanic = m.choice === "terastallize" ? { mechanic: "tera" as const } : m.choice === "dynamax" ? { mechanic: "dynamax" as const } : {};
  const trained = base.game === "champions"
    ? { ...base, ...shared, points: { ...ZERO, ...m.evs } }
    : { ...base, ...shared, native: { level: m.level ?? 50, evs: { ...ZERO, ...m.evs }, ivs: { hp: 31, atk: 31, def: 31, spa: 31, spd: 31, spe: 31, ...m.ivs } } };
  return { ...trained, ...(Object.keys(configuration).length ? { configuration } : {}), ...mechanic, ...m.appBuild } as BattleBuild;
}
function side(s: Side | undefined) {
  return { ...createSide(), tailwind: !!s?.tailwind, reflect: !!s?.reflect, lightScreen: !!s?.lightScreen, auroraVeil: !!s?.auroraVeil };
}
async function input(c: Setup): Promise<DoublesTurnInput> {
  const runtime = await loadBattleRuntime(GAMES[c.game]);
  const f = c.field ?? {};
  const field: BattleConditions = {
    ...createConditions(), gameType: "Doubles", weather: f.weather ?? "", terrain: f.terrain ?? "", critical: !!f.critical,
    trickRoom: !!f.trickRoom, gravity: !!f.gravity, wonderRoom: !!f.wonderRoom, magicRoom: !!f.magicRoom,
    attackerSide: side(f.own), defenderSide: side(f.opponent),
  };
  const pokemon = Object.fromEntries(SLOTS.map((slot) => {
    const m = c.slots[slot];
    if (m.absent) return [slot, null];
    const moveId = m.move === null ? null : id(m.move);
    const context: MoveContext = { ...(m.choice === "zmove" ? { useZ: true } : {}), ...m.context };
    const entry: DoublesPokemonInput = {
      build: build(m, runtime), contexts: moveId && Object.keys(context).length ? { [moveId]: context } : {}, charged: !!m.charged,
      action: { moveId, target: m.target ?? null },
    };
    return [slot, entry];
  })) as Record<DoublesSlotId, DoublesPokemonInput | null>;
  return { runtime, field, pokemon };
}
const find = (list: Setup[], key: string) => list.find((c) => c.id === key)!;

/** Ready cases with the oracle's values (fix-engine/results, review-engine/results). */
const READY: Ready[] = [
  {id:"R04",game:"sv",title:"A move aimed at a fainted ally goes to a foe's Follow Me",slots:{"own-left":{species:"Snorlax",ability:"Thick Fat",move:"Body Slam",target:"own-right"},"own-right":{species:"Venusaur",ability:"Overgrow",hp:1,move:null},"opponent-left":{species:"Clefable",ability:"Magic Guard",move:"Follow Me"},"opponent-right":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Dragon Claw",target:"own-right"}},hp:{"own-left":{start:235,maximum:235,low:235,high:235,min:235,max:235,average:235,koChance:0},"own-right":{start:1,maximum:155,low:0,high:0,min:0,max:0,average:0,koChance:1},"opponent-left":{start:170,maximum:170,low:103,high:89,min:89,max:103,average:96.0625,koChance:0},"opponent-right":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0}},steps:{"own-left":{moveId:"bodyslam",moves:1,order:[[3,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,min:67,max:81}]},"opponent-left":{moveId:"followme",moves:1,order:[[1,1]],hits:[]},"opponent-right":{moveId:"dragonclaw",moves:1,order:[[2,1]],hits:[{slot:"own-right",reached:1,koChance:1,min:81,max:96}]}}},
  {id:"R05",game:"swsh",title:"Flower Gift raises its partner's Sp. Def in sun",field:{weather:"Sun"},slots:{"own-left":{species:"Cherrim",ability:"Flower Gift",move:null},"own-right":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-left":{species:"Charizard",ability:"Blaze",nature:"Timid",evs:{spa:252,spe:252},move:"Air Slash",target:"own-right"},"opponent-right":{species:"Blastoise",ability:"Torrent",move:null}},hp:{"own-left":{start:145,maximum:145,low:145,high:145,min:145,max:145,average:145,koChance:0},"own-right":{start:155,maximum:155,low:77,high:63,min:63,max:77,average:70.875,koChance:0},"opponent-left":{start:153,maximum:153,low:153,high:153,min:153,max:153,average:153,koChance:0},"opponent-right":{start:154,maximum:154,low:154,high:154,min:154,max:154,average:154,koChance:0}},steps:{"opponent-left":{moveId:"airslash",moves:1,order:[[1,1]],hits:[{slot:"own-right",reached:1,koChance:0,min:78,max:92}]}}},
  {id:"R05u",game:"usum",title:"Flower Gift raises its partner's Sp. Def in sun (USUM)",field:{weather:"Sun"},slots:{"own-left":{species:"Cherrim",ability:"Flower Gift",move:null},"own-right":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-left":{species:"Charizard",ability:"Blaze",nature:"Timid",evs:{spa:252,spe:252},move:"Air Slash",target:"own-right"},"opponent-right":{species:"Blastoise",ability:"Torrent",move:null}},hp:{"own-left":{start:145,maximum:145,low:145,high:145,min:145,max:145,average:145,koChance:0},"own-right":{start:155,maximum:155,low:77,high:63,min:63,max:77,average:70.875,koChance:0},"opponent-left":{start:153,maximum:153,low:153,high:153,min:153,max:153,average:153,koChance:0},"opponent-right":{start:154,maximum:154,low:154,high:154,min:154,max:154,average:154,koChance:0}},steps:{"opponent-left":{moveId:"airslash",moves:1,order:[[1,1]],hits:[{slot:"own-right",reached:1,koChance:0,min:78,max:92}]}}},
  {id:"R06",game:"usum",title:"Clangorous Soulblaze hits both foes",slots:{"own-left":{species:"Kommo-o",ability:"Bulletproof",item:"Kommonium Z",nature:"Timid",evs:{spa:252,spe:252},choice:"zmove",move:"Clanging Scales"},"own-right":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-left":{species:"Blastoise",ability:"Torrent",move:null},"opponent-right":{species:"Charizard",ability:"Blaze",move:null}},hp:{"own-left":{start:150,maximum:150,low:150,high:150,min:150,max:150,average:150,koChance:0},"own-right":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-left":{start:154,maximum:154,low:60,high:42,min:42,max:60,average:50.75,koChance:0},"opponent-right":{start:153,maximum:153,low:41,high:20,min:20,max:41,average:30.4375,koChance:0}},steps:{"own-left":{moveId:"clangingscales",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:112,max:133},{slot:"opponent-left",reached:1,koChance:0,min:94,max:112}]}}},
  {id:"R08",game:"sv",title:"Unburden after a Sitrus Berry: the re-sort reads the doubled Speed",slots:{"own-left":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Dragon Claw",target:"opponent-left"},"own-right":{species:"Charizard",ability:"Blaze",nature:"Timid",evs:{spa:252,spe:252},move:"Air Slash",target:"opponent-left"},"opponent-left":{species:"Hawlucha",ability:"Unburden",item:"Sitrus Berry",move:"Close Combat",target:"own-right"},"opponent-right":{species:"Snorlax",ability:"Thick Fat",move:null}},hp:{"own-left":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"own-right":{start:153,maximum:153,low:114,high:107,min:107,max:114,average:110.75,koChance:0},"opponent-left":{start:153,maximum:153,low:0,high:0,min:0,max:0,average:0,koChance:1},"opponent-right":{start:235,maximum:235,low:235,high:235,min:235,max:235,average:235,koChance:0}},steps:{"own-left":{moveId:"dragonclaw",moves:1,order:[[1,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,min:87,max:103}]},"own-right":{moveId:"airslash",moves:1,order:[[3,1]],hits:[{slot:"opponent-left",reached:1,koChance:1,min:248,max:294}]},"opponent-left":{moveId:"closecombat",moves:1,order:[[2,1]],hits:[{slot:"own-right",reached:1,koChance:0,min:39,max:46}]}}},
  {id:"R17",game:"champions",title:"Champions Speeds above 999 are not tied",field:{own:{tailwind:true},opponent:{tailwind:true}},slots:{"own-left":{species:"Dragapult",ability:"Clear Body",nature:"Jolly",evs:{spe:32},hp:1,boosts:{spe:6},move:"Dragon Claw",target:"opponent-left"},"own-right":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-left":{species:"Garchomp",ability:"Sand Veil",nature:"Jolly",evs:{spe:32},hp:1,boosts:{spe:6},move:"Dragon Claw",target:"own-left"},"opponent-right":{species:"Blastoise",ability:"Torrent",move:null}},hp:{"own-left":{start:1,maximum:163,low:1,high:1,min:1,max:1,average:1,koChance:0},"own-right":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-left":{start:1,maximum:183,low:0,high:0,min:0,max:0,average:0,koChance:1,faintsBeforeMoving:1},"opponent-right":{start:154,maximum:154,low:154,high:154,min:154,max:154,average:154,koChance:0}},steps:{"own-left":{moveId:"dragonclaw",moves:1,order:[[1,1]],hits:[{slot:"opponent-left",reached:1,koChance:1,min:110,max:132}]},"opponent-left":{moveId:"dragonclaw",moves:0,order:[[2,1]],hits:[]}}},
  {id:"F16a",game:"sv",title:"Thunderbolt at a fainted foe goes to the partner's Lightning Rod",slots:{"own-left":{species:"Pikachu",ability:"Static",move:"Thunderbolt",target:"opponent-left"},"own-right":{species:"Raichu",ability:"Lightning Rod",nature:"Jolly",evs:{spe:252},move:"Quick Attack",target:"opponent-left"},"opponent-left":{species:"Snorlax",ability:"Thick Fat",hp:1,move:null},"opponent-right":{species:"Blastoise",ability:"Torrent",absent:true,move:null}},hp:{"own-left":{start:110,maximum:110,low:110,high:110,min:110,max:110,average:110,koChance:0},"own-right":{start:135,maximum:135,low:135,high:135,min:135,max:135,average:135,koChance:0},"opponent-left":{start:1,maximum:235,low:0,high:0,min:0,max:0,average:0,koChance:1},"opponent-right":null},steps:{"own-left":{moveId:"thunderbolt",moves:1,order:[[2,1]],hits:[{slot:"own-right",reached:1,koChance:0,kind:"blocked"}]},"own-right":{moveId:"quickattack",moves:1,order:[[1,1]],hits:[{slot:"opponent-left",reached:1,koChance:1,min:20,max:24}]}}},
  {id:"F16b",game:"sv",title:"A move aimed at a fainted ally with no redirection fails",slots:{"own-left":{species:"Snorlax",ability:"Thick Fat",move:"Body Slam",target:"own-right"},"own-right":{species:"Venusaur",ability:"Overgrow",hp:1,move:null},"opponent-left":{species:"Clefable",ability:"Magic Guard",move:null},"opponent-right":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Dragon Claw",target:"own-right"}},hp:{"own-left":{start:235,maximum:235,low:235,high:235,min:235,max:235,average:235,koChance:0},"own-right":{start:1,maximum:155,low:0,high:0,min:0,max:0,average:0,koChance:1},"opponent-left":{start:170,maximum:170,low:170,high:170,min:170,max:170,average:170,koChance:0},"opponent-right":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0}},steps:{"own-left":{moveId:"bodyslam",moves:1,order:[[2,1]],hits:[]},"opponent-right":{moveId:"dragonclaw",moves:1,order:[[1,1]],hits:[{slot:"own-right",reached:1,koChance:1,min:81,max:96}]}}},
  {id:"F18a",game:"usum",title:"Clangorous Soulblaze into a lone foe",slots:{"own-left":{species:"Kommo-o",ability:"Bulletproof",item:"Kommonium Z",nature:"Timid",evs:{spa:252,spe:252},choice:"zmove",move:"Clanging Scales"},"own-right":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-left":{species:"Blastoise",ability:"Torrent",move:null},"opponent-right":{species:"Charizard",ability:"Blaze",nature:"Timid",evs:{spa:252,spe:252},absent:true,move:null}},hp:{"own-left":{start:150,maximum:150,low:150,high:150,min:150,max:150,average:150,koChance:0},"own-right":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-left":{start:154,maximum:154,low:27,high:4,min:4,max:27,average:15.5,koChance:0},"opponent-right":null},steps:{"own-left":{moveId:"clangingscales",moves:1,order:[[1,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,min:127,max:150}]}}},
  {id:"F15a",game:"champions",title:"Champions Trick Room with Speeds above 999",field:{trickRoom:true,own:{tailwind:true},opponent:{tailwind:true}},slots:{"own-left":{species:"Dragapult",ability:"Clear Body",nature:"Jolly",evs:{spe:32},hp:1,boosts:{spe:6},move:"Dragon Claw",target:"opponent-left"},"own-right":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-left":{species:"Garchomp",ability:"Sand Veil",nature:"Jolly",evs:{spe:32},hp:1,boosts:{spe:6},move:"Dragon Claw",target:"own-left"},"opponent-right":{species:"Blastoise",ability:"Torrent",move:null}},hp:{"own-left":{start:1,maximum:163,low:0,high:0,min:0,max:0,average:0,koChance:1,faintsBeforeMoving:1},"own-right":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-left":{start:1,maximum:183,low:1,high:1,min:1,max:1,average:1,koChance:0},"opponent-right":{start:154,maximum:154,low:154,high:154,min:154,max:154,average:154,koChance:0}},steps:{"own-left":{moveId:"dragonclaw",moves:0,order:[[2,1]],hits:[]},"opponent-left":{moveId:"dragonclaw",moves:1,order:[[1,1]],hits:[{slot:"own-left",reached:1,koChance:1,min:144,max:170}]}}},
  {id:"F17a",game:"swsh",title:"Flower Gift raises its partner's Attack in sun",field:{weather:"Sun"},slots:{"own-left":{species:"Cherrim",ability:"Flower Gift",move:null},"own-right":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Dragon Claw",target:"opponent-left"},"opponent-left":{species:"Snorlax",ability:"Thick Fat",move:null},"opponent-right":{species:"Blastoise",ability:"Torrent",move:null}},hp:{"own-left":{start:145,maximum:145,low:145,high:145,min:145,max:145,average:145,koChance:0},"own-right":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"opponent-left":{start:235,maximum:235,low:90,high:63,min:63,max:90,average:76.4375,koChance:0},"opponent-right":{start:154,maximum:154,low:154,high:154,min:154,max:154,average:154,koChance:0}},steps:{"own-right":{moveId:"dragonclaw",moves:1,order:[[1,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,min:145,max:172}]}}},
  {id:"F17b",game:"swsh",title:"Mold Breaker ignores Flower Gift on the target's partner",field:{weather:"Sun"},slots:{"own-left":{species:"Cherrim",ability:"Flower Gift",move:null},"own-right":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-left":{species:"Haxorus",ability:"Mold Breaker",nature:"Modest",move:"Draco Meteor",target:"own-right"},"opponent-right":{species:"Blastoise",ability:"Torrent",move:null}},hp:{"own-left":{start:145,maximum:145,low:145,high:145,min:145,max:145,average:145,koChance:0},"own-right":{start:155,maximum:155,low:101,high:91,min:91,max:101,average:96.375,koChance:0},"opponent-left":{start:151,maximum:151,low:151,high:151,min:151,max:151,average:151,koChance:0},"opponent-right":{start:154,maximum:154,low:154,high:154,min:154,max:154,average:154,koChance:0}},steps:{"opponent-left":{moveId:"dracometeor",moves:1,order:[[1,1]],hits:[{slot:"own-right",reached:1,koChance:0,min:54,max:64}]}}},
  {id:"F17c",game:"swsh",title:"Utility Umbrella keeps the sun off Flower Gift's partner",field:{weather:"Sun"},slots:{"own-left":{species:"Cherrim",ability:"Flower Gift",move:null},"own-right":{species:"Venusaur",ability:"Overgrow",item:"Utility Umbrella",move:null},"opponent-left":{species:"Charizard",ability:"Blaze",nature:"Timid",evs:{spa:252,spe:252},move:"Air Slash",target:"own-right"},"opponent-right":{species:"Blastoise",ability:"Torrent",move:null}},hp:{"own-left":{start:145,maximum:145,low:145,high:145,min:145,max:145,average:145,koChance:0},"own-right":{start:155,maximum:155,low:39,high:17,min:17,max:39,average:29.125,koChance:0},"opponent-left":{start:153,maximum:153,low:153,high:153,min:153,max:153,average:153,koChance:0},"opponent-right":{start:154,maximum:154,low:154,high:154,min:154,max:154,average:154,koChance:0}},steps:{"opponent-left":{moveId:"airslash",moves:1,order:[[1,1]],hits:[{slot:"own-right",reached:1,koChance:0,min:116,max:138}]}}},
  {id:"F30a",game:"sv",title:"A third Pokémon's Unnerve stops the target's Sitrus Berry",slots:{"own-left":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Dragon Claw",target:"opponent-left"},"own-right":{species:"Tyranitar",ability:"Unnerve",move:null},"opponent-left":{species:"Snorlax",ability:"Thick Fat",item:"Sitrus Berry",hp:120,move:null},"opponent-right":{species:"Blastoise",ability:"Torrent",move:null}},hp:{"own-left":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"own-right":{start:175,maximum:175,low:175,high:175,min:175,max:175,average:175,koChance:0},"opponent-left":{start:120,maximum:235,low:23,high:5,min:5,max:23,average:14.125,koChance:0},"opponent-right":{start:154,maximum:154,low:154,high:154,min:154,max:154,average:154,koChance:0}},steps:{"own-left":{moveId:"dragonclaw",moves:1,order:[[1,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,min:97,max:115}]}}},
  {id:"F30b",game:"sv",title:"An attacker's Unnerve does not stop its own partner's Sitrus Berry",slots:{"own-left":{species:"Tyranitar",ability:"Unnerve",move:"Crunch",target:"own-right"},"own-right":{species:"Snorlax",ability:"Thick Fat",item:"Sitrus Berry",hp:120,move:null},"opponent-left":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-right":{species:"Blastoise",ability:"Torrent",move:null}},hp:{"own-left":{start:175,maximum:175,low:175,high:175,min:175,max:175,average:175,koChance:0},"own-right":{start:120,maximum:235,low:96,high:81,min:81,max:96,average:88.8125,koChance:0},"opponent-left":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-right":{start:154,maximum:154,low:154,high:154,min:154,max:154,average:154,koChance:0}},steps:{"own-left":{moveId:"crunch",moves:1,order:[[1,1]],hits:[{slot:"own-right",reached:1,koChance:0,min:82,max:97}]}}},
  {id:"F30c",game:"sv",title:"A third Pokémon's Unnerve stops the attacker's Sitrus Berry after recoil",slots:{"own-left":{species:"Garchomp",ability:"Rough Skin",item:"Sitrus Berry",hp:100,nature:"Jolly",evs:{atk:252,spe:252},move:"Double-Edge",target:"opponent-left"},"own-right":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-left":{species:"Snorlax",ability:"Thick Fat",move:null},"opponent-right":{species:"Tyranitar",ability:"Unnerve",move:null}},hp:{"own-left":{start:100,maximum:183,low:68,high:62,min:62,max:68,average:65.0625,koChance:0},"own-right":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-left":{start:235,maximum:235,low:138,high:120,min:120,max:138,average:129.125,koChance:0},"opponent-right":{start:175,maximum:175,low:175,high:175,min:175,max:175,average:175,koChance:0}},steps:{"own-left":{moveId:"doubleedge",moves:1,order:[[1,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,min:97,max:115}]}}},
  {id:"F30e",game:"sv",title:"A third Pokémon's Unnerve and a Figy-family Berry eaten in a spread move",slots:{"own-left":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Rock Slide"},"own-right":{species:"Tyranitar",ability:"Unnerve",move:null},"opponent-left":{species:"Snorlax",ability:"Thick Fat",item:"Figy Berry",hp:70,move:null},"opponent-right":{species:"Blastoise",ability:"Torrent",item:"Sitrus Berry",hp:90,move:null}},hp:{"own-left":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"own-right":{start:175,maximum:175,low:175,high:175,min:175,max:175,average:175,koChance:0},"opponent-left":{start:70,maximum:235,low:25,high:16,min:16,max:25,average:20.5625,koChance:0},"opponent-right":{start:90,maximum:154,low:57,high:51,min:51,max:57,average:54.375,koChance:0}},steps:{"own-left":{moveId:"rockslide",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:33,max:39},{slot:"opponent-left",reached:1,koChance:0,min:45,max:54}]}}},
  {id:"F31a",game:"sv",title:"Throat Chop before a slower sound move",slots:{"own-left":{species:"Kingambit",ability:"Defiant",nature:"Jolly",evs:{spe:252},move:"Throat Chop",target:"opponent-right"},"own-right":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-left":{species:"Snorlax",ability:"Thick Fat",move:null},"opponent-right":{species:"Sylveon",ability:"Pixilate",move:"Hyper Voice"}},hp:{"own-left":{start:175,maximum:175,low:175,high:175,min:175,max:175,average:175,koChance:0},"own-right":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-left":{start:235,maximum:235,low:235,high:235,min:235,max:235,average:235,koChance:0},"opponent-right":{start:170,maximum:170,low:128,high:121,min:121,max:128,average:124.8125,koChance:0}},steps:{"own-left":{moveId:"throatchop",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:42,max:49}]},"opponent-right":{moveId:"hypervoice",moves:0,order:[[2,1]],hits:[]}}},
  {id:"F31b",game:"sv",title:"Throat Chop before a slower move that is not a sound move",slots:{"own-left":{species:"Kingambit",ability:"Defiant",nature:"Jolly",evs:{spe:252},move:"Throat Chop",target:"opponent-right"},"own-right":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-left":{species:"Snorlax",ability:"Thick Fat",move:null},"opponent-right":{species:"Sylveon",ability:"Pixilate",move:"Moonblast",target:"own-left"}},hp:{"own-left":{start:175,maximum:175,low:108,high:96,min:96,max:108,average:102.4375,koChance:0},"own-right":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-left":{start:235,maximum:235,low:235,high:235,min:235,max:235,average:235,koChance:0},"opponent-right":{start:170,maximum:170,low:128,high:121,min:121,max:128,average:124.8125,koChance:0}},steps:{"own-left":{moveId:"throatchop",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:42,max:49}]},"opponent-right":{moveId:"moonblast",moves:1,order:[[2,1]],hits:[{slot:"own-left",reached:1,koChance:0,min:67,max:79}]}}},
  {id:"F32a",game:"swsh",title:"Mirror Armor on the other foe of a Max Darkness",slots:{"own-left":{species:"Weavile",ability:"Pressure",nature:"Jolly",evs:{atk:252,spe:252},choice:"dynamax",move:"Night Slash",target:"opponent-left"},"own-right":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-left":{species:"Snorlax",ability:"Thick Fat",nature:"Modest",move:"Fire Blast",target:"own-left"},"opponent-right":{species:"Corviknight",ability:"Mirror Armor",move:null}},hp:{"own-left":{start:290,maximum:290,low:178,high:158,min:158,max:178,average:168.625,koChance:0},"own-right":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-left":{start:235,maximum:235,low:99,high:73,min:73,max:99,average:86.1875,koChance:0},"opponent-right":{start:173,maximum:173,low:173,high:173,min:173,max:173,average:173,koChance:0}},steps:{"own-left":{moveId:"nightslash",moves:1,order:[[1,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,min:136,max:162}]},"opponent-left":{moveId:"fireblast",moves:1,order:[[2,1]],hits:[{slot:"own-left",reached:1,koChance:0,min:112,max:132}]}}},
  {id:"F13a",game:"sv",title:"A Figy Berry eaten without a disliked Nature",slots:{"own-left":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Dragon Claw",target:"opponent-left"},"own-right":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-left":{species:"Snorlax",ability:"Thick Fat",nature:"Adamant",item:"Figy Berry",hp:150,move:"Body Slam",target:"own-right"},"opponent-right":{species:"Blastoise",ability:"Torrent",move:null}},hp:{"own-left":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"own-right":{start:155,maximum:155,low:88,high:76,min:76,max:88,average:82.4375,koChance:0},"opponent-left":{start:150,maximum:235,low:131,high:113,min:113,max:131,average:122.125,koChance:0},"opponent-right":{start:154,maximum:154,low:154,high:154,min:154,max:154,average:154,koChance:0}},steps:{"own-left":{moveId:"dragonclaw",moves:1,order:[[1,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,min:97,max:115}]},"opponent-left":{moveId:"bodyslam",moves:1,order:[[2,1]],hits:[{slot:"own-right",reached:1,koChance:0,min:67,max:79}]}}},
  {id:"F12a",game:"sv",title:"Glaive Rush with no later damaging move",slots:{"own-left":{species:"Baxcalibur",ability:"Thermal Exchange",nature:"Jolly",evs:{atk:252,spe:252},move:"Glaive Rush",target:"opponent-right"},"own-right":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-left":{species:"Charizard",ability:"Blaze",nature:"Timid",evs:{spa:252,spe:252},move:null},"opponent-right":{species:"Blastoise",ability:"Torrent",move:null}},hp:{"own-left":{start:190,maximum:190,low:190,high:190,min:190,max:190,average:190,koChance:0},"own-right":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-left":{start:153,maximum:153,low:153,high:153,min:153,max:153,average:153,koChance:0},"opponent-right":{start:154,maximum:154,low:43,high:22,min:22,max:43,average:32.8125,koChance:0}},steps:{"own-left":{moveId:"glaiverush",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:111,max:132}]}}},
  {id:"F10a",game:"sv",title:"Protean with no later damaging move",slots:{"own-left":{species:"Greninja",ability:"Protean",nature:"Timid",evs:{spa:252,spe:252},move:"Ice Beam",target:"opponent-right"},"own-right":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-left":{species:"Pelipper",ability:"Drizzle",move:"Tailwind"},"opponent-right":{species:"Blastoise",ability:"Torrent",move:null}},hp:{"own-left":{start:147,maximum:147,low:147,high:147,min:147,max:147,average:147,koChance:0},"own-right":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-left":{start:135,maximum:135,low:135,high:135,min:135,max:135,average:135,koChance:0},"opponent-right":{start:154,maximum:154,low:122,high:116,min:116,max:122,average:119.4375,koChance:0}},steps:{"own-left":{moveId:"icebeam",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:32,max:38}]},"opponent-left":{moveId:"tailwind",moves:1,order:[[2,1]],hits:[]}}},
  {id:"F05a",game:"swsh",title:"Bolt Beak into a target using a priority move",slots:{"own-left":{species:"Dracozolt",ability:"Volt Absorb",move:"Bolt Beak",target:"opponent-left"},"own-right":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-left":{species:"Azumarill",ability:"Huge Power",move:"Aqua Jet",target:"own-right"},"opponent-right":{species:"Blastoise",ability:"Torrent",move:null}},hp:{"own-left":{start:165,maximum:165,low:165,high:165,min:165,max:165,average:165,koChance:0},"own-right":{start:155,maximum:155,low:140,high:137,min:137,max:140,average:138.3125,koChance:0},"opponent-left":{start:175,maximum:175,low:59,high:37,min:37,max:59,average:49.125,koChance:0},"opponent-right":{start:154,maximum:154,low:154,high:154,min:154,max:154,average:154,koChance:0}},steps:{"own-left":{moveId:"boltbeak",moves:1,order:[[2,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,min:116,max:138}]},"opponent-left":{moveId:"aquajet",moves:1,order:[[1,1]],hits:[{slot:"own-right",reached:1,koChance:0,min:15,max:18}]}}},
  {id:"F05b",game:"sv",title:"Analytic moving last",slots:{"own-left":{species:"Magnezone",ability:"Analytic",move:"Flash Cannon",target:"opponent-left"},"own-right":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-left":{species:"Blastoise",ability:"Torrent",move:null},"opponent-right":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Dragon Claw",target:"own-right"}},hp:{"own-left":{start:145,maximum:145,low:145,high:145,min:145,max:145,average:145,koChance:0},"own-right":{start:155,maximum:155,low:74,high:59,min:59,max:74,average:67.0625,koChance:0},"opponent-left":{start:154,maximum:154,low:119,high:112,min:112,max:119,average:115.875,koChance:0},"opponent-right":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0}},steps:{"own-left":{moveId:"flashcannon",moves:1,order:[[2,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,min:35,max:42}]},"opponent-right":{moveId:"dragonclaw",moves:1,order:[[1,1]],hits:[{slot:"own-right",reached:1,koChance:0,min:81,max:96}]}}},
  {id:"F30f",game:"sv",title:"An Earthquake user's Unnerve and its partner's Sitrus Berry",slots:{"own-left":{species:"Tyranitar",ability:"Unnerve",move:"Earthquake"},"own-right":{species:"Snorlax",ability:"Thick Fat",item:"Sitrus Berry",hp:140,move:null},"opponent-left":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-right":{species:"Blastoise",ability:"Torrent",item:"Sitrus Berry",hp:100,move:null}},hp:{"own-left":{start:175,maximum:175,low:175,high:175,min:175,max:175,average:175,koChance:0},"own-right":{start:140,maximum:235,low:147,high:137,min:137,max:147,average:142.0625,koChance:0},"opponent-left":{start:155,maximum:155,low:113,high:105,min:105,max:113,average:109,koChance:0},"opponent-right":{start:100,maximum:154,low:64,high:57,min:57,max:64,average:60.75,koChance:0}},steps:{"own-left":{moveId:"earthquake",moves:1,order:[[1,1]],hits:[{slot:"own-right",reached:1,koChance:0,min:51,max:61},{slot:"opponent-right",reached:1,koChance:0,min:36,max:43},{slot:"opponent-left",reached:1,koChance:0,min:42,max:50}]}}},
  {id:"F30g",game:"swsh",title:"Self-Destruct from an Unnerve user and the targets' Sitrus Berries",slots:{"own-left":{species:"Mewtwo",ability:"Unnerve",move:"Self-Destruct"},"own-right":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-left":{species:"Snorlax",ability:"Thick Fat",item:"Sitrus Berry",hp:140,move:null},"opponent-right":{species:"Blastoise",ability:"Torrent",item:"Sitrus Berry",hp:120,move:null}},hp:{"own-left":{start:181,maximum:181,low:0,high:0,min:0,max:0,average:0,koChance:1},"own-right":{start:155,maximum:155,low:83,high:70,min:70,max:83,average:76.8125,koChance:0},"opponent-left":{start:140,maximum:235,low:112,high:96,min:96,max:112,average:104.4375,koChance:0},"opponent-right":{start:120,maximum:154,low:96,high:85,min:85,max:96,average:90.9375,koChance:0}},steps:{"own-left":{moveId:"selfdestruct",moves:1,order:[[1,1]],hits:[{slot:"own-right",reached:1,koChance:0,min:72,max:85},{slot:"opponent-right",reached:1,koChance:0,min:62,max:73},{slot:"opponent-left",reached:1,koChance:0,min:86,max:102}]}}},
];
/** Guarded cases with the reason the turn is not estimated for. */
const GUARDED: Guarded[] = [
  {id:"R02",game:"sv",title:"Protean changes the user's type before a later hit into it",slots:{"own-left":{species:"Greninja",ability:"Protean",nature:"Timid",evs:{spa:252,spe:252},move:"Ice Beam",target:"opponent-right"},"own-right":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-left":{species:"Charizard",ability:"Blaze",move:"Flamethrower",target:"own-left"},"opponent-right":{species:"Blastoise",ability:"Torrent",move:null}},reason:"Protean changes Greninja's type: later moves are not modelled."},
  {id:"R03",game:"sv",title:"Double Shock removes the user's Electric type before a later Ground hit",slots:{"own-left":{species:"Pawmot",ability:"Natural Cure",nature:"Jolly",evs:{atk:252,spe:252},move:"Double Shock",target:"opponent-right"},"own-right":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-left":{species:"Garchomp",ability:"Rough Skin",move:"Earth Power",target:"own-left"},"opponent-right":{species:"Blastoise",ability:"Torrent",move:null}},reason:"Double Shock changes Pawmot's type: later moves are not modelled."},
  {id:"R07",game:"swsh",title:"Burn Up removes the user's Fire type before a later Water hit",slots:{"own-left":{species:"Arcanine",ability:"Flash Fire",nature:"Jolly",evs:{atk:252,spe:252},move:"Burn Up",target:"opponent-right"},"own-right":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-left":{species:"Blastoise",ability:"Torrent",move:"Water Pulse",target:"own-left"},"opponent-right":{species:"Snorlax",ability:"Thick Fat",move:null}},reason:"Burn Up changes Arcanine's type: later moves are not modelled."},
  {id:"R09",game:"sv",title:"Fire Pledge and Grass Pledge from partners combine",slots:{"own-left":{species:"Charizard",ability:"Blaze",move:"Fire Pledge",target:"opponent-left"},"own-right":{species:"Venusaur",ability:"Overgrow",move:"Grass Pledge",target:"opponent-left"},"opponent-left":{species:"Snorlax",ability:"Thick Fat",move:null},"opponent-right":{species:"Blastoise",ability:"Torrent",move:null}},reason:"Fire Pledge with Grass Pledge is not modelled in 2v2."},
  {id:"R10",game:"sv",title:"Copycat used last copies the move before it",slots:{"own-left":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:null},"own-right":{species:"Clefable",ability:"Magic Guard",move:"Copycat"},"opponent-left":{species:"Charizard",ability:"Blaze",move:null},"opponent-right":{species:"Blastoise",ability:"Torrent",move:"Water Pulse",target:"own-left"}},reason:"Copycat is not modelled in 2v2."},
  {id:"R13",game:"sv",title:"Dragon Tail forces its target out before a second -6 move into that slot",slots:{"own-left":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Dragon Tail",target:"opponent-left"},"own-right":{species:"Dragonite",ability:"Inner Focus",move:"Dragon Tail",target:"opponent-left"},"opponent-left":{species:"Blastoise",ability:"Torrent",move:null},"opponent-right":{species:"Venusaur",ability:"Overgrow",move:null}},reason:"Blastoise switches out: the replacement is not known."},
  {id:"R14",game:"sv",title:"Glaive Rush doubles the damage its user takes later in the turn",slots:{"own-left":{species:"Baxcalibur",ability:"Thermal Exchange",nature:"Jolly",evs:{atk:252,spe:252},move:"Glaive Rush",target:"opponent-right"},"own-right":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-left":{species:"Charizard",ability:"Blaze",move:"Air Slash",target:"own-left"},"opponent-right":{species:"Blastoise",ability:"Torrent",move:null}},reason:"Glaive Rush doubles the damage Baxcalibur takes: later moves are not modelled."},
  {id:"R16",game:"usum",title:"Z-Protect (a status Z-Move) blocks like Protect",slots:{"own-left":{species:"Snorlax",ability:"Thick Fat",item:"Normalium Z",choice:"zmove",move:"Protect"},"own-right":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-left":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Dragon Claw",target:"own-left"},"opponent-right":{species:"Blastoise",ability:"Torrent",move:null}},reason:"Status Z-Moves are not calculated."},
  {id:"F22a",game:"sv",title:"Steadfast's Speed after a flinch and an Opportunist foe",slots:{"own-left":{species:"Hariyama",ability:"Thick Fat",move:"Fake Out",target:"opponent-left"},"own-right":{species:"Espathra",ability:"Opportunist",move:null},"opponent-left":{species:"Lucario",ability:"Steadfast",move:"Close Combat",target:"own-left"},"opponent-right":{species:"Blastoise",ability:"Torrent",move:null}},reason:"Opportunist copying a stat rise is not modelled in 2v2."},
  {id:"F14a",game:"sv",title:"Sleep Talk while asleep",slots:{"own-left":{species:"Snorlax",ability:"Thick Fat",status:"slp",move:"Sleep Talk"},"own-right":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-left":{species:"Blastoise",ability:"Torrent",move:"Water Pulse",target:"own-left"},"opponent-right":{species:"Charizard",ability:"Blaze",nature:"Timid",evs:{spa:252,spe:252},move:null}},reason:"Sleep Talk is not modelled in 2v2."},
  {id:"F14c",game:"sv",title:"Sleep Talk with Comatose",slots:{"own-left":{species:"Komala",ability:"Comatose",move:"Sleep Talk"},"own-right":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-left":{species:"Blastoise",ability:"Torrent",move:"Water Pulse",target:"own-left"},"opponent-right":{species:"Charizard",ability:"Blaze",nature:"Timid",evs:{spa:252,spe:252},move:null}},reason:"Sleep Talk is not modelled in 2v2."},
  {id:"F21a",game:"usum",title:"Sucker Punch against a target using Me First",slots:{"own-left":{species:"Absol",ability:"Pressure",nature:"Jolly",evs:{spe:252},move:"Sucker Punch",target:"opponent-left"},"own-right":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-left":{species:"Lickilicky",ability:"Own Tempo",move:"Me First",target:"own-left"},"opponent-right":{species:"Blastoise",ability:"Torrent",move:null}},reason:"Me First is not modelled in 2v2."},
  {id:"F30d",game:"sv",title:"A third Pokémon's As One and a target's resist Berry",slots:{"own-left":{species:"Charizard",ability:"Blaze",nature:"Timid",evs:{spa:252,spe:252},move:"Air Slash",target:"opponent-left"},"own-right":{species:"Calyrex-Shadow",ability:"As One (Spectrier)",move:null},"opponent-left":{species:"Venusaur",ability:"Overgrow",item:"Coba Berry",move:null},"opponent-right":{species:"Blastoise",ability:"Torrent",move:null}},reason:"As One (Spectrier) is not modelled in 2v2."},
];

describe("round 1 engine fixes against pinned Showdown", () => {
  for (const c of READY) {
    it(`${c.id}: ${c.title}`, async () => {
      const result = calculateDoublesTurn(await input(c));
      expect(result.status, result.status === "not-estimated" ? result.reason : result.status).toBe("ready");
      if (result.status !== "ready") return;
      for (const slot of SLOTS) {
        const want = c.hp[slot], got = result.hp[slot];
        if (!want) { expect(got, slot).toBeNull(); continue; }
        expect({ start: got!.start, maximum: got!.maximum, low: got!.low, high: got!.high, min: got!.min, max: got!.max }, `${c.id} ${slot}`)
          .toEqual({ start: want.start, maximum: want.maximum, low: want.low, high: want.high, min: want.min, max: want.max });
        expect(got!.average, `${c.id} ${slot} average`).toBeCloseTo(want.average, 9);
        expect(Math.abs(got!.koChance - want.koChance), `${c.id} ${slot} KO chance`).toBeLessThanOrEqual(1e-9);
        expect(got!.faintsBeforeMoving ?? 0, `${c.id} ${slot} faints before moving`).toBeCloseTo(want.faintsBeforeMoving ?? 0, 9);
      }
      expect(result.steps.map((step) => step.slot).sort()).toEqual(Object.keys(c.steps).sort());
      for (const step of result.steps) {
        const want = c.steps[step.slot]!;
        expect(step.moveId).toBe(want.moveId);
        expect(step.moves, `${c.id} ${step.slot} moves`).toBeCloseTo(want.moves, 9);
        const order = new Map(step.order.map((entry) => [entry.position, entry.chance]));
        for (const [position, chance] of want.order) expect(order.get(position) ?? 0, `${c.id} ${step.slot} order ${position}`).toBeCloseTo(chance, 9);
        for (const hit of want.hits) {
          const got = step.hits.find((h) => h.slot === hit.slot);
          expect(got, `${c.id} ${step.slot} → ${hit.slot}`).toBeDefined();
          expect(got!.reached, `${c.id} ${step.slot} → ${hit.slot} reached`).toBeCloseTo(hit.reached, 9);
          expect(got!.koChance, `${c.id} ${step.slot} → ${hit.slot} KO chance`).toBeCloseTo(hit.koChance, 9);
          if (hit.kind) expect(got!.kind === hit.kind || (hit.kind === "blocked" && got!.kind === "no-damage"), `${c.id} ${step.slot} → ${hit.slot} ${got!.kind}`).toBe(true);
          if (hit.min !== undefined) expect({ kind: got!.kind, min: got!.min, max: got!.max }, `${c.id} ${step.slot} → ${hit.slot}`).toEqual({ kind: "calculated", min: hit.min, max: hit.max });
        }
      }
    });
  }
});

/**
 * Round 1 guards that status-eot models (confusion from a Figy Berry and Dynamic Punch, Snore while asleep): each turn is
 * ready now; their exact values against pinned Showdown are rows of tests/unit/doubles-turn-showdown.test.ts (R01, R15, F14b).
 */
const MODELLED: Setup[] = [
  {id:"R01",game:"sv",title:"Figy Berry eaten mid-turn confuses a later attacker",slots:{"own-left":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Dragon Claw",target:"opponent-left"},"own-right":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-left":{species:"Snorlax",ability:"Thick Fat",nature:"Modest",item:"Figy Berry",hp:150,move:"Body Slam",target:"own-right"},"opponent-right":{species:"Blastoise",ability:"Torrent",move:null}}},
  {id:"R15",game:"swsh",title:"Dynamic Punch confuses a target that moves later",slots:{"own-left":{species:"Machamp",ability:"No Guard",nature:"Jolly",evs:{spe:252},move:"Dynamic Punch",target:"opponent-left"},"own-right":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-left":{species:"Blastoise",ability:"Torrent",move:"Water Pulse",target:"own-right"},"opponent-right":{species:"Snorlax",ability:"Thick Fat",move:null}}},
  {id:"F14b",game:"sv",title:"Snore while asleep",slots:{"own-left":{species:"Snorlax",ability:"Thick Fat",status:"slp",move:"Snore",target:"opponent-left"},"own-right":{species:"Venusaur",ability:"Overgrow",move:null},"opponent-left":{species:"Blastoise",ability:"Torrent",move:null},"opponent-right":{species:"Charizard",ability:"Blaze",nature:"Timid",evs:{spa:252,spe:252},move:null}}},
];

describe("round 1 guards status-eot models", () => {
  for (const c of MODELLED) {
    it(`${c.id}: ${c.title}`, async () => {
      const result = calculateDoublesTurn(await input(c));
      expect(result.status, result.status === "not-estimated" ? result.reason : result.status).toBe("ready");
    });
  }
});

describe("round 1 mechanics the turn does not estimate when they occur", () => {
  for (const c of GUARDED) {
    it(`${c.id}: ${c.title}`, async () => {
      const result = calculateDoublesTurn(await input(c));
      expect(result.status).toBe("not-estimated");
      if (result.status === "not-estimated") expect(result.reason).toBe(c.reason);
    });
  }
});

const mon = (species: string, ability: string, extra: Partial<Mon> = {}): Mon => ({ species, ability, move: null, ...extra });
const turnOf = (game: Setup["game"], slots: Record<DoublesSlotId, Mon>, field?: Field): Setup => ({ id: "", game, title: "", slots, ...(field ? { field } : {}) });

describe("round 1 engine fixes: what the turn reports", () => {
  it("a hit that knocks out on every branch has a KO chance of exactly 1 (fix-status 2)", async () => {
    const result = calculateDoublesTurn(await input(find(READY, "F16a")));
    if (result.status !== "ready") throw new Error(result.status);
    const quickAttack = result.steps.find((step) => step.moveId === "quickattack")!;
    expect(quickAttack.hits.find((hit) => hit.slot === "opponent-left")!.koChance).toBe(1);
    expect(result.hp["opponent-left"]!.koChance).toBe(1);
  });

  it("lists the attacker's Shell Bell heal on its own card (fix-status 3)", async () => {
    // Garchomp 100/183 deals 97-115 to Snorlax: Shell Bell heals 1/8 of it (12-14) before Snorlax's Body Slam.
    const result = calculateDoublesTurn(await input(turnOf("sv", {
      "own-left": mon("Garchomp", "Rough Skin", { item: "Shell Bell", hp: 100, nature: "Jolly", evs: { atk: 252, spe: 252 }, move: "Dragon Claw", target: "opponent-right" }),
      "own-right": mon("Charizard", "Blaze"), "opponent-left": mon("Venusaur", "Overgrow"),
      "opponent-right": mon("Snorlax", "Thick Fat", { move: "Body Slam", target: "own-left" }),
    })));
    if (result.status !== "ready") throw new Error(result.status);
    expect(result.hp["own-left"]!.heals).toEqual(["Shell Bell: +12–14 HP."]);
  });

  it("a Pokémon that knocks itself out has its KO chance and a fact naming the cause (fix-status 6)", async () => {
    const idle = { "own-right": mon("Venusaur", "Overgrow"), "opponent-right": mon("Blastoise", "Torrent") };
    const cases: [Mon, Mon, string][] = [
      [mon("Charizard", "Blaze", { hp: 5, move: "Flare Blitz", target: "opponent-left" }), mon("Snorlax", "Thick Fat"), "Charizard faints (recoil)."],
      [mon("Metagross", "Clear Body", { move: "Explosion" }), mon("Snorlax", "Thick Fat"), "Metagross faints (Explosion)."],
      [mon("Charizard", "Blaze", { hp: 10, move: "Dragon Claw", target: "opponent-left" }), mon("Snorlax", "Thick Fat", { item: "Rocky Helmet" }), "Charizard faints (Rocky Helmet)."],
    ];
    for (const [user, target, fact] of cases) {
      const result = calculateDoublesTurn(await input(turnOf("sv", { "own-left": user, "opponent-left": target, ...idle })));
      if (result.status !== "ready") throw new Error(result.status);
      expect(result.hp["own-left"]!.koChance, fact).toBe(1);
      expect(result.steps.find((step) => step.slot === "own-left")!.facts, fact).toContainEqual({ text: fact, chance: 1 });
    }
  });

  it("the Moves pane and the start rows read Analytic's and Bolt Beak's order as the turn does (fix-status 5)", async () => {
    // F05b: Magnezone moves last, Flash Cannon 35-42 with Analytic in the turn (the oracle's).
    const analytic = await input(find(READY, "F05b"));
    const turn = calculateDoublesTurn(analytic);
    if (turn.status !== "ready") throw new Error(turn.status);
    const hit = turn.steps.find((step) => step.moveId === "flashcannon")!.hits[0];
    const pane = calculateDoublesMoves(analytic, "own-left", "opponent-left").results.find((row) => row.moveId === "flashcannon")!;
    expect({ kind: pane.kind, min: pane.min, max: pane.max }).toEqual({ kind: "calculated", min: hit.min, max: hit.max });
    expect(turn.startRows.find((row) => row.slot === "own-left")!.row).toMatchObject({ kind: "calculated", min: 35, max: 42 });
    // F05a: Azumarill's Aqua Jet comes before Dracozolt: Bolt Beak 116-138, not doubled.
    const beak = calculateDoublesMoves(await input(find(READY, "F05a")), "own-left", "opponent-left").results.find((row) => row.moveId === "boltbeak")!;
    expect({ kind: beak.kind, min: beak.min, max: beak.max }).toEqual({ kind: "calculated", min: 116, max: 138 });
    // A Speed tie with the other Magnezone: the order is not known as the turn starts.
    const tie = calculateDoublesMoves(await input(turnOf("sv", {
      "own-left": mon("Magnezone", "Analytic", { move: "Flash Cannon", target: "opponent-left" }), "own-right": mon("Magnezone", "Sturdy"),
      "opponent-left": mon("Blastoise", "Torrent"), "opponent-right": mon("Garchomp", "Rough Skin"),
    })), "own-left", "opponent-left").results.find((row) => row.moveId === "flashcannon")!;
    expect({ kind: tie.kind, reason: tie.reason }).toEqual({ kind: "needs-context", reason: "Analytic: needs the turn order (Speed tie at 80)." });
  });

  it("Clangorous Soulblaze takes its own spread target (fix-status 18)", async () => {
    const usum = await input(find(READY, "R06"));
    expect(doublesTargetRule(usum, "own-left", "clangingscales")).toEqual({ kind: "auto", hits: ["opponent-left", "opponent-right"] });
    const plain = { ...usum, pokemon: { ...usum.pokemon, "own-left": { ...usum.pokemon["own-left"]!, contexts: {} } } };
    expect(doublesTargetRule(plain, "own-left", "clangingscales").kind).toBe("auto");
    expect(doublesTargetRule(plain, "own-left", "dragonclaw")).toEqual({ kind: "choose", options: ["opponent-left", "opponent-right", "own-right"] });
  });
});

describe("round 1 engine fixes: Unnerve and As One from a third Pokémon", () => {
  it("a resist Berry the calculation would read otherwise is not estimated in the turn and in the Moves pane", async () => {
    // Calyrex-Shadow's As One stops Venusaur's Coba Berry; the calculation reads only the attacker's Unnerve.
    const asOne = await input(find(GUARDED, "F30d"));
    const turn = calculateDoublesTurn(asOne);
    expect(turn.status === "not-estimated" && turn.reason).toBe("As One (Spectrier) is not modelled in 2v2.");
    const pane = calculateDoublesMoves(asOne, "own-left", "opponent-left").results;
    expect(pane.find((row) => row.moveId === "airslash")).toMatchObject({ kind: "unsupported", reason: "As One (Spectrier) is not modelled in 2v2." });
    expect(pane.find((row) => row.moveId === "flamethrower")).toMatchObject({ kind: "calculated" });
  });
});
