import { describe, expect, it } from "vitest";
import { calculateMatchup } from "@/app/lib/battle/calculate";
import { doublesTargetRule } from "@/app/lib/battle/doubles-targets";
import { calculateDoublesMoves, calculateDoublesTurn } from "@/app/lib/battle/doubles-turn";
import type { DoublesPokemonInput, DoublesSlotId, DoublesTurnInput, DoublesTurnResult } from "@/app/lib/battle/doubles-types";
import { loadBattleRuntime } from "@/app/lib/battle/load-runtime";
import { createBuild, createConditions, createSide, defaultAbilityActive } from "@/app/lib/battle/model";
import { championsRuntime, type BattleRuntime } from "@/app/lib/battle/runtime";
import type { BattleBuild, BattleConditions, BattleGame, MoveContext, MoveDamageResult, StatTable } from "@/app/lib/battle/types";

/**
 * A Pokémon fainted before the turn with no replacement left: in 2v2 the UI passes its slot as null (doubles-types.ts
 * DoublesTurnInput.pokemon). Pinned Showdown c23d2e94 keeps it in its slot with fainted set, and allies(), foes(),
 * adjacency and every event skip it: it takes no action, a move aimed at it goes to the other foe, a spread move counts only
 * the Pokémon in place (one target: no spread modifier), its partner gets none of its effects, and side.totalFainted counts
 * it (Last Respects). The cases' values are the exact oracle of scripts/.cache/calc-audit/2v2/verify/sim-dfs.ts, the slot's
 * Pokémon entering at the start and fainting before the turn (fainted-engine/real-battle.ts gives the same turns from a real
 * battle where it was knocked out the turn before). Level 50, 31 IVs, Serious nature and 0 EVs / Stat Points unless set.
 * Generated by scripts/.cache/calc-audit/2v2/fainted-engine/gen-fainted-tests.ts.
 */
type Stat = "hp" | "atk" | "def" | "spa" | "spd" | "spe";
type Mon = {
  species: string; appSpecies?: string; ability: string; item?: string; nature?: string; evs?: Partial<Record<Stat, number>>;
  ivs?: Partial<Record<Stat, number>>; level?: number; hp?: number; status?: BattleBuild["status"];
  boosts?: Partial<Record<Exclude<Stat, "hp">, number>>; absent?: boolean; move: string | null; target?: DoublesSlotId; context?: MoveContext;
};
type Field = Partial<Pick<BattleConditions, "weather" | "terrain">>;
type HP = { start: number; maximum: number; low: number; high: number; min: number; max: number; average: number; koChance: number; faintsBeforeMoving?: number };
type Hit = { slot: DoublesSlotId; reached: number; koChance: number; min?: number; max?: number; kind?: "blocked" };
type Step = { moveId: string; moves: number; order: [number, number][]; hits: Hit[] };
type Case = {
  id: string; game: "sv" | "swsh" | "usum" | "champions"; title: string; checks: string; field?: Field;
  slots: Record<DoublesSlotId, Mon>; hp: Record<DoublesSlotId, HP | null>; steps: Partial<Record<DoublesSlotId, Step>>;
};

const GAMES: Record<Case["game"], BattleGame> = { sv: "scarlet_violet", swsh: "sword_shield", usum: "ultra_sun_ultra_moon", champions: "champions" };
const SLOTS: DoublesSlotId[] = ["own-left", "own-right", "opponent-left", "opponent-right"];
const id = (text: string) => text.toLowerCase().replace(/[^a-z0-9]+/g, "");
const ZERO = { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 };

/** The app build for an oracle set: Showdown names as ids, EVs (native) or Stat Points (Champions), the start state. */
function caseBuild(m: Mon, runtime: BattleRuntime): BattleBuild {
  const base = createBuild(m.appSpecies ?? id(m.species), runtime);
  const abilityId = id(m.ability);
  const shared = {
    nature: m.nature ?? "Serious", abilityId, abilityActive: defaultAbilityActive(abilityId), itemId: id(m.item ?? ""),
    boosts: { atk: 0, def: 0, spa: 0, spd: 0, spe: 0, ...m.boosts }, currentHP: m.hp ?? null, status: m.status ?? "",
  };
  return (base.game === "champions"
    ? { ...base, ...shared, points: { ...ZERO, ...m.evs } }
    : { ...base, ...shared, native: { level: m.level ?? 50, evs: { ...ZERO, ...m.evs }, ivs: { hp: 31, atk: 31, def: 31, spa: 31, spd: 31, spe: 31, ...m.ivs } } }) as BattleBuild;
}
async function caseInput(c: Case): Promise<DoublesTurnInput> {
  const runtime = await loadBattleRuntime(GAMES[c.game]);
  const field: BattleConditions = { ...createConditions(), gameType: "Doubles", weather: c.field?.weather ?? "", terrain: c.field?.terrain ?? "", attackerSide: createSide(), defenderSide: createSide() };
  const pokemon = Object.fromEntries(SLOTS.map((slot) => {
    const m = c.slots[slot];
    // The fainted Pokémon's slot is empty in the input.
    if (m.absent) return [slot, null];
    const moveId = m.move === null ? null : id(m.move);
    const entry: DoublesPokemonInput = {
      build: caseBuild(m, runtime), contexts: moveId && m.context ? { [moveId]: m.context } : {}, charged: false, action: { moveId, target: m.target ?? null },
    };
    return [slot, entry];
  })) as Record<DoublesSlotId, DoublesPokemonInput | null>;
  return { runtime, field, pokemon };
}

/** cases-fainted.ts with the oracle's values (verify/results/<id>.json). */
const CASES: Case[] = [
  {id:"K01a",game:"sv",title:"Rock Slide into a lone foe (sv)",checks:"Blastoise fainted before the turn: Rock Slide hits Snorlax alone at full damage.",slots:{"own-left":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Rock Slide"},"own-right":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-left":{species:"Blastoise",ability:"Torrent",absent:true,move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}},hp:{"own-left":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"own-right":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-left":null,"opponent-right":{start:235,maximum:235,low:174,high:163,min:163,max:174,average:168.875,koChance:0}},steps:{"own-left":{moveId:"rockslide",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:61,max:72}]}}},
  {id:"K01b",game:"swsh",title:"Rock Slide into a lone foe (swsh)",checks:"Blastoise fainted before the turn: Rock Slide hits Snorlax alone at full damage.",slots:{"own-left":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Rock Slide"},"own-right":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-left":{species:"Blastoise",ability:"Torrent",absent:true,move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}},hp:{"own-left":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"own-right":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-left":null,"opponent-right":{start:235,maximum:235,low:174,high:163,min:163,max:174,average:168.875,koChance:0}},steps:{"own-left":{moveId:"rockslide",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:61,max:72}]}}},
  {id:"K01c",game:"usum",title:"Rock Slide into a lone foe (usum)",checks:"Blastoise fainted before the turn: Rock Slide hits Snorlax alone at full damage.",slots:{"own-left":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Rock Slide"},"own-right":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-left":{species:"Blastoise",ability:"Torrent",absent:true,move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}},hp:{"own-left":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"own-right":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-left":null,"opponent-right":{start:235,maximum:235,low:174,high:163,min:163,max:174,average:168.875,koChance:0}},steps:{"own-left":{moveId:"rockslide",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:61,max:72}]}}},
  {id:"K01d",game:"champions",title:"Rock Slide into a lone foe (champions)",checks:"Blastoise fainted before the turn: Rock Slide hits Snorlax alone at full damage.",slots:{"own-left":{species:"Garchomp",ability:"Sand Veil",move:"Rock Slide"},"own-right":{species:"Venusaur",ability:"Overgrow",evs:{spe:1},move:null},"opponent-left":{species:"Blastoise",ability:"Torrent",absent:true,move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:1},move:null}},hp:{"own-left":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"own-right":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-left":null,"opponent-right":{start:235,maximum:235,low:184,high:175,min:175,max:184,average:179.875,koChance:0}},steps:{"own-left":{moveId:"rockslide",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:51,max:60}]}}},
  {id:"K02a",game:"sv",title:"Heat Wave into a lone foe",checks:"Snorlax fainted before the turn: Heat Wave hits Venusaur alone at full damage.",slots:{"own-left":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:null},"own-right":{species:"Charizard",ability:"Blaze",nature:"Timid",evs:{spa:252,spe:252},move:"Heat Wave"},"opponent-left":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},absent:true,move:null}},hp:{"own-left":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"own-right":{start:153,maximum:153,low:153,high:153,min:153,max:153,average:153,koChance:0},"opponent-left":{start:155,maximum:155,low:9,high:0,min:0,max:9,average:1.8125,koChance:0.6875},"opponent-right":null},steps:{"own-right":{moveId:"heatwave",moves:1,order:[[1,1]],hits:[{slot:"opponent-left",reached:1,koChance:0.6875,min:146,max:174}]}}},
  {id:"K02b",game:"champions",title:"Heat Wave into a lone foe (champions)",checks:"Snorlax fainted before the turn: Heat Wave hits Venusaur alone at full damage.",slots:{"own-left":{species:"Garchomp",ability:"Sand Veil",move:null},"own-right":{species:"Charizard",ability:"Blaze",move:"Heat Wave"},"opponent-left":{species:"Venusaur",ability:"Overgrow",evs:{spe:1},move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:1},absent:true,move:null}},hp:{"own-left":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"own-right":{start:153,maximum:153,low:153,high:153,min:153,max:153,average:153,koChance:0},"opponent-left":{start:155,maximum:155,low:39,high:17,min:17,max:39,average:29.125,koChance:0},"opponent-right":null},steps:{"own-right":{moveId:"heatwave",moves:1,order:[[1,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,min:116,max:138}]}}},
  {id:"K03a",game:"sv",title:"Earthquake with a fainted ally",checks:"Charizard fainted before the turn: Earthquake hits only the two foes, each at 0.75.",slots:{"own-left":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Earthquake"},"own-right":{species:"Charizard",ability:"Blaze",nature:"Timid",evs:{spa:252,spe:252},absent:true,move:null},"opponent-left":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}},hp:{"own-left":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"own-right":null,"opponent-left":{start:155,maximum:155,low:80,high:67,min:67,max:80,average:74.0625,koChance:0},"opponent-right":{start:235,maximum:235,low:144,high:127,min:127,max:144,average:136.0625,koChance:0}},steps:{"own-left":{moveId:"earthquake",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:91,max:108},{slot:"opponent-left",reached:1,koChance:0,min:75,max:88}]}}},
  {id:"K03b",game:"swsh",title:"Earthquake with a fainted ally into a lone foe",checks:"Charizard and Venusaur fainted before the turn: Earthquake hits Snorlax alone at full damage.",slots:{"own-left":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Earthquake"},"own-right":{species:"Charizard",ability:"Blaze",nature:"Timid",evs:{spa:252,spe:252},absent:true,move:null},"opponent-left":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},absent:true,move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}},hp:{"own-left":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"own-right":null,"opponent-left":null,"opponent-right":{start:235,maximum:235,low:114,high:91,min:91,max:114,average:102.5,koChance:0}},steps:{"own-left":{moveId:"earthquake",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:121,max:144}]}}},
  {id:"K04a",game:"sv",title:"Dragon Claw aimed at the fainted foe",checks:"Blastoise fainted before the turn: Dragon Claw aimed at it hits Snorlax.",slots:{"own-left":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Dragon Claw",target:"opponent-left"},"own-right":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-left":{species:"Blastoise",ability:"Torrent",absent:true,move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}},hp:{"own-left":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"own-right":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-left":null,"opponent-right":{start:235,maximum:235,low:138,high:120,min:120,max:138,average:129.125,koChance:0}},steps:{"own-left":{moveId:"dragonclaw",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:97,max:115}]}}},
  {id:"K04b",game:"usum",title:"Dragon Claw aimed at your fainted Pokémon (from the far side)",checks:"Your Venusaur fainted before the turn: the opponent's Dragon Claw aimed at it hits Snorlax.",slots:{"own-left":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},absent:true,move:null},"own-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null},"opponent-left":{species:"Blastoise",ability:"Torrent",move:null},"opponent-right":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Dragon Claw",target:"own-left"}},hp:{"own-left":null,"own-right":{start:235,maximum:235,low:138,high:120,min:120,max:138,average:129.125,koChance:0},"opponent-left":{start:154,maximum:154,low:154,high:154,min:154,max:154,average:154,koChance:0},"opponent-right":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0}},steps:{"opponent-right":{moveId:"dragonclaw",moves:1,order:[[1,1]],hits:[{slot:"own-right",reached:1,koChance:0,min:97,max:115}]}}},
  {id:"K05a",game:"sv",title:"Two attacks into the last foe, which attacks back",checks:"Dragon Claw, then Flamethrower into Snorlax (its Sitrus Berry between them), then its Body Slam into Garchomp.",slots:{"own-left":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Dragon Claw",target:"opponent-right"},"own-right":{species:"Charizard",ability:"Blaze",nature:"Timid",evs:{spa:252,spe:252},move:"Flamethrower",target:"opponent-right"},"opponent-left":{species:"Blastoise",ability:"Torrent",absent:true,move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},item:"Sitrus Berry",move:"Body Slam",target:"own-left"}},hp:{"own-left":{start:183,maximum:183,low:128,high:117,min:117,max:128,average:122.875,koChance:0},"own-right":{start:153,maximum:153,low:153,high:153,min:153,max:153,average:153,koChance:0},"opponent-left":null,"opponent-right":{start:235,maximum:235,low:134,high:110,min:110,max:134,average:123,koChance:0}},steps:{"own-left":{moveId:"dragonclaw",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:97,max:115}]},"own-right":{moveId:"flamethrower",moves:1,order:[[2,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:33,max:39}]},"opponent-right":{moveId:"bodyslam",moves:1,order:[[3,1]],hits:[{slot:"own-left",reached:1,koChance:0,min:55,max:66}]}}},
  {id:"K05b",game:"swsh",title:"Two attacks into the last foe, which attacks back (swsh)",checks:"Dragon Claw, then Air Slash into Snorlax, then its Body Slam into Charizard.",slots:{"own-left":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Dragon Claw",target:"opponent-left"},"own-right":{species:"Charizard",ability:"Blaze",nature:"Timid",evs:{spa:252,spe:252},move:"Air Slash",target:"opponent-left"},"opponent-left":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},item:"Sitrus Berry",move:"Body Slam",target:"own-right"},"opponent-right":{species:"Blastoise",ability:"Torrent",absent:true,move:null}},hp:{"own-left":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"own-right":{start:153,maximum:153,low:89,high:77,min:77,max:89,average:83.4375,koChance:0},"opponent-left":{start:235,maximum:235,low:144,high:115,min:115,max:144,average:129.8125,koChance:0},"opponent-right":null},steps:{"own-left":{moveId:"dragonclaw",moves:1,order:[[1,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,min:97,max:115}]},"own-right":{moveId:"airslash",moves:1,order:[[2,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,min:52,max:63}]},"opponent-left":{moveId:"bodyslam",moves:1,order:[[3,1]],hits:[{slot:"own-right",reached:1,koChance:0,min:64,max:76}]}}},
  {id:"K05c",game:"usum",title:"Two attacks into the last foe, which attacks back (usum)",checks:"Dragon Claw, then Flamethrower into Snorlax, then its Body Slam into Garchomp.",slots:{"own-left":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Dragon Claw",target:"opponent-right"},"own-right":{species:"Charizard",ability:"Blaze",nature:"Timid",evs:{spa:252,spe:252},move:"Flamethrower",target:"opponent-right"},"opponent-left":{species:"Blastoise",ability:"Torrent",absent:true,move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},item:"Sitrus Berry",move:"Body Slam",target:"own-left"}},hp:{"own-left":{start:183,maximum:183,low:128,high:117,min:117,max:128,average:122.875,koChance:0},"own-right":{start:153,maximum:153,low:153,high:153,min:153,max:153,average:153,koChance:0},"opponent-left":null,"opponent-right":{start:235,maximum:235,low:134,high:110,min:110,max:134,average:123,koChance:0}},steps:{"own-left":{moveId:"dragonclaw",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:97,max:115}]},"own-right":{moveId:"flamethrower",moves:1,order:[[2,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:33,max:39}]},"opponent-right":{moveId:"bodyslam",moves:1,order:[[3,1]],hits:[{slot:"own-left",reached:1,koChance:0,min:55,max:66}]}}},
  {id:"K05d",game:"champions",title:"Two attacks into the last foe, which attacks back (champions)",checks:"Dragon Claw, then Flamethrower into Snorlax, then its Body Slam into Garchomp.",slots:{"own-left":{species:"Garchomp",ability:"Sand Veil",move:"Dragon Claw",target:"opponent-right"},"own-right":{species:"Charizard",ability:"Blaze",move:"Flamethrower",target:"opponent-right"},"opponent-left":{species:"Blastoise",ability:"Torrent",absent:true,move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:1},item:"Sitrus Berry",move:"Body Slam",target:"own-left"}},hp:{"own-left":{start:183,maximum:183,low:128,high:117,min:117,max:128,average:122.875,koChance:0},"own-right":{start:153,maximum:153,low:153,high:153,min:153,max:153,average:153,koChance:0},"opponent-left":null,"opponent-right":{start:235,maximum:235,low:129,high:166,min:118,max:175,average:142.890625,koChance:0}},steps:{"own-left":{moveId:"dragonclaw",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:81,max:96}]},"own-right":{moveId:"flamethrower",moves:1,order:[[2,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:25,max:31}]},"opponent-right":{moveId:"bodyslam",moves:1,order:[[3,1]],hits:[{slot:"own-left",reached:1,koChance:0,min:55,max:66}]}}},
  {id:"K05e",game:"sv",title:"Two attacks knock out the last foe before it moves",checks:"Snorlax at 120: the two attacks can knock it out before its Body Slam.",slots:{"own-left":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Dragon Claw",target:"opponent-right"},"own-right":{species:"Charizard",ability:"Blaze",nature:"Timid",evs:{spa:252,spe:252},move:"Flamethrower",target:"opponent-right"},"opponent-left":{species:"Blastoise",ability:"Torrent",absent:true,move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},hp:120,move:"Body Slam",target:"own-left"}},hp:{"own-left":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"own-right":{start:153,maximum:153,low:153,high:153,min:153,max:153,average:153,koChance:0},"opponent-left":null,"opponent-right":{start:120,maximum:235,low:0,high:0,min:0,max:0,average:0,koChance:1,faintsBeforeMoving:1}},steps:{"own-left":{moveId:"dragonclaw",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:97,max:115}]},"own-right":{moveId:"flamethrower",moves:1,order:[[2,1]],hits:[{slot:"opponent-right",reached:1,koChance:1,min:33,max:39}]},"opponent-right":{moveId:"bodyslam",moves:0,order:[[3,1]],hits:[]}}},
  {id:"K06a",game:"sv",title:"The last foe's Rock Slide into both of yours",checks:"Rock Slide from the last foe hits Venusaur and Blastoise at 0.75.",slots:{"own-left":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"own-right":{species:"Blastoise",ability:"Torrent",move:null},"opponent-left":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},absent:true,move:null},"opponent-right":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Rock Slide"}},hp:{"own-left":{start:155,maximum:155,low:117,high:110,min:110,max:117,average:113.8125,koChance:0},"own-right":{start:154,maximum:154,low:121,high:115,min:115,max:121,average:118.375,koChance:0},"opponent-left":null,"opponent-right":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0}},steps:{"opponent-right":{moveId:"rockslide",moves:1,order:[[1,1]],hits:[{slot:"own-left",reached:1,koChance:0,min:38,max:45},{slot:"own-right",reached:1,koChance:0,min:33,max:39}]}}},
  {id:"K06b",game:"champions",title:"The last foe's Earthquake with its ally fainted",checks:"Earthquake from the last foe hits only your two, at 0.75.",slots:{"own-left":{species:"Venusaur",ability:"Overgrow",evs:{spe:1},move:null},"own-right":{species:"Blastoise",ability:"Torrent",move:null},"opponent-left":{species:"Snorlax",ability:"Thick Fat",evs:{spe:1},absent:true,move:null},"opponent-right":{species:"Garchomp",ability:"Sand Veil",move:"Earthquake"}},hp:{"own-left":{start:155,maximum:155,low:94,high:82,min:82,max:94,average:87.75,koChance:0},"own-right":{start:154,maximum:154,low:100,high:90,min:90,max:100,average:95.375,koChance:0},"opponent-left":null,"opponent-right":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0}},steps:{"opponent-right":{moveId:"earthquake",moves:1,order:[[1,1]],hits:[{slot:"own-left",reached:1,koChance:0,min:61,max:73},{slot:"own-right",reached:1,koChance:0,min:54,max:64}]}}},
  {id:"K07a",game:"sv",title:"Helping Hand with the ally fainted",checks:"Charizard fainted before the turn: Helping Hand has no target and fails; Rock Slide hits Clefable alone.",slots:{"own-left":{species:"Clefable",ability:"Magic Guard",move:"Helping Hand"},"own-right":{species:"Charizard",ability:"Blaze",nature:"Timid",evs:{spa:252,spe:252},absent:true,move:null},"opponent-left":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Rock Slide"},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}},hp:{"own-left":{start:170,maximum:170,low:114,high:104,min:104,max:114,average:109.3125,koChance:0},"own-right":null,"opponent-left":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"opponent-right":{start:235,maximum:235,low:235,high:235,min:235,max:235,average:235,koChance:0}},steps:{"own-left":{moveId:"helpinghand",moves:1,order:[[1,1]],hits:[]},"opponent-left":{moveId:"rockslide",moves:1,order:[[2,1]],hits:[{slot:"own-left",reached:1,koChance:0,min:56,max:66}]}}},
  {id:"K07b",game:"sv",title:"Aromatic Mist with the ally fainted",checks:"Charizard fainted before the turn: Aromatic Mist (Alcremie 84) has no target and fails before Snorlax's Body Slam.",slots:{"own-left":{species:"Alcremie",ability:"Sweet Veil",move:"Aromatic Mist"},"own-right":{species:"Charizard",ability:"Blaze",nature:"Timid",evs:{spa:252,spe:252},absent:true,move:null},"opponent-left":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:"Body Slam",target:"own-left"}},hp:{"own-left":{start:140,maximum:140,low:73,high:61,min:61,max:73,average:67.4375,koChance:0},"own-right":null,"opponent-left":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"opponent-right":{start:235,maximum:235,low:235,high:235,min:235,max:235,average:235,koChance:0}},steps:{"own-left":{moveId:"aromaticmist",moves:1,order:[[1,1]],hits:[]},"opponent-right":{moveId:"bodyslam",moves:1,order:[[2,1]],hits:[{slot:"own-left",reached:1,koChance:0,min:67,max:79}]}}},
  {id:"K08a",game:"champions",title:"Follow Me user fainted",checks:"Clefable fainted before the turn: no Follow Me, Dragon Claw hits Blastoise.",slots:{"own-left":{species:"Garchomp",ability:"Sand Veil",move:"Dragon Claw",target:"opponent-right"},"own-right":{species:"Venusaur",ability:"Overgrow",evs:{spe:1},move:null},"opponent-left":{species:"Clefable",ability:"Magic Guard",absent:true,move:"Follow Me"},"opponent-right":{species:"Blastoise",ability:"Torrent",move:null}},hp:{"own-left":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"own-right":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-left":null,"opponent-right":{start:154,maximum:154,low:96,high:85,min:85,max:96,average:91.0625,koChance:0}},steps:{"own-left":{moveId:"dragonclaw",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:58,max:69}]}}},
  {id:"K09a",game:"sv",title:"Friend Guard partner fainted",checks:"Clefairy fainted before the turn: no Friend Guard on Blastoise.",slots:{"own-left":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Dragon Claw",target:"opponent-right"},"own-right":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-left":{species:"Clefairy",ability:"Friend Guard",absent:true,move:null},"opponent-right":{species:"Blastoise",ability:"Torrent",move:null}},hp:{"own-left":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"own-right":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-left":null,"opponent-right":{start:154,maximum:154,low:85,high:72,min:72,max:85,average:78.6875,koChance:0}},steps:{"own-left":{moveId:"dragonclaw",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:69,max:82}]}}},
  {id:"K10a",game:"sv",title:"Intimidate holder fainted",checks:"Incineroar's Intimidate ran as it entered (-1 Attack on both of yours, as Showdown's start shows), then it fainted: nothing more.",slots:{"own-left":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},boosts:{atk:-1},move:"Dragon Claw",target:"opponent-right"},"own-right":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},boosts:{atk:-1},move:null},"opponent-left":{species:"Incineroar",ability:"Intimidate",absent:true,move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}},hp:{"own-left":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"own-right":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-left":null,"opponent-right":{start:235,maximum:235,low:169,high:157,min:157,max:169,average:163.875,koChance:0}},steps:{"own-left":{moveId:"dragonclaw",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:66,max:78}]}}},
  {id:"K10b",game:"sv",title:"Unnerve holder fainted: the Sitrus Berry is eaten at the start",checks:"Tyranitar fainted before the turn: Snorlax at 100/235 eats its Sitrus Berry as the turn starts (158), then Dragon Claw.",slots:{"own-left":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"own-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},item:"Sitrus Berry",hp:100,move:null},"opponent-left":{species:"Tyranitar",ability:"Unnerve",absent:true,move:null},"opponent-right":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Dragon Claw",target:"own-right"}},hp:{"own-left":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"own-right":{start:158,maximum:235,low:61,high:43,min:43,max:61,average:52.125,koChance:0},"opponent-left":null,"opponent-right":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0}},steps:{"opponent-right":{moveId:"dragonclaw",moves:1,order:[[1,1]],hits:[{slot:"own-right",reached:1,koChance:0,min:97,max:115}]}}},
  {id:"K10c",game:"sv",title:"Unnerve holder fainted: the Sitrus Berry after the hit",checks:"Tyranitar fainted before the turn: Dragon Claw takes Snorlax under half and it eats its Sitrus Berry.",slots:{"own-left":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"own-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},item:"Sitrus Berry",hp:150,move:null},"opponent-left":{species:"Tyranitar",ability:"Unnerve",absent:true,move:null},"opponent-right":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Dragon Claw",target:"own-right"}},hp:{"own-left":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"own-right":{start:150,maximum:235,low:111,high:93,min:93,max:111,average:102.125,koChance:0},"opponent-left":null,"opponent-right":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0}},steps:{"opponent-right":{moveId:"dragonclaw",moves:1,order:[[1,1]],hits:[{slot:"own-right",reached:1,koChance:0,min:97,max:115}]}}},
  {id:"K11a",game:"sv",title:"Last Respects with the ally fainted (count 0 given)",checks:"Charizard fainted before the turn (side.totalFainted 1): Last Respects into Venusaur has 100 power though the count given is 0.",slots:{"own-left":{species:"Basculegion",ability:"Swift Swim",move:"Last Respects",target:"opponent-left",context:{fainted:0}},"own-right":{species:"Charizard",ability:"Blaze",nature:"Timid",evs:{spa:252,spe:252},absent:true,move:null},"opponent-left":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}},hp:{"own-left":{start:195,maximum:195,low:195,high:195,min:195,max:195,average:195,koChance:0},"own-right":null,"opponent-left":{start:155,maximum:155,low:82,high:68,min:68,max:82,average:75.5,koChance:0},"opponent-right":{start:235,maximum:235,low:235,high:235,min:235,max:235,average:235,koChance:0}},steps:{"own-left":{moveId:"lastrespects",moves:1,order:[[1,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,min:73,max:87}]}}},
  {id:"K11b",game:"sv",title:"Last Respects with the ally fainted (count 1 given)",checks:"The count given already counts Charizard: 100 power, not 150.",slots:{"own-left":{species:"Basculegion",ability:"Swift Swim",move:"Last Respects",target:"opponent-left",context:{fainted:1}},"own-right":{species:"Charizard",ability:"Blaze",nature:"Timid",evs:{spa:252,spe:252},absent:true,move:null},"opponent-left":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}},hp:{"own-left":{start:195,maximum:195,low:195,high:195,min:195,max:195,average:195,koChance:0},"own-right":null,"opponent-left":{start:155,maximum:155,low:82,high:68,min:68,max:82,average:75.5,koChance:0},"opponent-right":{start:235,maximum:235,low:235,high:235,min:235,max:235,average:235,koChance:0}},steps:{"own-left":{moveId:"lastrespects",moves:1,order:[[1,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,min:73,max:87}]}}},
  {id:"K11c",game:"champions",title:"Last Respects with the ally fainted (champions)",checks:"Charizard fainted before the turn: Last Respects has 100 power.",slots:{"own-left":{species:"Basculegion",ability:"Swift Swim",move:"Last Respects",target:"opponent-left"},"own-right":{species:"Charizard",ability:"Blaze",absent:true,move:null},"opponent-left":{species:"Venusaur",ability:"Overgrow",evs:{spe:1},move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:1},move:null}},hp:{"own-left":{start:195,maximum:195,low:195,high:195,min:195,max:195,average:195,koChance:0},"own-right":null,"opponent-left":{start:155,maximum:155,low:82,high:68,min:68,max:82,average:75.5,koChance:0},"opponent-right":{start:235,maximum:235,low:235,high:235,min:235,max:235,average:235,koChance:0}},steps:{"own-left":{moveId:"lastrespects",moves:1,order:[[1,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,min:73,max:87}]}}},
  {id:"K12a",game:"sv",title:"Plus with the Minus partner fainted",checks:"Minun fainted before the turn: Plus does not raise Plusle's Sp. Atk.",slots:{"own-left":{species:"Plusle",ability:"Plus",move:"Thunderbolt",target:"opponent-right"},"own-right":{species:"Minun",ability:"Minus",absent:true,move:null},"opponent-left":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-right":{species:"Blastoise",ability:"Torrent",move:null}},hp:{"own-left":{start:135,maximum:135,low:135,high:135,min:135,max:135,average:135,koChance:0},"own-right":null,"opponent-left":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-right":{start:154,maximum:154,low:68,high:50,min:50,max:68,average:58.875,koChance:0}},steps:{"own-left":{moveId:"thunderbolt",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:86,max:104}]}}},
  {id:"K13a",game:"swsh",title:"Flower Gift partner fainted in sun",checks:"Cherrim fainted before the turn: no Flower Gift Attack for Garchomp.",field:{weather:"Sun"},slots:{"own-left":{species:"Cherrim",ability:"Flower Gift",absent:true,move:null},"own-right":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Dragon Claw",target:"opponent-left"},"opponent-left":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null},"opponent-right":{species:"Blastoise",ability:"Torrent",move:null}},hp:{"own-left":null,"own-right":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"opponent-left":{start:235,maximum:235,low:138,high:120,min:120,max:138,average:129.125,koChance:0},"opponent-right":{start:154,maximum:154,low:154,high:154,min:154,max:154,average:154,koChance:0}},steps:{"own-right":{moveId:"dragonclaw",moves:1,order:[[1,1]],hits:[{slot:"opponent-left",reached:1,koChance:0,min:97,max:115}]}}},
  {id:"K14a",game:"sv",title:"Armor Tail partner fainted: a priority move gets through",checks:"Farigiraf fainted before the turn: Ice Shard (+1) hits Garchomp.",slots:{"own-left":{species:"Weavile",ability:"Pressure",move:"Ice Shard",target:"opponent-right"},"own-right":{species:"Blastoise",ability:"Torrent",move:null},"opponent-left":{species:"Farigiraf",ability:"Armor Tail",absent:true,move:null},"opponent-right":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:null}},hp:{"own-left":{start:145,maximum:145,low:145,high:145,min:145,max:145,average:145,koChance:0},"own-right":{start:154,maximum:154,low:154,high:154,min:154,max:154,average:154,koChance:0},"opponent-left":null,"opponent-right":{start:183,maximum:183,low:71,high:47,min:47,max:71,average:59,koChance:0}},steps:{"own-left":{moveId:"iceshard",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:112,max:136}]}}},
  {id:"K15a",game:"usum",title:"Battery partner fainted",checks:"Charjabug fainted before the turn: no Battery on Pikachu's Thunderbolt.",slots:{"own-left":{species:"Pikachu",ability:"Static",move:"Thunderbolt",target:"opponent-right"},"own-right":{species:"Charjabug",ability:"Battery",absent:true,move:null},"opponent-left":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-right":{species:"Blastoise",ability:"Torrent",move:null}},hp:{"own-left":{start:110,maximum:110,low:110,high:110,min:110,max:110,average:110,koChance:0},"own-right":null,"opponent-left":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-right":{start:154,maximum:154,low:94,high:82,min:82,max:94,average:89.25,koChance:0}},steps:{"own-left":{moveId:"thunderbolt",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:60,max:72}]}}},
  {id:"K16a",game:"sv",title:"Sword of Ruin holder fainted",checks:"Chien-Pao fainted before the turn: Snorlax's Defense is not lowered.",slots:{"own-left":{species:"Garchomp",ability:"Rough Skin",nature:"Jolly",evs:{atk:252,spe:252},move:"Dragon Claw",target:"opponent-right"},"own-right":{species:"Chien-Pao",ability:"Sword of Ruin",absent:true,move:null},"opponent-left":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}},hp:{"own-left":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"own-right":null,"opponent-left":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-right":{start:235,maximum:235,low:138,high:120,min:120,max:138,average:129.125,koChance:0}},steps:{"own-left":{moveId:"dragonclaw",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:97,max:115}]}}},
  {id:"K17a",game:"champions",title:"Cloud Nine holder fainted in sun",checks:"Altaria fainted before the turn: the sun boosts Flamethrower.",field:{weather:"Sun"},slots:{"own-left":{species:"Garchomp",ability:"Sand Veil",move:null},"own-right":{species:"Charizard",ability:"Blaze",move:"Flamethrower",target:"opponent-right"},"opponent-left":{species:"Altaria",ability:"Cloud Nine",absent:true,move:null},"opponent-right":{species:"Venusaur",ability:"Overgrow",evs:{spe:1},move:null}},hp:{"own-left":{start:183,maximum:183,low:183,high:183,min:183,max:183,average:183,koChance:0},"own-right":{start:153,maximum:153,low:153,high:153,min:153,max:153,average:153,koChance:0},"opponent-left":null,"opponent-right":{start:155,maximum:155,low:0,high:0,min:0,max:0,average:0,koChance:1}},steps:{"own-right":{moveId:"flamethrower",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:1,min:168,max:198}]}}},
  {id:"K18a",game:"sv",title:"Lightning Rod partner fainted",checks:"Raichu fainted before the turn: Thunderbolt hits Blastoise.",slots:{"own-left":{species:"Pikachu",ability:"Static",move:"Thunderbolt",target:"opponent-right"},"own-right":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-left":{species:"Raichu",ability:"Lightning Rod",absent:true,move:null},"opponent-right":{species:"Blastoise",ability:"Torrent",move:null}},hp:{"own-left":{start:110,maximum:110,low:110,high:110,min:110,max:110,average:110,koChance:0},"own-right":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-left":null,"opponent-right":{start:154,maximum:154,low:94,high:82,min:82,max:94,average:89.25,koChance:0}},steps:{"own-left":{moveId:"thunderbolt",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:60,max:72}]}}},
  {id:"K19a",game:"sv",title:"Dragon Darts into a lone foe",checks:"Blastoise fainted before the turn: both darts hit Snorlax.",slots:{"own-left":{species:"Dragapult",ability:"Clear Body",move:"Dragon Darts",target:"opponent-right"},"own-right":{species:"Venusaur",ability:"Overgrow",evs:{spe:4},move:null},"opponent-left":{species:"Blastoise",ability:"Torrent",absent:true,move:null},"opponent-right":{species:"Snorlax",ability:"Thick Fat",evs:{spe:4},move:null}},hp:{"own-left":{start:163,maximum:163,low:163,high:163,min:163,max:163,average:163,koChance:0},"own-right":{start:155,maximum:155,low:155,high:155,min:155,max:155,average:155,koChance:0},"opponent-left":null,"opponent-right":{start:235,maximum:235,low:139,high:121,min:121,max:139,average:131.375,koChance:0}},steps:{"own-left":{moveId:"dragondarts",moves:1,order:[[1,1]],hits:[{slot:"opponent-right",reached:1,koChance:0,min:96,max:114}]}}},
];

describe("a Pokémon fainted before the turn, against pinned Showdown", () => {
  for (const c of CASES) {
    it(`${c.id}: ${c.title}`, async () => {
      const result = calculateDoublesTurn(await caseInput(c));
      expect(result.status, c.checks).toBe("ready");
      if (result.status !== "ready") return;
      for (const slot of SLOTS) {
        const want = c.hp[slot], got = result.hp[slot];
        if (!want) { expect(got, slot).toBeNull(); continue; }
        expect(got, slot).not.toBeNull();
        expect({ start: got!.start, maximum: got!.maximum, low: got!.low, high: got!.high, min: got!.min, max: got!.max }, `${c.id} ${slot}`)
          .toEqual({ start: want.start, maximum: want.maximum, low: want.low, high: want.high, min: want.min, max: want.max });
        expect(got!.average, `${c.id} ${slot} average`).toBeCloseTo(want.average, 9);
        expect(Math.abs(got!.koChance - want.koChance), `${c.id} ${slot} KO chance`).toBeLessThanOrEqual(1e-9);
        expect(got!.faintsBeforeMoving ?? 0, `${c.id} ${slot} faints before moving`).toBeCloseTo(want.faintsBeforeMoving ?? 0, 9);
      }
      // No step for the fainted Pokémon: only the slots with a move that are in place.
      expect(result.steps.map((step) => step.slot).sort()).toEqual(Object.keys(c.steps).sort());
      for (const step of result.steps) {
        const want = c.steps[step.slot]!;
        expect(step.moveId).toBe(want.moveId);
        expect(step.moves, `${c.id} ${step.slot} moves`).toBeCloseTo(want.moves, 9);
        expect(step.order.map((entry) => [entry.position, entry.chance])).toEqual(want.order);
        if (!want.hits.length) { expect(step.hits.filter((hit) => hit.reached > 0), `${c.id} ${step.slot} hits`).toEqual([]); continue; }
        expect(step.hits.map((hit) => hit.slot).sort(), `${c.id} ${step.slot} hits`).toEqual(want.hits.map((hit) => hit.slot).sort());
        for (const hit of want.hits) {
          const got = step.hits.find((h) => h.slot === hit.slot)!;
          expect(got.reached, `${c.id} ${step.slot} → ${hit.slot} reached`).toBeCloseTo(hit.reached, 9);
          expect(got.koChance, `${c.id} ${step.slot} → ${hit.slot} KO chance`).toBeCloseTo(hit.koChance, 9);
          if (hit.min !== undefined) expect({ kind: got.kind, min: got.min, max: got.max }, `${c.id} ${step.slot} → ${hit.slot}`).toEqual({ kind: "calculated", min: hit.min, max: hit.max });
          else expect(got.kind === "blocked" || got.kind === "no-damage").toBe(true);
        }
      }
    });
  }
});

// ---------------------------------------------------------------------------------------------------------------------------
// The engine's rules for empty slots (doubles-targets.ts doublesTargetRule, doubles-turn.ts), and the 1v1 parity.
// ---------------------------------------------------------------------------------------------------------------------------

type P = {
  id: string; ability?: string; item?: string; nature?: string; evs?: Partial<StatTable>; hp?: number; move?: string | null; target?: DoublesSlotId;
  contexts?: Record<string, MoveContext>;
};
function turn(runtime: BattleRuntime, slots: Record<DoublesSlotId, P | null>, field: Partial<BattleConditions> = {}): DoublesTurnInput {
  const pokemon = Object.fromEntries(SLOTS.map((slot) => {
    const p = slots[slot];
    if (!p) return [slot, null];
    const base = createBuild(p.id, runtime);
    const abilityId = p.ability ?? base.abilityId;
    const trained = base.game === "champions" ? { points: { ...ZERO, ...p.evs } } : { native: { ...base.native!, evs: { ...ZERO, ...p.evs } } };
    const build = {
      ...base, ...trained, nature: p.nature ?? "Serious", abilityId, abilityActive: defaultAbilityActive(abilityId), itemId: p.item ?? base.itemId, currentHP: p.hp ?? null,
    } as BattleBuild;
    const entry: DoublesPokemonInput = { build, contexts: p.contexts ?? {}, charged: false, action: { moveId: p.move ?? null, target: p.target ?? null } };
    return [slot, entry];
  })) as Record<DoublesSlotId, DoublesPokemonInput | null>;
  return { runtime, field: { ...createConditions(), gameType: "Doubles", ...field }, pokemon };
}
const idle = (id: string, extra: Partial<P> = {}): P => ({ id, move: null, ...extra });
function ready(result: DoublesTurnResult) {
  expect(result.status, result.status === "not-estimated" ? result.reason : result.status === "issues" ? JSON.stringify(result.issues) : "").toBe("ready");
  if (result.status !== "ready") throw new Error("not ready");
  return result;
}
const NO_FOE = "No target: both foes have fainted.";

describe("target rules with an empty slot", () => {
  it("leave the empty slot out of every option and hit list", () => {
    const lone = turn(championsRuntime, { "own-left": idle("garchomp"), "own-right": null, "opponent-left": null, "opponent-right": idle("blastoise") });
    expect(doublesTargetRule(lone, "own-left", "dragonclaw")).toEqual({ kind: "choose", options: ["opponent-right"] });
    expect(doublesTargetRule(lone, "own-left", "rockslide")).toEqual({ kind: "auto", hits: ["opponent-right"] });
    expect(doublesTargetRule(lone, "own-left", "earthquake")).toEqual({ kind: "auto", hits: ["opponent-right"] });
    expect(doublesTargetRule(lone, "opponent-right", "surf")).toEqual({ kind: "auto", hits: ["own-left"] });
    const alone = turn(championsRuntime, { "own-left": idle("clefable"), "own-right": null, "opponent-left": idle("garchomp"), "opponent-right": idle("blastoise") });
    expect(doublesTargetRule(alone, "own-left", "helpinghand")).toEqual({ kind: "auto", hits: [] });
  });

  it("give a move that can reach a foe no target once both foe slots are empty", () => {
    const won = turn(championsRuntime, { "own-left": idle("garchomp"), "own-right": idle("clefable"), "opponent-left": null, "opponent-right": null });
    // Not even the ally: a single-target move into a foe has nothing to aim at.
    expect(doublesTargetRule(won, "own-left", "dragonclaw")).toEqual({ kind: "choose", options: [] });
    expect(doublesTargetRule(won, "own-left", "rockslide")).toEqual({ kind: "auto", hits: [] });
    expect(doublesTargetRule(won, "own-left", "earthquake")).toEqual({ kind: "auto", hits: [] });
    expect(doublesTargetRule(won, "own-right", "helpinghand")).toEqual({ kind: "auto", hits: ["own-left"] });
    expect(doublesTargetRule(won, "own-left", "protect")).toEqual({ kind: "none", scope: "self" });
  });
});

/** Garchomp's Dragon Claw at `target`, the opponent-left slot empty. */
const at = (target: DoublesSlotId) => turn(championsRuntime, {
  "own-left": { id: "garchomp", ability: "sandveil", move: "dragonclaw", target }, "own-right": idle("venusaur"), "opponent-left": null, "opponent-right": idle("blastoise"),
});

describe("validation with an empty slot", () => {

  it("takes a move aimed at an empty foe slot to the other foe, as pinned Showdown retargets it (getTarget, getRandomTarget)", () => {
    expect(ready(calculateDoublesTurn(at("opponent-left")))).toEqual(ready(calculateDoublesTurn(at("opponent-right"))));
  });

  it("rejects a move aimed at an empty ally slot", () => {
    const result = calculateDoublesTurn(turn(championsRuntime, {
      "own-left": { id: "garchomp", move: "dragonclaw", target: "own-right" }, "own-right": null, "opponent-left": idle("venusaur"), "opponent-right": idle("blastoise"),
    }));
    expect(result.status).toBe("issues");
    if (result.status === "issues") expect(result.issues.actions).toEqual([{ slot: "own-left", message: "This move cannot target that Pokémon." }]);
  });
});

describe("both foes fainted", () => {
  it("is a ready turn with no steps when every move has no target", () => {
    const result = ready(calculateDoublesTurn(turn(championsRuntime, {
      "own-left": { id: "garchomp", move: "dragonclaw" }, "own-right": { id: "charizard", move: "heatwave" }, "opponent-left": null, "opponent-right": null,
    })));
    expect(result.steps).toEqual([]);
    expect(result.startRows).toEqual([]);
    expect(result.facts).toContain(NO_FOE);
    expect(result.hp["opponent-left"]).toBeNull();
    expect(result.hp["opponent-right"]).toBeNull();
    for (const slot of ["own-left", "own-right"] as const) {
      const hp = result.hp[slot]!;
      expect({ low: hp.low, high: hp.high, min: hp.min, max: hp.max, koChance: hp.koChance }).toEqual({ low: hp.start, high: hp.start, min: hp.start, max: hp.start, koChance: 0 });
      expect(hp.faintsBeforeMoving).toBeUndefined();
    }
  });

  it("still runs a move that needs no foe, numbered among the steps alone", () => {
    const result = ready(calculateDoublesTurn(turn(championsRuntime, {
      "own-left": { id: "garchomp", move: "dragonclaw" }, "own-right": { id: "clefable", ability: "magicguard", move: "lightscreen" }, "opponent-left": null, "opponent-right": null,
    })));
    expect(result.steps.map((step) => [step.slot, step.moveId, step.order])).toEqual([["own-right", "lightscreen", [{ position: 1, chance: 1 }]]]);
    expect(result.steps[0].facts.map((fact) => fact.text)).toEqual(["Light Screen starts on Clefable's side."]);
    expect(result.facts).toContain(NO_FOE);
  });

  it("is not stated while a foe is in place", () => {
    const result = ready(calculateDoublesTurn(at("opponent-right")));
    expect(result.facts).not.toContain(NO_FOE);
  });
});

describe("a move aimed at the ally with the ally slot empty", () => {
  it("fails before any later move: Helping Hand, Aromatic Mist (K07a, K07b)", async () => {
    const helping = ready(calculateDoublesTurn(turn(championsRuntime, {
      "own-left": { id: "clefable", ability: "magicguard", move: "helpinghand" }, "own-right": null,
      "opponent-left": { id: "garchomp", ability: "sandveil", move: "rockslide" }, "opponent-right": idle("blastoise"),
    })));
    expect(helping.steps.find((step) => step.slot === "own-left")).toMatchObject({ moves: 1, hits: [], facts: [{ text: "Helping Hand fails: its ally has fainted.", chance: 1 }] });
    const sv = await loadBattleRuntime("scarlet_violet");
    const mist = ready(calculateDoublesTurn(turn(sv, {
      "own-left": { id: "alcremie", ability: "sweetveil", move: "aromaticmist" }, "own-right": null,
      "opponent-left": idle("garchomp"), "opponent-right": { id: "snorlax", ability: "thickfat", move: "bodyslam", target: "own-left" },
    })));
    expect(mist.steps.map((step) => [step.slot, step.order[0].position, step.facts.map((fact) => fact.text)])).toEqual([
      ["own-left", 1, ["Aromatic Mist fails: its ally has fainted."]], ["opponent-right", 2, []],
    ]);
  });
});

describe("Last Respects", () => {
  it("counts the side's empty slot among its fainted, never twice (K11a, K11b)", async () => {
    const sv = await loadBattleRuntime("scarlet_violet");
    const line = (fainted: number | undefined) => {
      const input = turn(sv, {
        "own-left": { id: "basculegion", ability: "swiftswim", contexts: fainted === undefined ? {} : { lastrespects: { fainted } } }, "own-right": null,
        "opponent-left": idle("venusaur"), "opponent-right": idle("snorlax"),
      });
      const row = calculateDoublesMoves(input, "own-left", "opponent-left").results.find((each) => each.moveId === "lastrespects")!;
      return row.assumptions.find((text) => text.startsWith("Last Respects:"));
    };
    expect(line(undefined)).toBe("Last Respects: 1 fainted, 100 power.");
    expect(line(0)).toBe("Last Respects: 1 fainted, 100 power.");
    expect(line(1)).toBe("Last Respects: 1 fainted, 100 power.");
    expect(line(2)).toBe("Last Respects: 2 fainted, 150 power.");
  });
});

// The 1v1 calculator with gameType Doubles and Multiple targets hit off: one Pokémon per side in 2v2 is that matchup.
/** Moves whose 1v1 row depends on the turn order or an event of the turn (event-moves.ts, count-moves.ts, turn-order.ts). */
const TURN_DEPENDENT = new Set([
  "payback", "boltbeak", "fishiousrend", "analytic", "avalanche", "revenge", "assurance", "lashout", "round", "stompingtantrum", "temperflare",
  "lastrespects", "ragefist", "beatup", "suckerpunch", "thunderclap", "upperhand", "focuspunch", "fakeout", "firstimpression", "metalburst", "counter", "mirrorcoat", "comeuppance",
]);
const damage = (row: MoveDamageResult) => ({
  kind: row.kind, min: row.min, max: row.max, minPercent: row.minPercent, maxPercent: row.maxPercent, rolls: row.rolls, hits: row.hits, ohkoChance: row.ohkoChance,
  usesToKO: row.usesToKO, afterUse: row.afterUse && { start: row.afterUse.start, low: row.afterUse.low, high: row.afterUse.high, koChance: row.afterUse.koChance },
});
function expectSameRows(doubles: MoveDamageResult[], single: MoveDamageResult[]) {
  const byMove = new Map(single.map((row) => [row.moveId, row]));
  expect(doubles.map((row) => row.moveId).sort()).toEqual(single.map((row) => row.moveId).sort());
  let compared = 0;
  for (const row of doubles) {
    if (TURN_DEPENDENT.has(row.moveId)) continue;
    expect(damage(row), row.moveId).toEqual(damage(byMove.get(row.moveId)!));
    compared++;
  }
  expect(compared).toBeGreaterThan(20);
}
const oneTarget = (): BattleConditions => ({ ...createConditions(), gameType: "Doubles", multipleTargets: false });

describe("one Pokémon per side equals the 1v1 calculator in Doubles with Multiple targets hit off", () => {
  const pairs: [BattleGame, string, string][] = [
    ["champions", "garchomp", "blastoise"], ["scarlet_violet", "garchomp", "snorlax"], ["sword_shield", "charizard", "venusaur"], ["ultra_sun_ultra_moon", "garchomp", "blastoise"],
  ];
  for (const [game, attacker, defender] of pairs) {
    it(`${game}: every move of ${attacker} into ${defender} and back, single-target and spread`, async () => {
      const runtime = await loadBattleRuntime(game);
      const input = turn(runtime, { "own-left": idle(attacker), "own-right": null, "opponent-left": null, "opponent-right": idle(defender) });
      const own = input.pokemon["own-left"]!.build, foe = input.pokemon["opponent-right"]!.build;
      const rows = calculateDoublesMoves(input, "own-left", "opponent-right");
      expect(rows.issues).toEqual({ attacker: [], defender: [], field: [] });
      expectSameRows(rows.results, calculateMatchup(own, foe, oneTarget(), {}, runtime).results);
      expectSameRows(calculateDoublesMoves(input, "opponent-right", "own-left").results, calculateMatchup(foe, own, oneTarget(), {}, runtime).results);
    });
  }

  it("gives the turn's hit into the lone foe the 1v1 row: Dragon Claw, Rock Slide, Earthquake, Heat Wave", () => {
    const cases: [string, string][] = [["garchomp", "dragonclaw"], ["garchomp", "rockslide"], ["garchomp", "earthquake"], ["charizard", "heatwave"]];
    for (const [attacker, move] of cases) {
      const target = move === "dragonclaw" ? "opponent-right" : undefined;
      const input = turn(championsRuntime, { "own-left": { id: attacker, move, target }, "own-right": null, "opponent-left": null, "opponent-right": idle("snorlax") });
      const single = calculateMatchup(input.pokemon["own-left"]!.build, input.pokemon["opponent-right"]!.build, oneTarget(), {}, championsRuntime).results.find((row) => row.moveId === move)!;
      const result = ready(calculateDoublesTurn(input));
      expect(result.steps.map((step) => step.hits.map((hit) => hit.slot)), move).toEqual([["opponent-right"]]);
      const hit = result.steps[0].hits[0];
      expect({ kind: hit.kind, min: hit.min, max: hit.max, rolls: hit.row?.rolls }, move).toEqual({ kind: "calculated", min: single.min, max: single.max, rolls: single.rolls });
      expect(result.startRows.map((row) => [row.slot, row.target, damage(row.row)]), move).toEqual([["own-left", "opponent-right", damage(single)]]);
      // All lowest rolls leave the foe at its start less the lowest roll; all highest, less the highest.
      const hp = result.hp["opponent-right"]!;
      expect([hp.low, hp.high], move).toEqual([hp.start - single.min!, hp.start - single.max!]);
    }
  });

  it("gives Last Respects the 1v1 row with the empty slot as one fainted", async () => {
    const sv = await loadBattleRuntime("scarlet_violet");
    const input = turn(sv, { "own-left": idle("basculegion", { ability: "swiftswim" }), "own-right": null, "opponent-left": null, "opponent-right": idle("venusaur") });
    const row = calculateDoublesMoves(input, "own-left", "opponent-right").results.find((each) => each.moveId === "lastrespects")!;
    const single = calculateMatchup(input.pokemon["own-left"]!.build, input.pokemon["opponent-right"]!.build, oneTarget(), { lastrespects: { fainted: 1 } }, sv).results.find((each) => each.moveId === "lastrespects")!;
    expect(damage(row)).toEqual(damage(single));
  });
});
